//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ACDProxyModel.h"

@class NSArray, NSMutableArray, NSPredicate, NSString;
@protocol ACDProxyModelFilterSortDelegate;

@interface ACDFilterSortProxyModel : ACDProxyModel
{
    vector_a9c0768e _sourceToProxyMap;
    vector_a9c0768e _proxyToSourceMap;
    vector_a9c0768e _proxySectionIndex;
    vector_a9c0768e _proxySectionEndOffset;
    unsigned int _filterType;
    unsigned int _sortType;
    unsigned int _groupType;
    struct vector<bool, std::__1::allocator<bool>> _sortOrders;
    _Bool _groupOrder;
    struct unordered_map<unsigned int, std::__1::shared_ptr<std::__1::vector<id, std::__1::allocator<id>>>, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, std::__1::shared_ptr<std::__1::vector<id, std::__1::allocator<id>>>>>> _willUpdateIPKeys;
    _Bool _rebuildNoResortBackDoor;
    NSPredicate *_filterPredicate;
    NSString *_sortTerms;
    NSString *_groupKey;
    id <ACDProxyModelFilterSortDelegate> _filterSortDelegate;
    NSArray *_sortKeys;
    NSMutableArray *_groupValues;
}

@property(retain, nonatomic) NSMutableArray *groupValues; // @synthesize groupValues=_groupValues;
@property(retain, nonatomic) NSArray *sortKeys; // @synthesize sortKeys=_sortKeys;
@property(nonatomic) _Bool rebuildNoResortBackDoor; // @synthesize rebuildNoResortBackDoor=_rebuildNoResortBackDoor;
@property(nonatomic) __weak id <ACDProxyModelFilterSortDelegate> filterSortDelegate; // @synthesize filterSortDelegate=_filterSortDelegate;
@property(retain, nonatomic) NSString *groupKey; // @synthesize groupKey=_groupKey;
@property(retain, nonatomic) NSString *sortTerms; // @synthesize sortTerms=_sortTerms;
@property(retain, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)acdModel:(id)arg1 didChangeWithDelta:(id)arg2;
- (void)acdModel:(id)arg1 willChangeWithDelta:(id)arg2;
- (void)recordSortValueForIP:(unsigned int)arg1;
- (_Bool)sortValueHasChangeForIP:(unsigned int)arg1 acutalIP:(unsigned int)arg2;
- (shared_ptr_854e4988)sortValueForIP:(unsigned int)arg1;
- (void)simpleMapSourceGrouped32:(const vector_a9c0768e *)arg1 toProxy:(vector_7dcb3552 *)arg2;
- (void)simpleMapSourceGrouped:(const vector_7dcb3552 *)arg1 toProxy:(vector_7dcb3552 *)arg2;
- (void)insertUpdateProxyForSourceIndexes:(vector_a9c0768e *)arg1 proxyIndexPaths:(vector_7dcb3552 *)arg2 proxySections:(vector_a9c0768e *)arg3;
- (void)deleteUpdateProxyForProxyIndexes:(vector_7dcb3552 *)arg1 proxySections:(vector_a9c0768e *)arg2;
- (void)rebuildIndexMap;
- (id)groupValueForKeyAtIndexPath:(unsigned long long)arg1;
- (_Bool)filterIndexPath:(unsigned long long)arg1;
- (long long)compareIP:(unsigned int)arg1 withAnotherIP:(unsigned int)arg2;
- (unsigned int)sectionRowCount:(unsigned int)arg1;
- (id)groupValueForSection:(unsigned long long)arg1;
- (unsigned long long)numberOfObjects;
- (unsigned long long)numberOfRowsInSection:(unsigned long long)arg1;
- (unsigned long long)numberOfSections;
- (id)unsafeObjectAtACDIP:(unsigned long long)arg1;
- (unsigned long long)proxyACDIPToSource:(unsigned long long)arg1;
- (void)acdModelReset:(id)arg1;
- (_Bool)rebuildSortKeysFromSortTerms:(id)arg1;
- (unsigned int)rowSumBeforeGroupIndex:(unsigned int)arg1;
- (_Bool)innerStateVerify;
- (void)logVector:(const vector_a9c0768e *)arg1;
- (void)reindex;
- (unsigned int)groupType;
- (void)reset;
- (id)init;

@end

