//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ACDListModel, ACDMemoryIndex, NSArray;

@interface ACDManagedClassInfo : NSObject
{
    Class _class;
    ACDListModel *_model;
    ACDMemoryIndex *_memoryIndex;
    NSArray *_preloadPropList;
    unsigned long long _inMemPropFlag;
    unsigned long long _nextRID;
    struct ACDManagedClassInfoImp *_imp;
}

- (void).cxx_destruct;
- (void)dealloc;
- (struct ACDManagedClassInfoImp *)imp;
- (void)privateAddNew:(id)arg1;
- (id)init;

@end

