//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ACDContext.h"

@class FMDatabase, FMDatabaseQueue, NSObject;
@protocol OS_dispatch_queue;

@interface ACDStoreContext : ACDContext
{
    FMDatabase *_db;
    FMDatabaseQueue *_databaseQueue;
    void *readSpecific;
    void *writeSpecific;
    NSObject<OS_dispatch_queue> *_readQueue;
    NSObject<OS_dispatch_queue> *_writeQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *writeQueue; // @synthesize writeQueue=_writeQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *readQueue; // @synthesize readQueue=_readQueue;
- (void).cxx_destruct;
- (void)preloadProperties:(id)arg1 forClass:(Class)arg2;
- (void)asyncDBFindObjectsWithClass:(Class)arg1 sql:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)dbFindObjectsWithClass:(Class)arg1 sql:(id)arg2;
- (void)performReadWriteBlock:(CDUnknownBlockType)arg1;
- (void)performReadWriteBlockAndWait:(CDUnknownBlockType)arg1;
- (void)performReadBlock:(CDUnknownBlockType)arg1;
- (void)performReadBlockAndWait:(CDUnknownBlockType)arg1;
- (void)performBlock:(CDUnknownBlockType)arg1 readOnly:(_Bool)arg2;
- (void)performBlockAndWait:(CDUnknownBlockType)arg1 readOnly:(_Bool)arg2;
- (void)initializDatabase;
- (id)md5WithString:(id)arg1;
- (id)documentPath;
- (void)faultInObject:(id)arg1;
- (void)deliverDeltas:(id)arg1;
- (void)syncMemWithDBCache;
- (void)dealloc;
- (id)init;

@end

