//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ACDProxyModel.h"

@class NSMutableDictionary, UITableView;

@interface ACDTableViewUpdateAdapter : ACDProxyModel
{
    unsigned int _sourceCount;
    _Bool _allowDeltaUpdate;
    struct unordered_map<unsigned int, id, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, id>>> _willUpdateValues;
    NSMutableDictionary *_key2AnimationMap;
    struct map<ACDAnimationChangeType, UITableViewRowAnimation, std::__1::less<ACDAnimationChangeType>, std::__1::allocator<std::__1::pair<const ACDAnimationChangeType, UITableViewRowAnimation>>> _changeType2AnimationMap;
    long long _defaultAnimation;
    UITableView *_tableView;
    unsigned long long _sectionOffset;
}

@property(nonatomic) unsigned long long sectionOffset; // @synthesize sectionOffset=_sectionOffset;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long defaultAnimation; // @synthesize defaultAnimation=_defaultAnimation;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)handleUpdateAnimationWithDelta:(id)arg1;
- (void)clearAnimationCategory;
- (void)setAnimation:(long long)arg1 forChangeType:(int)arg2;
- (void)setUpdateAnimation:(long long)arg1 forKeys:(id)arg2;
- (void)recordValuesForWillUpdateIPs:(const vector_7dcb3552 *)arg1;
- (void)acdModel:(id)arg1 didChangeWithDelta:(id)arg2;
- (void)acdModel:(id)arg1 willChangeWithDelta:(id)arg2;
- (void)reset;
- (void)acdModelDidChangeContent:(id)arg1;
- (void)acdModelWillChangeContent:(id)arg1;
- (void)recount;
- (void)setSourceModel:(id)arg1;
- (id)init;

@end

