//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface AFViewShaker : NSObject
{
    NSArray *_views;
    unsigned long long _completedAnimations;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) unsigned long long completedAnimations; // @synthesize completedAnimations=_completedAnimations;
@property(retain, nonatomic) NSArray *views; // @synthesize views=_views;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)addShakeAnimationForView:(id)arg1 withDuration:(double)arg2;
- (void)shakeWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)shake;
- (id)initWithViewsArray:(id)arg1;
- (id)initWithView:(id)arg1;

@end

