//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseYapObject.h"

@interface BLBaseYapObject (Store)
+ (id)databaseConnectionWithAccount:(id)arg1 shouldHaveAccount:(_Bool)arg2 readOnly:(_Bool)arg3;
+ (id)databaseConnectionWithAccount:(id)arg1 readOnly:(_Bool)arg2;
+ (id)databaseWithWithAccount:(id)arg1 shouldHaveAccount:(_Bool)arg2;
+ (_Bool)shouldHaveAccountWithObject:(id)arg1;
+ (_Bool)shouldHaveAccount;
+ (id)sortDescriptorsWithSortTerm:(id)arg1 ascending:(_Bool)arg2;
+ (id)queryWithKeys:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5;
+ (id)queryWithSql:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5;
+ (void)updateObject:(id)arg1 account:(id)arg2;
+ (void)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 account:(id)arg6 completionBlock:(CDUnknownBlockType)arg7;
+ (void)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;
+ (void)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 account:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
+ (void)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
+ (id)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 account:(id)arg6;
+ (id)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5;
+ (id)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 account:(id)arg4;
+ (id)findWithPredicate:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3;
+ (void)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 account:(id)arg6 completionBlock:(CDUnknownBlockType)arg7;
+ (void)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 completionBlock:(CDUnknownBlockType)arg6;
+ (void)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 account:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
+ (void)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
+ (unsigned long long)countWithSqlAfterWhere:(id)arg1 account:(id)arg2;
+ (unsigned long long)countWithSqlAfterWhere:(id)arg1;
+ (unsigned long long)countWithKeysAndObjects:(id)arg1 account:(id)arg2;
+ (unsigned long long)countWithKeysAndObjects:(id)arg1;
+ (id)findSqlAfterWhere:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 account:(id)arg6;
+ (id)findSqlAfterWhere:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 account:(id)arg4;
+ (id)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5 account:(id)arg6;
+ (id)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 offset:(unsigned long long)arg4 length:(unsigned long long)arg5;
+ (id)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3 account:(id)arg4;
+ (id)findWithKeysAndObjects:(id)arg1 sortTerm:(id)arg2 ascending:(_Bool)arg3;
+ (void)objectWithUUID:(id)arg1 account:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (id)objectWithUUID:(id)arg1 account:(id)arg2;
+ (void)objectWithUUID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
+ (id)objectWithUUID:(id)arg1;
+ (void)asyncSaveObjects:(id)arg1 deleteObjects:(id)arg2 account:(id)arg3 complectionBlock:(CDUnknownBlockType)arg4;
+ (void)asyncSaveObjects:(id)arg1 deleteObjects:(id)arg2 complectionBlock:(CDUnknownBlockType)arg3;
+ (void)syncSaveObjects:(id)arg1 deleteObjects:(id)arg2 account:(id)arg3;
+ (void)syncSaveObjects:(id)arg1 deleteObjects:(id)arg2;
+ (void)asyncDeleteObjects:(id)arg1 account:(id)arg2 complectionBlock:(CDUnknownBlockType)arg3;
+ (void)asyncDeleteObject:(id)arg1 account:(id)arg2 complectionBlock:(CDUnknownBlockType)arg3;
+ (void)asyncDeleteObjects:(id)arg1 complectionBlock:(CDUnknownBlockType)arg2;
+ (void)asyncDeleteObject:(id)arg1 complectionBlock:(CDUnknownBlockType)arg2;
+ (void)syncDeleteObjects:(id)arg1 account:(id)arg2;
+ (void)syncDeleteObject:(id)arg1 account:(id)arg2;
+ (void)syncDeleteObjects:(id)arg1;
+ (void)syncDeleteObject:(id)arg1;
+ (void)asyncSaveObjects:(id)arg1 account:(id)arg2 complectionBlock:(CDUnknownBlockType)arg3;
+ (void)asyncSaveObject:(id)arg1 account:(id)arg2 complectionBlock:(CDUnknownBlockType)arg3;
+ (void)asyncSaveObjects:(id)arg1 complectionBlock:(CDUnknownBlockType)arg2;
+ (void)asyncSaveObject:(id)arg1 complectionBlock:(CDUnknownBlockType)arg2;
+ (void)syncUpdateObjects:(id)arg1 account:(id)arg2;
+ (void)syncUpdateObject:(id)arg1 account:(id)arg2;
+ (void)syncUpdateObjects:(id)arg1;
+ (void)syncUpdateObject:(id)arg1;
+ (void)syncSaveObjects:(id)arg1 account:(id)arg2;
+ (void)syncSaveObject:(id)arg1 account:(id)arg2;
+ (void)syncSaveObjects:(id)arg1;
+ (void)syncSaveObject:(id)arg1;
- (void)objectWillSave;
@end

