//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BLBizLogger : NSObject
{
}

+ (void)logEvent:(id)arg1 level:(unsigned long long)arg2 desc:(id)arg3 context:(id)arg4 account:(id)arg5;
+ (void)logEvent:(id)arg1 level:(unsigned long long)arg2 desc:(id)arg3 account:(id)arg4;
+ (void)logEvent:(id)arg1 level:(unsigned long long)arg2;

@end

