//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLCalendarInstance.h"

@interface BLCalendarInstance (Store)
+ (id)findFirstWithNotificationId:(id)arg1 account:(id)arg2;
+ (id)findWithEventUUID:(id)arg1 startTime:(unsigned long long)arg2 account:(id)arg3;
+ (id)findWithCalendarUUID:(id)arg1 account:(id)arg2;
+ (id)findWithEventUUID:(id)arg1 account:(id)arg2;
@end

