//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLFolder.h"

@interface BLFolder (DT)
+ (id)dt_trashFmailFolderUUID:(id)arg1;
+ (id)dt_trashMailFolder:(id)arg1;
- (_Bool)dt_shouldDisplayRecepients;
- (_Bool)dt_allowMutliEdit;
- (_Bool)dt_shouldThreading;
- (_Bool)dt_allowOperation;
@end

