//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLYapObjectWithAccount.h"

@interface BLItemToUpdate : BLYapObjectWithAccount
{
    long long _action;
    long long _createTime;
}

@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long action; // @synthesize action=_action;

@end

