//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BLCalendar, BLMail, BLMailComposeDTO, NSArray, NSData, NSDictionary, NSString;

@protocol BLMailComposeInteractorInput <NSObject>
- (void)cleanup;
- (void)cancelContactsSearch;
- (void)searchContactWithString:(NSString *)arg1 forRecipientType:(long long)arg2;
- (void)setMailAutoQuote:(_Bool)arg1;
- (void)setAttachmentImageQuanlity:(long long)arg1;
- (void)saveMailWithData:(BLMailComposeDTO *)arg1 isDirectly:(_Bool)arg2;
- (void)sendMailWithData:(BLMailComposeDTO *)arg1 isDirectly:(_Bool)arg2;
- (void)mail:(BLMail *)arg1 saveDraftWithData:(BLMailComposeDTO *)arg2;
- (void)removeNoninlineAttachment:(unsigned long long)arg1;
- (void)addAttachmentsByAssets:(NSArray *)arg1;
- (void)addImageAttachment:(NSData *)arg1;
- (void)addInlineImageAttachments:(NSArray *)arg1 andUrls:(NSArray *)arg2;
- (void)deleteCurrentMail;
- (void)checkAttachmentResource;
- (void)buildMailWithQuotedCalendar:(BLCalendar *)arg1;
- (void)buildMailWithRecipients:(NSArray *)arg1 quotedMail:(BLMail *)arg2 draftMail:(BLMail *)arg3 subject:(NSString *)arg4 body:(NSString *)arg5 extension:(NSDictionary *)arg6 andType:(long long)arg7;
- (void)loadQuoteMailWithMailId:(NSString *)arg1 withComplete:(void (^)(BLMail *))arg2;
@end

