//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BLAttachmentAction-Protocol.h"
#import "BLMailDetailInteractorOutput-Protocol.h"
#import "BLMeetingEventResponseAction-Protocol.h"
#import "BLPhotoBrowserDataSource-Protocol.h"

@class BLAccount, BLMail, BLMailDetailStoryboard, NSMutableArray, NSString, NSTimer;
@protocol BLMailChatHelper, BLMailDetailInteractorInput, BLMailDetailInterface, BLMailDetailPresenterDelegate, BLMailDetailViewData, BLMailOperation, BLMailStoryboardRoutable;

@interface BLMailDetailPresenter : NSObject <BLPhotoBrowserDataSource, BLMailDetailInteractorOutput, BLAttachmentAction, BLMeetingEventResponseAction>
{
    _Bool _directViewAttachment;
    _Bool _notFirst;
    id <BLMailDetailInterface> _userInterface;
    id <BLMailDetailViewData> _viewData;
    id <BLMailDetailInteractorInput> _mailDetailInteractor;
    id <BLMailOperation> _mailOp;
    id <BLMailDetailPresenterDelegate> _delgate;
    BLMailDetailStoryboard *_storyboard;
    id <BLMailStoryboardRoutable> _routableStoryboard;
    BLAccount *_currentAccount;
    id <BLMailChatHelper> _mailChatHelper;
    BLMail *_mail;
    NSMutableArray *_attachmentsList;
    long long _handlingAttachmentIndex;
    long long _holdNewEventResponseStatus;
    NSTimer *_timer;
    NSMutableArray *_photoDataSource;
    unsigned long long _currentPhotoItemIndex;
}

@property(nonatomic) _Bool notFirst; // @synthesize notFirst=_notFirst;
@property(nonatomic) unsigned long long currentPhotoItemIndex; // @synthesize currentPhotoItemIndex=_currentPhotoItemIndex;
@property(retain, nonatomic) NSMutableArray *photoDataSource; // @synthesize photoDataSource=_photoDataSource;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long holdNewEventResponseStatus; // @synthesize holdNewEventResponseStatus=_holdNewEventResponseStatus;
@property(nonatomic) long long handlingAttachmentIndex; // @synthesize handlingAttachmentIndex=_handlingAttachmentIndex;
@property(retain, nonatomic) NSMutableArray *attachmentsList; // @synthesize attachmentsList=_attachmentsList;
@property(retain, nonatomic) BLMail *mail; // @synthesize mail=_mail;
@property(nonatomic) _Bool directViewAttachment; // @synthesize directViewAttachment=_directViewAttachment;
@property(nonatomic) __weak id <BLMailChatHelper> mailChatHelper; // @synthesize mailChatHelper=_mailChatHelper;
@property(retain, nonatomic) BLAccount *currentAccount; // @synthesize currentAccount=_currentAccount;
@property(nonatomic) __weak id <BLMailStoryboardRoutable> routableStoryboard; // @synthesize routableStoryboard=_routableStoryboard;
@property(nonatomic) __weak BLMailDetailStoryboard *storyboard; // @synthesize storyboard=_storyboard;
@property(nonatomic) id <BLMailDetailPresenterDelegate> delgate; // @synthesize delgate=_delgate;
@property(retain, nonatomic) id <BLMailOperation> mailOp; // @synthesize mailOp=_mailOp;
@property(retain, nonatomic) id <BLMailDetailInteractorInput> mailDetailInteractor; // @synthesize mailDetailInteractor=_mailDetailInteractor;
@property(retain, nonatomic) id <BLMailDetailViewData> viewData; // @synthesize viewData=_viewData;
@property(nonatomic) __weak id <BLMailDetailInterface> userInterface; // @synthesize userInterface=_userInterface;
- (void).cxx_destruct;
- (_Bool)needShowInlineImagesTapDiv;
- (void)dealInlineImageCacheFromInterceptor:(id)arg1;
- (id)wrapHtmlNew:(id)arg1;
- (id)wrapHtml:(id)arg1;
- (void)showMailBody:(id)arg1;
- (void)updateAllRecipientsFieldForMail:(id)arg1;
- (void)loadBccTokenFieldForMail:(id)arg1;
- (void)loadCcTokenFieldForMail:(id)arg1;
- (void)loadToTokenFieldForMail:(id)arg1;
- (id)convertToPhotoItemFromAttachment:(id)arg1 mail:(id)arg2;
- (id)photoAtIndex:(unsigned long long)arg1;
- (id)photoes;
- (unsigned long long)currentPhotoIndex;
- (unsigned long long)photoCounts;
- (void)previewAttachment:(id)arg1;
- (void)showNetworkErrorAlert;
- (void)showDownloadOptions;
- (void)setNeedManualShowInlineAttachments;
- (void)didDownloadAttachment:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)didDownloadAttachmentFailed:(id)arg1;
- (void)updateAttachmentDownloadProgress:(unsigned long long)arg1 status:(long long)arg2 atIndex:(unsigned long long)arg3;
- (void)updateInlineAttachmentsDownloadProgress:(unsigned long long)arg1 total:(unsigned long long)arg2;
- (void)showEventOrganizer;
- (void)askForUpdatingResponse;
- (void)didLoadCalendarEventStartTime:(long long)arg1 endTime:(long long)arg2 alarm:(long long)arg3 andiaAllDay:(_Bool)arg4;
- (id)alarmTipForAlarm:(long long)arg1;
- (void)setAllowViewAttendeeStatus:(_Bool)arg1;
- (void)didloadCalendarOrganizer:(id)arg1;
- (void)didLoadCalendarEventLocation:(id)arg1;
- (void)didLoadCalendarAttendeeStatus:(long long)arg1;
- (void)setAllowResponse:(_Bool)arg1 andDisallowReason:(id)arg2;
- (void)noCalendarEventFound;
- (void)loadedInlineAttachment:(id)arg1 withCIDURL:(id)arg2;
- (void)foundShouldShowAttachments:(id)arg1;
- (void)updateMailBody:(id)arg1 loadProgress:(unsigned long long)arg2 total:(unsigned long long)arg3;
- (void)didLoadMailBodyFail:(id)arg1 error:(id)arg2;
- (void)didLoadMailBody:(id)arg1;
- (void)didLoadMail:(id)arg1 withShowCCAndBcc:(_Bool)arg2 loadFromServerIfNeed:(_Bool)arg3;
- (void)showAttendeeStatus;
- (void)confirmResponseEvent;
- (void)showOrganizer;
- (void)reponseEventWithAction:(long long)arg1;
- (void)wantsPreviewAttachmentAtIndex:(unsigned long long)arg1;
- (void)deleteMail;
- (void)openLink:(id)arg1;
- (void)openMailComposeWithRecipient:(id)arg1;
- (void)cancelDownloadAttachment;
- (void)stopDownloadAttachment;
- (void)startDownloadAttachment;
- (void)loadInlineAttachments:(_Bool)arg1;
- (void)loadInlineAttachment:(id)arg1;
- (void)willBecomeActive:(id)arg1;
- (void)cleanup;
- (void)onWaitLoadBodyFinished:(id)arg1;
- (void)loadMailDetail:(id)arg1;
- (void)showMail:(id)arg1 ccAndBcc:(_Bool)arg2 loadFromServerIfNeed:(_Bool)arg3;
- (void)showMailWithMailId:(id)arg1 inFolder:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

