//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLMailDetailPresenter.h"

@interface BLMailDetailPresenter (BLUtil)
+ (id)joinedCalendarAttendeeNameList:(id)arg1 senderEmail:(id)arg2;
+ (id)joinedAttendeeNameList:(id)arg1 senderEmail:(id)arg2;
+ (id)generatTokenDataWithRecipients:(id)arg1;
@end

