//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLYapObjectWithAccount.h"

@class NSString;

@interface BLMailReceiver : BLYapObjectWithAccount
{
    NSString *_mailID;
    NSString *_email;
    NSString *_alias;
    unsigned long long _receiverType;
    unsigned long long _deliverStatus;
    unsigned long long _receiverPos;
    long long _timestamp;
}

@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned long long receiverPos; // @synthesize receiverPos=_receiverPos;
@property(nonatomic) unsigned long long deliverStatus; // @synthesize deliverStatus=_deliverStatus;
@property(nonatomic) unsigned long long receiverType; // @synthesize receiverType=_receiverType;
@property(retain, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *mailID; // @synthesize mailID=_mailID;
- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1;

@end

