//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BLMailHeaderView, NSDictionary;

@protocol BLMailHeaderViewDelegate <NSObject>

@optional
- (void)mailHeaderView:(BLMailHeaderView *)arg1 didClickReceiver:(NSDictionary *)arg2;
- (void)mailHeaderViewDidClickSender:(BLMailHeaderView *)arg1;
@end

