//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BLAttachmentAction-Protocol.h"
#import "BLContactsSelectionReceiver-Protocol.h"
#import "BLMailComposeInteractorOutput-Protocol.h"
#import "BLMailDetailPresenterDelegate-Protocol.h"

@class BLCalendar, BLMail, BLMailComposeStoryboard, BLMailDetailPresenter, NSArray, NSDictionary, NSString, NSTimer;
@protocol BLMailComposeInteractorInput, BLMailComposeInterface, BLMailComposeViewData;

@interface BLMailComposePresenter : NSObject <BLMailComposeInteractorOutput, BLAttachmentAction, BLContactsSelectionReceiver, BLMailDetailPresenterDelegate>
{
    struct {
        unsigned int isMailInitialzed:1;
        unsigned int isShowCcAndBccArea:1;
        unsigned int isLoadingMail:1;
        unsigned int isAttachmentChanged:1;
        unsigned int isMailChanged:1;
        unsigned int shouldEndTextFieldEditing:1;
        unsigned int isQuitting:1;
        unsigned int isSelectQualityForSend:1;
        unsigned int shouldWebViewBecomeFirstResponder:1;
        unsigned int isEditingToken:1;
    } _flags;
    unsigned long long _clickAttachmentIndex;
    long long _willAddTokenField;
    NSTimer *_timerForSavingDraft;
    NSString *_currentSearchKeyword;
    id <BLMailComposeInteractorInput> _mailComposeInteractor;
    BLMailComposeStoryboard *_mailComposeStoryboard;
    id <BLMailComposeInterface> _userInterface;
    id <BLMailComposeViewData> _viewData;
    BLMailDetailPresenter *_detailPresenter;
    BLMail *_lastDraftMail;
    long long _actionType;
    BLMail *_quotedMail;
    BLCalendar *_quotedCalendar;
    NSString *_quotedMailId;
    NSArray *_toRecipients;
    NSString *_initialSubject;
    NSString *_initialBody;
    NSArray *_initialDenties;
    NSDictionary *_mailExtension;
    NSArray *_pastedAttchemtAndUrls;
    BLMail *_composingMail;
    long long _toRecipientCount;
}

@property(nonatomic) long long toRecipientCount; // @synthesize toRecipientCount=_toRecipientCount;
@property(retain, nonatomic) BLMail *composingMail; // @synthesize composingMail=_composingMail;
@property(retain, nonatomic) NSArray *pastedAttchemtAndUrls; // @synthesize pastedAttchemtAndUrls=_pastedAttchemtAndUrls;
@property(retain, nonatomic) NSDictionary *mailExtension; // @synthesize mailExtension=_mailExtension;
@property(retain, nonatomic) NSArray *initialDenties; // @synthesize initialDenties=_initialDenties;
@property(retain, nonatomic) NSString *initialBody; // @synthesize initialBody=_initialBody;
@property(retain, nonatomic) NSString *initialSubject; // @synthesize initialSubject=_initialSubject;
@property(retain, nonatomic) NSArray *toRecipients; // @synthesize toRecipients=_toRecipients;
@property(retain, nonatomic) NSString *quotedMailId; // @synthesize quotedMailId=_quotedMailId;
@property(retain, nonatomic) BLCalendar *quotedCalendar; // @synthesize quotedCalendar=_quotedCalendar;
@property(nonatomic) BLMail *quotedMail; // @synthesize quotedMail=_quotedMail;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) BLMail *lastDraftMail; // @synthesize lastDraftMail=_lastDraftMail;
@property(retain, nonatomic) BLMailDetailPresenter *detailPresenter; // @synthesize detailPresenter=_detailPresenter;
@property(nonatomic) __weak id <BLMailComposeViewData> viewData; // @synthesize viewData=_viewData;
@property(nonatomic) __weak id <BLMailComposeInterface> userInterface; // @synthesize userInterface=_userInterface;
@property(nonatomic) __weak BLMailComposeStoryboard *mailComposeStoryboard; // @synthesize mailComposeStoryboard=_mailComposeStoryboard;
@property(retain, nonatomic) id <BLMailComposeInteractorInput> mailComposeInteractor; // @synthesize mailComposeInteractor=_mailComposeInteractor;
- (void).cxx_destruct;
- (_Bool)isTokensValid:(id)arg1 errorEmail:(id *)arg2;
- (_Bool)isRecepientsValid;
- (_Bool)isAttachmentDownloaded:(_Bool)arg1;
- (_Bool)isAttachmentFileValid;
- (_Bool)isMailAttenderEdited:(id)arg1;
- (_Bool)isMailChangedSinceLastEdit:(id)arg1;
- (void)handleEnterBackgound;
- (void)handleEnterForegound;
- (id)wrapHtml:(id)arg1 withReferBody:(id)arg2;
- (void)checkSendEnableWithInput:(id)arg1 andType:(long long)arg2;
- (void)checkSendEnable;
- (_Bool)hasAnyRecipient;
- (_Bool)isEdited;
- (void)autoSaveMail:(id)arg1;
- (void)autoSaveDraftToLocal;
- (_Bool)isCCAndBccExtended;
- (void)didFinishContactSearchWithResult:(id)arg1 forSearchString:(id)arg2 andRecipientType:(long long)arg3;
- (void)didSaveMailDraftSuccess;
- (void)didSendMailSuccess;
- (void)shouldShowImageQualitySelection;
- (void)didSendMailFail:(id)arg1;
- (void)didStartSendingMail;
- (void)willStartSendingMail;
- (void)didChangeImageAttachmentQuality;
- (void)didRemoveAttachmentAtIndex:(unsigned long long)arg1;
- (void)didAddImageAttachmentToMail:(id)arg1;
- (void)didAddInlineImages:(id)arg1;
- (void)didLoadMailBodyFail:(id)arg1;
- (void)didStartLoadMailBody;
- (void)didLoadMailBody:(id)arg1 andReferBody:(id)arg2;
- (void)didShowComposingMail:(id)arg1 withActionType:(long long)arg2;
- (void)didSelectedContacts:(id)arg1;
- (void)wantsPreviewAttachmentAtIndex:(unsigned long long)arg1;
- (void)wantsDeleteAttachmentAtIndex:(unsigned long long)arg1;
- (void)setAutoQuote:(_Bool)arg1;
- (void)selectImageQuality:(long long)arg1;
- (void)addAttachmentsWithAttachmentType:(unsigned long long)arg1;
- (void)saveDraft;
- (void)discardDraftUpdate;
- (void)discardDraft;
- (void)willDiscardDraft;
- (void)resignAllKeyboardInput;
- (void)selectContactsForRecipientType:(long long)arg1;
- (id)searchResultSubTitleForRecipientTokenObject:(id)arg1;
- (id)searchResultTitleForRecipientTokenObject:(id)arg1;
- (id)displayTextForRecipientTokenObject:(id)arg1;
- (void)recipientFieldFrameChanged;
- (void)toggleShowCcAndBccField;
- (void)recipientFieldChanged:(id)arg1 originText:(id)arg2 forType:(long long)arg3;
- (void)willBeginImportContactsForRecipientField:(long long)arg1;
- (_Bool)shouldReturnForRecipientField:(long long)arg1;
- (_Bool)shouldReturnForSubjectField;
- (_Bool)willEndEditingSubject;
- (_Bool)willEndEditingRecipientField:(long long)arg1;
- (void)didBeginEditingRecipientField:(long long)arg1;
- (void)willBeginEditingRecipientField:(long long)arg1;
- (void)didBeginEditingSubject;
- (void)willBeginEditingSubject;
- (void)updateCCBCCField;
- (void)searchContactWithSearchString:(id)arg1 atRecipientField:(long long)arg2;
- (void)didRemoveToken:(id)arg1 atRecipientField:(long long)arg2;
- (void)didAddToken:(id)arg1 withTitle:(id)arg2 atRecipientField:(long long)arg3;
- (_Bool)willAddToken:(id)arg1 withTitle:(id)arg2 atRecipientField:(long long)arg3 newToken:(id *)arg4;
- (_Bool)isEditingContentEdit;
- (void)onBeginContentEdit;
- (void)loadInlineAttachments:(_Bool)arg1;
- (void)cancel;
- (void)addAttachmentsFromCloudDentry:(id)arg1;
- (void)addAttachmentsFromPhotoLibrary:(id)arg1;
- (void)addImageAttachment:(id)arg1;
- (void)pasteImagesIntoMail:(id)arg1;
- (void)sendMailInternal;
- (void)sendMail;
- (void)cleanupView;
- (void)checkContentIsEmpty;
- (void)willBecomeActive;
- (void)updateInitView;
- (void)setInitialMailExtension:(id)arg1;
- (void)setInitialDentries:(id)arg1;
- (void)setInitialSubject:(id)arg1 andBody:(id)arg2;
- (void)setQuoteMailId:(id)arg1;
- (void)setQuoteCalendar:(id)arg1;
- (void)setQuoteMail:(id)arg1;
- (void)setInitialRecipients:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

