//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BLPhotoItem, BLSpaceEntry, NSArray, NSDictionary, NSString;
@protocol BLCancelable;

@protocol BLPhotoBrowserDataSource <NSObject>
- (BLPhotoItem *)photoAtIndex:(unsigned long long)arg1;
- (NSArray *)photoes;
- (unsigned long long)currentPhotoIndex;
- (unsigned long long)photoCounts;

@optional
- (void)didDisplayPhotoAtIndex:(unsigned long long)arg1;
- (void)cancelDownloadPhotoWithKey:(NSString *)arg1;
- (id <BLCancelable>)downloadPhotoAtIndex:(unsigned long long)arg1 progress:(void (^)(double))arg2 completion:(void (^)(UIImage *))arg3;
- (NSDictionary *)photoRequestHeader;
- (BLSpaceEntry *)sourceSpace;
- (unsigned long long)sourceOperationType;
@end

