//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLSpaceEntry.h"

@class DTDpOrgConversationModel, DTOrganization, NSString;

@interface BLSpaceEntry (dingtalk)
@property(nonatomic) _Bool needToCheck;
@property(nonatomic) _Bool isWatarMark;
@property(nonatomic) _Bool isDocReadOnly;
@property(copy, nonatomic) NSString *groupName;
@property(retain, nonatomic) DTOrganization *organization;
@property(retain, nonatomic) DTDpOrgConversationModel *model;
@property(nonatomic) long long orgId;
@property(copy, nonatomic) NSString *cid;
@end

