//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseAPITask.h"

@interface BLSyncFolderAPITask : BLBaseAPITask
{
}

- (void)deleteFolderFromAPIFolder:(id)arg1 forAccount:(id)arg2;
- (id)createOrUpdateFolderFromAPIFolder:(id)arg1 forAccount:(id)arg2;
- (void)handleSuccessResponse:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)process;

@end

