//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@interface DTAccountSafeViewController : DTTableViewController
{
}

- (id)unbindAccountCloudSetting;
- (void)viewWillLayoutSubviews;
- (void)unbindItemClick;
- (void)changeHideBossChat:(_Bool)arg1 sender:(id)arg2;
- (void)safePasscodeItemClick;
- (void)passwordItemClick;
- (void)phonenumberItemClick;
- (void)accountItemClick;
- (void)loadDataSource;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

