//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTUIThemeDelegate-Protocol.h"

@class NSArray, NSString;

@interface DTAppLaunchCenter : NSObject <DTUIThemeDelegate>
{
    NSArray *_observers;
}

+ (id)sharedCenter;
@property(copy, nonatomic) NSArray *observers; // @synthesize observers=_observers;
- (void).cxx_destruct;
- (void)applicationWillLogout;
- (void)applicationDidEnterMainPage;
- (void)applicationLoginFailure;
- (void)applicationLoginSuccess;
- (void)applicationAuthFailure;
- (void)applicationAuthSuccess;
- (void)applicationWillAuth;
- (void)applicationWillLogin;
- (void)applicationWillStart;
- (void)removeAllObserver;
- (void)removeObserver:(id)arg1;
- (void)registerObserver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

