//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, UIImageView;
@protocol DTAvatarViewControlDelegate, DTAvatarViewDelegate;

@interface DTAvatarView : UIView
{
    _Bool _scalable;
    _Bool _hasAddGestureRecognizer;
    id <DTAvatarViewDelegate> _showDelegate;
    id <DTAvatarViewControlDelegate> _controlDelegate;
    NSArray *_avatarModels;
    unsigned long long _avatarMaxCount;
    long long _avatarSize;
    NSString *_avatarSizeKey;
    NSArray *_avatarImageViews;
    UIImageView *_backgroundImageView;
}

@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) _Bool hasAddGestureRecognizer; // @synthesize hasAddGestureRecognizer=_hasAddGestureRecognizer;
@property(copy, nonatomic) NSArray *avatarImageViews; // @synthesize avatarImageViews=_avatarImageViews;
@property(copy, nonatomic) NSString *avatarSizeKey; // @synthesize avatarSizeKey=_avatarSizeKey;
@property(nonatomic) long long avatarSize; // @synthesize avatarSize=_avatarSize;
@property(nonatomic) unsigned long long avatarMaxCount; // @synthesize avatarMaxCount=_avatarMaxCount;
@property(copy, nonatomic) NSArray *avatarModels; // @synthesize avatarModels=_avatarModels;
@property(nonatomic) __weak id <DTAvatarViewControlDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
@property(nonatomic) __weak id <DTAvatarViewDelegate> showDelegate; // @synthesize showDelegate=_showDelegate;
@property(nonatomic) _Bool scalable; // @synthesize scalable=_scalable;
- (void).cxx_destruct;
- (void)resetAvatarImageViews;
- (void)layoutSubviews;
- (void)refreshAvatar;
- (void)longPressEvent:(id)arg1;
- (void)clickEvent:(id)arg1;
- (void)addGestureRecognizer;
- (id)avatarViewImage;
- (void)setBackgroundImage:(id)arg1;
- (void)setFixedImage:(id)arg1;
- (void)setAvatarSize;
- (void)addAllSubViews;

@end

