//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTWebImageView.h"

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface DTAvatarCellImageView : DTWebImageView
{
    _Bool _isNotificationEnable;
    _Bool _observing;
    long long _uid;
    NSString *_userName;
    NSString *_avatarSize;
    NSObject<OS_dispatch_queue> *_imageCutQueue;
    NSString *_imageMark;
    long long _imageShapeType;
}

@property(nonatomic) long long imageShapeType; // @synthesize imageShapeType=_imageShapeType;
@property(copy, nonatomic) NSString *imageMark; // @synthesize imageMark=_imageMark;
@property(nonatomic) _Bool observing; // @synthesize observing=_observing;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *imageCutQueue; // @synthesize imageCutQueue=_imageCutQueue;
@property(copy, nonatomic) NSString *avatarSize; // @synthesize avatarSize=_avatarSize;
@property(nonatomic) _Bool isNotificationEnable; // @synthesize isNotificationEnable=_isNotificationEnable;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (id)getDefaultAvatarImageWithDTSize:(id)arg1;
- (id)getDefaultAvatarImageWithDTSize:(id)arg1 shapeType:(long long)arg2;
- (void)showImageWithURl:(id)arg1 dtSize:(id)arg2 userName:(id)arg3 mediaID:(id)arg4 uid:(long long)arg5 contact:(id)arg6;
- (void)postLoadCompletedNotificationWithImage:(id)arg1 sizeKey:(id)arg2 uid:(long long)arg3 notificationName:(id)arg4;
- (void)showImageWithURl:(id)arg1 dtSize:(id)arg2 userName:(id)arg3 mediaID:(id)arg4 uid:(long long)arg5 contact:(id)arg6 shapeType:(long long)arg7;
- (void)setImageWithURl:(id)arg1 dtSize:(id)arg2 userName:(id)arg3 mediaID:(id)arg4 uid:(long long)arg5;
- (void)setImageWithURl:(id)arg1 dtSize:(id)arg2 userName:(id)arg3 mediaID:(id)arg4 uid:(long long)arg5 shapeType:(long long)arg6;
- (void)clearAvatarInfo;
- (void)resetImageWithContact:(id)arg1;
- (void)resetImageWithContact:(id)arg1 shapeType:(long long)arg2;
- (void)resetImageWithDBNotification:(id)arg1;
- (void)dealloc;
- (id)initCellImageViewUid:(long long)arg1 withNotificationEnable:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

