//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTBizCallCreateModel : Marshal
{
    NSNumber *_calleeUid;
    NSString *_bizCallNum;
    NSNumber *_orgId;
}

@property(retain, nonatomic) NSNumber *orgId; // @synthesize orgId=_orgId;
@property(copy, nonatomic) NSString *bizCallNum; // @synthesize bizCallNum=_bizCallNum;
@property(retain, nonatomic) NSNumber *calleeUid; // @synthesize calleeUid=_calleeUid;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

