//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface DTBizDingLinkModel : NSObject
{
    long long _type;
    NSString *_title;
    NSString *_text;
    NSString *_picMediaId;
    NSString *_linkUrl;
    NSDictionary *_extension;
}

+ (id)convertToLinkModel:(id)arg1;
+ (id)convertFromLinkModel:(id)arg1;
@property(copy, nonatomic) NSDictionary *extension; // @synthesize extension=_extension;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSString *picMediaId; // @synthesize picMediaId=_picMediaId;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)getCModel;
- (id)initWithCModel:(id)arg1 type:(long long)arg2;

@end

