//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OpenModel.h"

@class NSArray, NSString;

@interface DTBizCSpaceCoFolderModel : OpenModel
{
    _Bool _createConversation;
    long long _orgId;
    NSString *_name;
    NSArray *_members;
}

@property(nonatomic) _Bool createConversation; // @synthesize createConversation=_createConversation;
@property(copy, nonatomic) NSArray *members; // @synthesize members=_members;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
- (void).cxx_destruct;

@end

