//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBizDingAttachment.h"

@class NSArray, NSData, NSString;

@interface DTBizDingAttachmentAudio : DTBizDingAttachment
{
    NSString *_audioUrl;
    NSString *_mediaId;
    NSData *_data;
    NSString *_duration;
    NSArray *_volumns;
}

@property(copy, nonatomic) NSArray *volumns; // @synthesize volumns=_volumns;
@property(copy, nonatomic) NSString *duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSData *data; // @synthesize data=_data;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *audioUrl; // @synthesize audioUrl=_audioUrl;
- (id)init;

@end

