//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTBizDingFrameModel : NSObject
{
    long long _dingHeight;
    struct CGRect _avatarFrame;
    struct CGRect _nameFrame;
    struct CGRect _timeFrame;
    struct CGRect _textFrame;
    struct CGRect _audioFrame;
    struct CGRect _attachmentFrame;
    struct CGRect _deadlineFrame;
}

@property(nonatomic) long long dingHeight; // @synthesize dingHeight=_dingHeight;
@property(nonatomic) struct CGRect deadlineFrame; // @synthesize deadlineFrame=_deadlineFrame;
@property(nonatomic) struct CGRect attachmentFrame; // @synthesize attachmentFrame=_attachmentFrame;
@property(nonatomic) struct CGRect audioFrame; // @synthesize audioFrame=_audioFrame;
@property(nonatomic) struct CGRect textFrame; // @synthesize textFrame=_textFrame;
@property(nonatomic) struct CGRect timeFrame; // @synthesize timeFrame=_timeFrame;
@property(nonatomic) struct CGRect nameFrame; // @synthesize nameFrame=_nameFrame;
@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;

@end

