//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBizDingModel.h"

@class NSString;

@interface DTBizDingModel (Assist)
- (id)otoConversationId;
- (_Bool)showDingConferenceSource;
- (_Bool)isDeadlineDingWillExpireBeforeTomorrow;
- (_Bool)isDeadlineExpire;
- (_Bool)commentIsRead;
- (void)setCommentReadIfNeed;
- (_Bool)isGuideDing;
- (_Bool)isSelfDing;
- (_Bool)isReceiverDing;
- (_Bool)isSentDing;
@property(nonatomic) _Bool noNeedLoadDingSource;
@property(copy, nonatomic) NSString *dingSource;
@end

