//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTBizDingLinkModel, NSDictionary, NSNumber, NSString;

@interface DTBizDingAttachmentExtra : NSObject
{
    NSNumber *_type;
    NSString *_mediaId;
    NSNumber *_duration;
    NSNumber *_size;
    NSString *_fileName;
    NSString *_detailType;
    NSString *_fileSpaceId;
    NSDictionary *_extension;
    DTBizDingLinkModel *_linkModel;
}

+ (id)convertToDingAttachmentModel:(id)arg1;
+ (id)convertToBizAttachmentExtra:(id)arg1;
+ (_Bool)isSupportType:(long long)arg1;
@property(retain, nonatomic) DTBizDingLinkModel *linkModel; // @synthesize linkModel=_linkModel;
@property(copy, nonatomic) NSDictionary *extension; // @synthesize extension=_extension;
@property(copy, nonatomic) NSString *fileSpaceId; // @synthesize fileSpaceId=_fileSpaceId;
@property(copy, nonatomic) NSString *detailType; // @synthesize detailType=_detailType;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSNumber *size; // @synthesize size=_size;
@property(retain, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isRE;
- (_Bool)isOriginalImage;

@end

