//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, CALayer, NSString, UIButton, UIImageView, UILabel;

@interface DTBusinessConfWelfareView : UIView
{
    _Bool _currentShow;
    unsigned long long _currentStatus;
    NSString *_sessionId;
    CDUnknownBlockType _closeBlock;
    CDUnknownBlockType _seeDetailBlock;
    UIView *_superView;
    UIView *_maskView;
    CAGradientLayer *_gradientLayer;
    CALayer *_backgroundImageLayer;
    UIButton *_closeBtn;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
    UIImageView *_contentImageView;
    UIButton *_getWealfareBtn;
    UIButton *_detailButton;
    unsigned long long _wealfareCnt;
}

@property(nonatomic) unsigned long long wealfareCnt; // @synthesize wealfareCnt=_wealfareCnt;
@property(retain, nonatomic) UIButton *detailButton; // @synthesize detailButton=_detailButton;
@property(retain, nonatomic) UIButton *getWealfareBtn; // @synthesize getWealfareBtn=_getWealfareBtn;
@property(retain, nonatomic) UIImageView *contentImageView; // @synthesize contentImageView=_contentImageView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) CALayer *backgroundImageLayer; // @synthesize backgroundImageLayer=_backgroundImageLayer;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIView *superView; // @synthesize superView=_superView;
@property(copy, nonatomic) CDUnknownBlockType seeDetailBlock; // @synthesize seeDetailBlock=_seeDetailBlock;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) _Bool currentShow; // @synthesize currentShow=_currentShow;
@property(nonatomic) unsigned long long currentStatus; // @synthesize currentStatus=_currentStatus;
- (void).cxx_destruct;
- (void)dismiss;
- (void)showWithSuperView:(id)arg1;
- (void)detail:(id)arg1;
- (void)getWealfare:(id)arg1;
- (void)closeView:(id)arg1;
- (void)layoutSubviews;
- (void)layoutSubviewsWithStatus:(unsigned long long)arg1;
- (void)loadCompoment;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

