//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, DTAvatarImageView, DTConferenceMember, UIImageView, UILabel, UITapGestureRecognizer;
@protocol BusinessConfMeberDelegate;

@interface DTBusinessConfMemberView : UIView
{
    id <BusinessConfMeberDelegate> _delegate;
    DTAvatarImageView *_avatarImageView;
    UIImageView *_statusImageView;
    UILabel *_statusLabel;
    CAShapeLayer *_cicleLayer;
    CAShapeLayer *_speakLayer;
    CAShapeLayer *_muteLayer;
    UITapGestureRecognizer *_tapGesture;
    UITapGestureRecognizer *_specialTapGesture;
    DTConferenceMember *_member;
}

@property(copy, nonatomic) DTConferenceMember *member; // @synthesize member=_member;
@property(retain, nonatomic) UITapGestureRecognizer *specialTapGesture; // @synthesize specialTapGesture=_specialTapGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) CAShapeLayer *muteLayer; // @synthesize muteLayer=_muteLayer;
@property(retain, nonatomic) CAShapeLayer *speakLayer; // @synthesize speakLayer=_speakLayer;
@property(retain, nonatomic) CAShapeLayer *cicleLayer; // @synthesize cicleLayer=_cicleLayer;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *statusImageView; // @synthesize statusImageView=_statusImageView;
@property(retain, nonatomic) DTAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak id <BusinessConfMeberDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)specialTapGesture:(id)arg1;
- (void)tapGesture:(id)arg1;
- (void)layoutUIWithSize:(id)arg1;
- (void)layoutAvatar:(id)arg1 size:(id)arg2;
- (void)refreshSpecialImageName:(id)arg1 dtAvatarSizeKey:(id)arg2;
- (void)refreshMember:(id)arg1 dtAvatarSizeKey:(id)arg2;
- (id)avatarModel:(id)arg1;
- (void)loadCompomentShowBorder:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 showBorder:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resetView;
- (void)dealloc;

@end

