//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTCloudSettingManager : NSObject
{
}

+ (_Bool)isIMVideoEntrnaceEnabled;
+ (id)conversationCleanUpSettings;
+ (void)refreshFunctionSwitchs;
+ (_Bool)_isSpdyEnabled;
+ (_Bool)_isLWPDownEnabled;
+ (_Bool)isLWPDownEnabled;
+ (_Bool)isSpdyEnabled;
+ (id)mediaIdForContactEmpty;
+ (id)randomStringWithBaseString:(id)arg1;
+ (id)getRandomString:(int)arg1;
+ (id)getSecurityCode:(id)arg1 uId:(id)arg2;
+ (_Bool)check:(id)arg1 content:(id)arg2 uId:(id)arg3;
+ (id)getBlackSecurityCode;
+ (void)setAllowAuthOrgsToShow:(_Bool)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (_Bool)allowAuthOrgsToShow;
+ (void)setJustHideBossChat:(_Bool)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (_Bool)hasJustHideBossChat:(_Bool *)arg1;
+ (_Bool)hasJustHideBossChat;
+ (void)setProtectLockscreen:(_Bool)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (_Bool)hasProtectLockscreen:(_Bool *)arg1;
+ (_Bool)hasProtectLockscreen;
+ (void)setHideBossMode:(_Bool)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (_Bool)hasHideBossMode:(_Bool *)arg1;
+ (_Bool)hasHideBossMode;
+ (void)setSafePasscode:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (_Bool)checkSafePasscodeCorrect:(id)arg1;
+ (_Bool)hasSafePasscode;
+ (void)configureSwitchs;
+ (void)onCloudSettingsChanged:(id)arg1;
+ (void)initialize;

@end

