//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LWFetchedResultsControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "WWSlideMenuCellDelegate-Protocol.h"

@class DTEmptyResultView, DTTableView, LWFetchedResultsController, NSMutableArray, NSString, UIActivityIndicatorView;

@interface DTConversationListDataSource : NSObject <WWSlideMenuCellDelegate, UITableViewDataSource, LWFetchedResultsControllerDelegate>
{
    _Bool _rpcLoadFailed;
    _Bool _rpcLoadSucceed;
    _Bool _isLoadingConversation;
    _Bool _addedKVOForContentSize;
    _Bool _isLoadingIndicatorHiding;
    _Bool _showBossConversations;
    LWFetchedResultsController *_fetchController;
    CDUnknownBlockType _emptyViewClickBlock;
    DTTableView *_tableView;
    DTEmptyResultView *_emptyResultView;
    NSMutableArray *_conversationList;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) NSMutableArray *conversationList; // @synthesize conversationList=_conversationList;
@property(retain, nonatomic) DTEmptyResultView *emptyResultView; // @synthesize emptyResultView=_emptyResultView;
@property(nonatomic) _Bool showBossConversations; // @synthesize showBossConversations=_showBossConversations;
@property(nonatomic) __weak DTTableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType emptyViewClickBlock; // @synthesize emptyViewClickBlock=_emptyViewClickBlock;
@property(retain, nonatomic) LWFetchedResultsController *fetchController; // @synthesize fetchController=_fetchController;
- (void).cxx_destruct;
- (double)cellHeightWithIndex:(unsigned long long)arg1;
- (id)conversationAtRow:(unsigned long long)arg1;
- (void)controllerDidRollback:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(long long)arg4 newIndex:(unsigned long long)arg5;
- (void)controllerWillChangeContent:(id)arg1;
- (void)removeConversation:(id)arg1;
- (void)changeTopSorting:(id)arg1 wkConversation:(id)arg2;
- (void)clearConversation:(id)arg1;
- (void)openConversationSettings:(id)arg1;
- (void)menuCell:(id)arg1 atIndexPath:(id)arg2 didClickedMenuIndex:(long long)arg3;
- (id)menuCell:(id)arg1 atIndexPath:(id)arg2 menuItemColorAtIndex:(long long)arg3;
- (id)menuCell:(id)arg1 titlesAtIndexPath:(id)arg2;
- (id)tableViewOfMenuCell:(id)arg1;
- (long long)slidingTypeConversation:(id)arg1;
- (_Bool)isBossConversation:(id)arg1;
- (_Bool)isOpenedCustomTopSorting:(id)arg1;
- (_Bool)conversationSettingsEnabled:(id)arg1;
- (_Bool)menuCell:(id)arg1 enableAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)checkEmptyPage;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeKVOForContentSize;
- (void)addKVOForContentSize;
- (void)dismissBottomLoading;
- (void)showBottomLoading;
- (void)asyncLoadAllLocalConversations;
- (void)restartHook;
- (void)stopHook;
- (void)refreshTotalUnreadBadge;
- (void)checkConversations;
- (void)loadAllConversations;
- (id)buildSqlStatement;
- (void)buildFetch;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

