//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactPickIdentifier.h"

@class DTAvatarModel, NSString;

@interface DTContactPickPersonIdentifier : DTContactPickIdentifier
{
    _Bool _isActived;
    NSString *_personIdentifier;
    long long _uid;
    NSString *_mobile;
    NSString *_staffId;
    DTAvatarModel *_avatarModel;
    NSString *_email;
    NSString *_mediaId;
}

+ (id)identifierWithContact:(id)arg1;
+ (id)identifierWithEnterpriseCard:(id)arg1;
@property(nonatomic) _Bool isActived; // @synthesize isActived=_isActived;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) DTAvatarModel *avatarModel; // @synthesize avatarModel=_avatarModel;
@property(copy, nonatomic) NSString *staffId; // @synthesize staffId=_staffId;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *personIdentifier; // @synthesize personIdentifier=_personIdentifier;
- (void).cxx_destruct;
- (_Bool)mobile:(id)arg1 isSameWithAnother:(id)arg2 exact:(_Bool)arg3;
- (_Bool)isEqualToIdentifier:(id)arg1 exactMobile:(_Bool)arg2;
- (_Bool)isEqualToIdentifier:(id)arg1;

@end

