//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactPickHandler.h"

#import "DTContactPickViewControllerDelegate-Protocol.h"
#import "DTLoadMoreDelegate-Protocol.h"

@class DTLoadMoreController, NSArray, NSString;

@interface DTContactPickCRMClientHandler : DTContactPickHandler <DTLoadMoreDelegate, DTContactPickViewControllerDelegate>
{
    _Bool _isLoading;
    _Bool _hasPermission;
    NSString *_corpId;
    NSString *_staffId;
    NSArray *_dataSources;
    DTLoadMoreController *_loadMoreController;
    long long _orgId;
}

@property(nonatomic) _Bool hasPermission; // @synthesize hasPermission=_hasPermission;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(retain, nonatomic) DTLoadMoreController *loadMoreController; // @synthesize loadMoreController=_loadMoreController;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(copy, nonatomic) NSArray *dataSources; // @synthesize dataSources=_dataSources;
@property(copy, nonatomic) NSString *staffId; // @synthesize staffId=_staffId;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
- (void).cxx_destruct;
- (_Bool)needShowAddItem;
- (void)addCustomer;
- (void)finishAdding:(id)arg1;
- (void)addNotification;
- (void)loadMoreControllerWillBeginLoading:(id)arg1;
- (id)handlerForSearchViewController:(id)arg1 searchBar:(id)arg2;
- (id)placeHolderForSearchBar:(id)arg1;
- (_Bool)shouldShowSearchBar:(id)arg1;
- (id)titleForViewController:(id)arg1;
- (id)emptyViewForViewController:(id)arg1;
- (_Bool)shouldShowEmptyView:(id)arg1;
- (id)loadModelControllerForPicker:(id)arg1;
- (void)pickViewWillDestory:(id)arg1;
- (void)updateDataSourceWithClients:(id)arg1 count:(long long)arg2;
- (void)loadClient:(_Bool)arg1;
- (id)dataSourceForPickViewController:(id)arg1;
- (void)pickViewWillShow:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

