//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OpenModel.h"

#import "OpenModelProtocol-Protocol.h"

@class NSString;

@interface DTConferenceADModel : OpenModel <OpenModelProtocol>
{
    _Bool _enable;
    long long _version;
    long long _type;
    NSString *_title;
    NSString *_content;
    NSString *_uri;
    NSString *_mediaId;
    NSString *_bgColor;
    long long _id_;
    NSString *_titleColor;
    NSString *_contentColor;
    NSString *_mediaColor;
    unsigned long long _confADKey;
}

+ (void)upgradeVersion2:(id)arg1;
+ (_Bool)upgradeTableToVersion:(unsigned long long)arg1 MDHandler:(id)arg2;
+ (void)createTableWithMDHandler:(id)arg1;
+ (_Bool)isShardingTable;
+ (id)tableName;
+ (id)primaryKeyName;
+ (_Bool)hasAutoIncrementPrimaryKey;
@property(nonatomic) unsigned long long confADKey; // @synthesize confADKey=_confADKey;
@property(copy, nonatomic) NSString *mediaColor; // @synthesize mediaColor=_mediaColor;
@property(copy, nonatomic) NSString *contentColor; // @synthesize contentColor=_contentColor;
@property(copy, nonatomic) NSString *titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) long long id_; // @synthesize id_=_id_;
@property(copy, nonatomic) NSString *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(copy, nonatomic) NSString *uri; // @synthesize uri=_uri;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

