//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactPickHandler.h"

#import "DTContactPickViewControllerDelegate-Protocol.h"
#import "DTLoadMoreDelegate-Protocol.h"

@class DTLoadMoreController, DTSectionItem, NSArray, NSString;

@interface DTContactPickCRMHandler : DTContactPickHandler <DTLoadMoreDelegate, DTContactPickViewControllerDelegate>
{
    long long _orgId;
    NSString *_starffId;
    DTSectionItem *_sectionItem;
    NSArray *_index;
    DTLoadMoreController *_loadMoreController;
}

@property(retain, nonatomic) DTLoadMoreController *loadMoreController; // @synthesize loadMoreController=_loadMoreController;
@property(copy, nonatomic) NSArray *index; // @synthesize index=_index;
@property(retain, nonatomic) DTSectionItem *sectionItem; // @synthesize sectionItem=_sectionItem;
@property(copy, nonatomic) NSString *starffId; // @synthesize starffId=_starffId;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
- (void).cxx_destruct;
- (id)fullMobileWithMobile:(id)arg1 countryCode:(id)arg2;
- (void)loadMoreControllerWillBeginLoading:(id)arg1;
- (_Bool)shouldShowSearchBar:(id)arg1;
- (void)updateCellItemWithIdentifier:(id)arg1 isSelect:(_Bool)arg2;
- (void)personHasUnselected:(id)arg1;
- (void)personHasSelected:(id)arg1;
- (void)showCrmContacts:(id)arg1;
- (void)loadDataSource;
- (id)dataSourceForPickViewController:(id)arg1;
- (id)titleForViewController:(id)arg1;
- (id)emptyViewForViewController:(id)arg1;
- (_Bool)shouldShowEmptyView:(id)arg1;
- (void)pickViewWillDestory:(id)arg1;
- (void)pickViewWillShow:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

