//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactTableViewCell.h"

@class DTWorkStatusView, UIButton;

@interface DTContactProfileCell : DTContactTableViewCell
{
    UIButton *_telephoneButton;
    UIButton *_saveButton;
    UIButton *_emailButton;
    DTWorkStatusView *_workStatusView;
}

+ (double)calculateCellHeight:(id)arg1 cellWidth:(double)arg2;
@property(retain, nonatomic) DTWorkStatusView *workStatusView; // @synthesize workStatusView=_workStatusView;
@property(retain, nonatomic) UIButton *emailButton; // @synthesize emailButton=_emailButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIButton *telephoneButton; // @synthesize telephoneButton=_telephoneButton;
- (void).cxx_destruct;
- (void)emailButtonPressed:(id)arg1;
- (void)saveButtonPressed:(id)arg1;
- (void)telButtonPressed:(id)arg1;
- (void)configCellWithContactItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCellStyle:(unsigned long long)arg1 reuseIdentifier:(id)arg2;

@end

