//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactBaseViewController.h"

#import "DTContactProfileHeaderViewDelegate-Protocol.h"
#import "DTContactProfileMoreOperationDelegate-Protocol.h"
#import "DTConversationSelectViewControllerDelegate-Protocol.h"
#import "DTMobileContactUIDelegate-Protocol.h"
#import "DTTipsViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTCRMContact, DTContact, DTContactProfile, DTContactProfileHeaderView, DTContactProfileMoreOperationController, DTEnterpriseCard, DTEnterpriseNavigation, DTFriendRequest, DTProfileButton, NSArray, NSIndexPath, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UIImageView, UITableView, UIView;

@interface DTContactProfileViewController : DTContactBaseViewController <UITableViewDelegate, UITableViewDataSource, DTContactProfileHeaderViewDelegate, DTContactProfileMoreOperationDelegate, DTConversationSelectViewControllerDelegate, DTTipsViewDelegate, DTMobileContactUIDelegate>
{
    _Bool _popToRootWhileRemoveFriend;
    _Bool _openInCurrentNavigationController;
    _Bool _showsAccept;
    _Bool _showsSendMsg;
    _Bool _showsDing;
    _Bool _showsConference;
    _Bool _showsAddFriend;
    _Bool _showsHasSent;
    _Bool _showMoreOrg;
    long long _uid;
    NSString *_staffId;
    long long _orgId;
    unsigned long long _source;
    NSString *_friendRequestMessage;
    NSString *_phoneName;
    NSString *_phone;
    NSString *_conversationTitle;
    CDUnknownBlockType _friendRequestStatusChanged;
    CDUnknownBlockType _attentionStatusChanged;
    DTContactProfileHeaderView *_profileHeaderView;
    DTContactProfile *_contactProfile;
    double _profileHeaderViewHeight;
    UITableView *_tableView;
    NSMutableArray *_datasource;
    UIView *_tableHeaderView;
    UIView *_actionBackground;
    DTProfileButton *_secretButton;
    DTProfileButton *_dingButton;
    DTProfileButton *_conferenceButton;
    DTProfileButton *_msgButton;
    UIButton *_addFriendButton;
    UIButton *_acceptButton;
    UIButton *_hasSentButton;
    UIImageView *_tipsView;
    DTContact *_contact;
    NSArray *_enterpriseCards;
    NSArray *_smartworkSummary;
    NSArray *_crmContacts;
    DTCRMContact *_currentCrmContact;
    DTEnterpriseCard *_currentEnterpriseCard;
    DTFriendRequest *_friendRequest;
    unsigned long long _relationship;
    DTEnterpriseNavigation *_crmNavigation;
    UIView *_crmHeaderView;
    DTEnterpriseNavigation *_enterpriseNavigation;
    UIView *_enterpriseHeaderView;
    long long _enterpriseCardsSection;
    UIActivityIndicatorView *_indicatorView;
    DTContactProfileMoreOperationController *_moreOperaController;
    DTEnterpriseCard *_extContact;
    NSIndexPath *_statusIndexPath;
}

@property(retain, nonatomic) NSIndexPath *statusIndexPath; // @synthesize statusIndexPath=_statusIndexPath;
@property(retain, nonatomic) DTEnterpriseCard *extContact; // @synthesize extContact=_extContact;
@property(nonatomic) _Bool showMoreOrg; // @synthesize showMoreOrg=_showMoreOrg;
@property(retain, nonatomic) DTContactProfileMoreOperationController *moreOperaController; // @synthesize moreOperaController=_moreOperaController;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) long long enterpriseCardsSection; // @synthesize enterpriseCardsSection=_enterpriseCardsSection;
@property(retain, nonatomic) UIView *enterpriseHeaderView; // @synthesize enterpriseHeaderView=_enterpriseHeaderView;
@property(retain, nonatomic) DTEnterpriseNavigation *enterpriseNavigation; // @synthesize enterpriseNavigation=_enterpriseNavigation;
@property(retain, nonatomic) UIView *crmHeaderView; // @synthesize crmHeaderView=_crmHeaderView;
@property(retain, nonatomic) DTEnterpriseNavigation *crmNavigation; // @synthesize crmNavigation=_crmNavigation;
@property(nonatomic) unsigned long long relationship; // @synthesize relationship=_relationship;
@property(retain, nonatomic) DTFriendRequest *friendRequest; // @synthesize friendRequest=_friendRequest;
@property(retain, nonatomic) DTEnterpriseCard *currentEnterpriseCard; // @synthesize currentEnterpriseCard=_currentEnterpriseCard;
@property(retain, nonatomic) DTCRMContact *currentCrmContact; // @synthesize currentCrmContact=_currentCrmContact;
@property(retain, nonatomic) NSArray *crmContacts; // @synthesize crmContacts=_crmContacts;
@property(retain, nonatomic) NSArray *smartworkSummary; // @synthesize smartworkSummary=_smartworkSummary;
@property(retain, nonatomic) NSArray *enterpriseCards; // @synthesize enterpriseCards=_enterpriseCards;
@property(retain, nonatomic) DTContact *contact; // @synthesize contact=_contact;
@property(nonatomic) _Bool showsHasSent; // @synthesize showsHasSent=_showsHasSent;
@property(nonatomic) _Bool showsAddFriend; // @synthesize showsAddFriend=_showsAddFriend;
@property(nonatomic) _Bool showsConference; // @synthesize showsConference=_showsConference;
@property(nonatomic) _Bool showsDing; // @synthesize showsDing=_showsDing;
@property(nonatomic) _Bool showsSendMsg; // @synthesize showsSendMsg=_showsSendMsg;
@property(nonatomic) _Bool showsAccept; // @synthesize showsAccept=_showsAccept;
@property(retain, nonatomic) UIImageView *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) UIButton *hasSentButton; // @synthesize hasSentButton=_hasSentButton;
@property(retain, nonatomic) UIButton *acceptButton; // @synthesize acceptButton=_acceptButton;
@property(retain, nonatomic) UIButton *addFriendButton; // @synthesize addFriendButton=_addFriendButton;
@property(retain, nonatomic) DTProfileButton *msgButton; // @synthesize msgButton=_msgButton;
@property(retain, nonatomic) DTProfileButton *conferenceButton; // @synthesize conferenceButton=_conferenceButton;
@property(retain, nonatomic) DTProfileButton *dingButton; // @synthesize dingButton=_dingButton;
@property(retain, nonatomic) DTProfileButton *secretButton; // @synthesize secretButton=_secretButton;
@property(retain, nonatomic) UIView *actionBackground; // @synthesize actionBackground=_actionBackground;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) double profileHeaderViewHeight; // @synthesize profileHeaderViewHeight=_profileHeaderViewHeight;
@property(retain, nonatomic) DTContactProfile *contactProfile; // @synthesize contactProfile=_contactProfile;
@property(retain, nonatomic) DTContactProfileHeaderView *profileHeaderView; // @synthesize profileHeaderView=_profileHeaderView;
@property(copy, nonatomic) CDUnknownBlockType attentionStatusChanged; // @synthesize attentionStatusChanged=_attentionStatusChanged;
@property(copy, nonatomic) CDUnknownBlockType friendRequestStatusChanged; // @synthesize friendRequestStatusChanged=_friendRequestStatusChanged;
@property(nonatomic) _Bool openInCurrentNavigationController; // @synthesize openInCurrentNavigationController=_openInCurrentNavigationController;
@property(copy, nonatomic) NSString *conversationTitle; // @synthesize conversationTitle=_conversationTitle;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *phoneName; // @synthesize phoneName=_phoneName;
@property(copy, nonatomic) NSString *friendRequestMessage; // @synthesize friendRequestMessage=_friendRequestMessage;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(copy, nonatomic) NSString *staffId; // @synthesize staffId=_staffId;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(nonatomic) _Bool popToRootWhileRemoveFriend; // @synthesize popToRootWhileRemoveFriend=_popToRootWhileRemoveFriend;
- (void).cxx_destruct;
- (id)workSummaryWithOrgId:(long long)arg1;
- (void)viewWillLayoutSubviews;
- (void)messageDidSend;
- (id)conversationSelectViewAttachmentDataForSend;
- (int)conversationSelectViewAttachmentType;
- (void)userDidTakeScreenshot:(id)arg1;
- (void)refreshAttentionStatus:(_Bool)arg1;
- (void)attentionStatusChange:(id)arg1;
- (void)remarkNameChange:(id)arg1;
- (void)tipsViewDidClick:(id)arg1;
- (void)operationCancelAttention;
- (void)operationAddAttention;
- (void)openEditMemberWithCard:(id)arg1;
- (void)addMemberIntoEnterprise:(id)arg1;
- (void)operationRemoveBlacklist;
- (void)addBlacklist;
- (void)operationAddBlacklist;
- (void)operationReport;
- (void)operationRecommendFriend;
- (void)operationRemarkName;
- (void)operationAddFriend;
- (void)operationFailAcceptFriend:(id)arg1;
- (void)operationSuccessAcceptFriend;
- (void)operationDidAcceptFriend;
- (void)operationFailRemoveFriend:(id)arg1;
- (void)operationSuccessRemoveFriend;
- (void)operationDidRemoveFriend;
- (id)profileBottomButtonWithTitle:(id)arg1 imageName:(id)arg2 frame:(struct CGRect)arg3 action:(SEL)arg4;
- (void)showsRelationListOfMasterRelation:(id)arg1 withRootCrumbName:(id)arg2;
- (void)showsRelationListOfMasterRelation:(id)arg1;
- (void)showDepartmentOrMasterEnterpriseCard:(id)arg1 OfEnterpriseCard:(id)arg2;
- (void)mobileContactSaveContactSuccess;
- (_Bool)isHttpOrHttps:(id)arg1;
- (void)openWebViewWithURL:(id)arg1;
- (void)gotoOrgCheng:(id)arg1;
- (void)gotoOrgVIP;
- (void)gotoEnterpriseHomePage:(id)arg1;
- (void)saveContactWithPhone:(id)arg1;
- (void)showsOperationsOfPhone:(id)arg1 forceCloseConference:(_Bool)arg2 isMobileContact:(_Bool)arg3;
- (void)showsOperationsOfTextContent:(id)arg1;
- (void)showMasterDetailWithEnterpriseCard:(id)arg1;
- (void)sendSMSWithPhone:(id)arg1;
- (void)sendEmailWithEmail:(id)arg1;
- (void)editProfile:(id)arg1;
- (void)moreOpearController:(id)arg1;
- (void)successToRemoveFriend;
- (void)removeFriendButtonPressed:(id)arg1;
- (void)successToAcceptFriend;
- (void)acceptFriendButtonPressed:(id)arg1;
- (void)addFriendButtonPressed:(id)arg1;
- (void)moreOperation:(id)arg1;
- (void)makeCall;
- (void)makeSystemCallWithPhone:(id)arg1;
- (void)conferenceButtonPressed:(id)arg1;
- (void)dingButtonPressed:(id)arg1;
- (void)msgButtonPressed:(id)arg1;
- (void)secretButtonPressed:(id)arg1;
- (void)showsWithContact:(id)arg1 enterpriseCards:(id)arg2 smartworkSummary:(id)arg3 crmContacts:(id)arg4 extContact:(id)arg5 reqeust:(id)arg6;
- (void)loadEnterpriseAndCrmCardFromServer;
- (void)loadSmartworkSummary;
- (void)loadExtContactInfo;
- (id)createSectionInfo:(id)arg1 forKey:(id)arg2 bgColor:(id)arg3;
- (id)createExtContactSectionInfo:(id)arg1;
- (void)loadDataFromServerAndShow;
- (void)loadDataInDBAndShow;
- (void)userTitleDidSelect:(id)arg1;
- (void)profileHeaderView:(id)arg1 avatarViewDidPressWith:(id)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showsAndLayoutActionButton:(_Bool)arg1;
- (double)tableViewTopMargin;
- (void)reloadWaterMarkViewWithEnterpriseCard:(id)arg1;
- (void)configNavigationRightItem;
- (void)configActionButton;
- (void)resetShowTag;
- (void)configProfileHeaderBlacklistStatus:(_Bool)arg1;
- (void)configProfileHeaderAttentionStatus:(_Bool)arg1;
- (void)configTableViewWithEnterpriseCard:(id)arg1 crmContact:(id)arg2;
- (void)configTableViewWithCrmContact:(id)arg1;
- (void)configTableViewWithEnterpriseCard:(id)arg1;
- (void)configDetailTableView;
- (void)configCRMNavigationView;
- (void)configOrgNavigationView;
- (void)checkMobileContact;
- (void)configProfileHeaderView;
- (void)resetRelationship;
- (void)showContactData:(_Bool)arg1 checkMobileContact:(_Bool)arg2;
- (void)showContactData:(_Bool)arg1;
- (void)loadDatasource;
- (void)contactProfilePopBack:(id)arg1;
- (void)loadComponent;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)setUpNotification;
- (id)initWithMobile:(id)arg1 name:(id)arg2;
- (id)initWithUid:(long long)arg1 staffId:(id)arg2 orgId:(long long)arg3;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

