//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTContactPickRegisterDelegate-Protocol.h"
#import "DTContactPickSelectedDelegate-Protocol.h"

@class DTContactPickModel, NSArray, NSDictionary, NSString, UINavigationController;
@protocol DTContactPickNavigationHandlerDelegate;

@interface DTContactPickNavigationHandler : NSObject <DTContactPickSelectedDelegate, DTContactPickRegisterDelegate>
{
    id <DTContactPickNavigationHandlerDelegate> _delegate;
    DTContactPickModel *_pickModel;
    UINavigationController *_pickViewController;
    NSArray *_observers;
    unsigned long long _selectedType;
    NSDictionary *_interalSelectedDepts;
    NSDictionary *_interalSelectedPersons;
    NSDictionary *_interalRequiredDepts;
    NSDictionary *_interalRequiredPersons;
    NSDictionary *_interalDisableDepts;
    NSDictionary *_interalDisablePersons;
    unsigned long long _totalPersonCount;
    unsigned long long _totalDepartsCount;
    unsigned long long _requiredPersonCount;
}

@property(nonatomic) unsigned long long requiredPersonCount; // @synthesize requiredPersonCount=_requiredPersonCount;
@property(nonatomic) unsigned long long totalDepartsCount; // @synthesize totalDepartsCount=_totalDepartsCount;
@property(nonatomic) unsigned long long totalPersonCount; // @synthesize totalPersonCount=_totalPersonCount;
@property(copy, nonatomic) NSDictionary *interalDisablePersons; // @synthesize interalDisablePersons=_interalDisablePersons;
@property(copy, nonatomic) NSDictionary *interalDisableDepts; // @synthesize interalDisableDepts=_interalDisableDepts;
@property(copy, nonatomic) NSDictionary *interalRequiredPersons; // @synthesize interalRequiredPersons=_interalRequiredPersons;
@property(copy, nonatomic) NSDictionary *interalRequiredDepts; // @synthesize interalRequiredDepts=_interalRequiredDepts;
@property(copy, nonatomic) NSDictionary *interalSelectedPersons; // @synthesize interalSelectedPersons=_interalSelectedPersons;
@property(copy, nonatomic) NSDictionary *interalSelectedDepts; // @synthesize interalSelectedDepts=_interalSelectedDepts;
@property(nonatomic) unsigned long long selectedType; // @synthesize selectedType=_selectedType;
@property(copy, nonatomic) NSArray *observers; // @synthesize observers=_observers;
@property(nonatomic) __weak UINavigationController *pickViewController; // @synthesize pickViewController=_pickViewController;
@property(retain, nonatomic) DTContactPickModel *pickModel; // @synthesize pickModel=_pickModel;
@property(nonatomic) __weak id <DTContactPickNavigationHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateDepartmentInfo;
- (void)updatePersonInfo;
- (void)updateStatusView;
- (void)personHasUnselected:(id)arg1;
- (void)personHasSelected:(id)arg1;
- (void)personsHasUnselected:(id)arg1;
- (void)personsHasSelected:(id)arg1;
- (void)departmentsHasUnselected:(id)arg1;
- (void)departmentsHasSelected:(id)arg1;
- (void)departmentHasUnselected:(id)arg1;
- (void)departmentHasSelected:(id)arg1;
- (void)conversationHasSelected:(id)arg1;
- (void)addPickObserver:(id)arg1;
- (_Bool)isDepartmentRequired:(id)arg1;
- (_Bool)isDepartmentDisable:(id)arg1;
- (_Bool)isDepartmentSelected:(id)arg1;
- (_Bool)isPersonHidden:(id)arg1;
- (_Bool)isPersonRequired:(id)arg1;
- (_Bool)isPersonDisable:(id)arg1;
- (_Bool)isPersonSelected:(id)arg1;
- (void)switchPickSelectedType:(unsigned long long)arg1;
- (unsigned long long)pickSelectedType;
- (void)removePickObserver:(id)arg1;
- (id)requiredDepts;
- (id)disableDepts;
- (id)selectedDepts;
- (id)allSelectedDepts;
- (id)disablePersons;
- (id)requiredPersons;
- (id)selectedPersons;
- (id)allSelectedPersons;
- (void)pickDidCancel;
- (void)memberFromDepartmentWithSuccessBlock:(CDUnknownBlockType)arg1;
- (void)createUidForPersonIfNeedWithSuccessBlock:(CDUnknownBlockType)arg1;
- (void)dealPersonsOnly;
- (void)pickDidFinish;
- (void)removeSelectedDept:(id)arg1;
- (_Bool)addSelectedDept:(id)arg1;
- (void)removeSelectedPerson:(id)arg1;
- (_Bool)addSelectedPerson:(id)arg1;
- (unsigned long long)selectedAndRequiredPersonCount;
- (unsigned long long)requiredPersonsCount;
- (unsigned long long)selectedPersonsCount;
- (unsigned long long)selectedDeptmentsCount;
- (void)closePickIfOverLimit;
- (id)initWithPickViewController:(id)arg1 pickModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

