//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIColor, UIFont, UIImage;

@interface DTContentBoardModel : NSObject
{
    UIImage *_btnImgNormal;
    UIImage *_btnImgHighlight;
    NSString *_btnText;
    UIColor *_btnTitleColorNormal;
    UIColor *_btnTitleColorHighlight;
    UIColor *_btnBackgroundColor;
    UIFont *_btnTitleFont;
}

@property(retain, nonatomic) UIFont *btnTitleFont; // @synthesize btnTitleFont=_btnTitleFont;
@property(retain, nonatomic) UIColor *btnBackgroundColor; // @synthesize btnBackgroundColor=_btnBackgroundColor;
@property(retain, nonatomic) UIColor *btnTitleColorHighlight; // @synthesize btnTitleColorHighlight=_btnTitleColorHighlight;
@property(retain, nonatomic) UIColor *btnTitleColorNormal; // @synthesize btnTitleColorNormal=_btnTitleColorNormal;
@property(copy, nonatomic) NSString *btnText; // @synthesize btnText=_btnText;
@property(retain, nonatomic) UIImage *btnImgHighlight; // @synthesize btnImgHighlight=_btnImgHighlight;
@property(retain, nonatomic) UIImage *btnImgNormal; // @synthesize btnImgNormal=_btnImgNormal;
- (void).cxx_destruct;

@end

