//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTAvatarImageView, DTContact, DTUserNameLabel, UIImageView, UILabel;

@interface DTConversationMembersCell : UITableViewCell
{
    DTContact *_item;
    DTAvatarImageView *_avatarView;
    DTUserNameLabel *_titleLabel;
    UILabel *_contentLabel;
    UILabel *_rightLabel;
    UILabel *_workStatusLabel;
    long long _uid;
    UIImageView *_topLine;
    UIImageView *_bottomLine;
}

@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIImageView *topLine; // @synthesize topLine=_topLine;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(retain, nonatomic) UILabel *workStatusLabel; // @synthesize workStatusLabel=_workStatusLabel;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) DTUserNameLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) DTAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(readonly, nonatomic) DTContact *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)drawSeperaterLineOfCell:(long long)arg1 number:(long long)arg2;
- (void)configWithItem:(id)arg1 isOwner:(_Bool)arg2 conversation:(id)arg3 memberWorkStatus:(id)arg4 needShowRealName:(_Bool)arg5;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

