//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "BusinessConfPersonDelegate-Protocol.h"
#import "DTConferenceHistoryDelegate-Protocol.h"
#import "DTSearchDisplayControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTBusinessConfPersonView, DTConferenceADModel, DTConferenceQuotaInfoView, DTConferenceQuotaShortInfoView, DTDetailQuotaModel, DTPickerStatus, DTSearchBar, DTSearchDisplayController, NSArray, NSDateFormatter, NSString, UIActivityIndicatorView, UIButton, UITableView, UIView;
@protocol conferenceDataRefreshDelegate;

@interface DTConferenceHistoryViewController : DTViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, DTSearchDisplayControllerDelegate, BusinessConfPersonDelegate, DTConferenceHistoryDelegate>
{
    _Bool _hasSetTop;
    _Bool _showSectionHeader;
    _Bool _hasShowAPNAlert;
    id <conferenceDataRefreshDelegate> _delegate;
    NSString *_cid;
    UIView *_bg;
    UITableView *_historyTableView;
    UIView *_historyTableHeaderView;
    UIButton *_startConference;
    DTSearchBar *_contactSearchBar;
    DTSearchDisplayController *_contactSearchDisplayController;
    DTPickerStatus *_pickerStatus;
    UIActivityIndicatorView *_indicatorView;
    NSArray *_result;
    NSDateFormatter *_dateFormatter;
    UIButton *_rightBarSettingButton;
    DTBusinessConfPersonView *_personView;
    DTConferenceQuotaInfoView *_quotaInfoView;
    UIView *_headView;
    UIView *_actionBackground;
    DTConferenceADModel *_adModel;
    DTDetailQuotaModel *_quotaDetailModel;
    UIButton *_quotaAlert;
    DTConferenceQuotaShortInfoView *_headerQuotaView;
}

@property(nonatomic) _Bool hasShowAPNAlert; // @synthesize hasShowAPNAlert=_hasShowAPNAlert;
@property(retain, nonatomic) DTConferenceQuotaShortInfoView *headerQuotaView; // @synthesize headerQuotaView=_headerQuotaView;
@property(nonatomic) _Bool showSectionHeader; // @synthesize showSectionHeader=_showSectionHeader;
@property(retain, nonatomic) UIButton *quotaAlert; // @synthesize quotaAlert=_quotaAlert;
@property(retain, nonatomic) DTDetailQuotaModel *quotaDetailModel; // @synthesize quotaDetailModel=_quotaDetailModel;
@property(retain, nonatomic) DTConferenceADModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) UIView *actionBackground; // @synthesize actionBackground=_actionBackground;
@property(nonatomic) _Bool hasSetTop; // @synthesize hasSetTop=_hasSetTop;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) DTConferenceQuotaInfoView *quotaInfoView; // @synthesize quotaInfoView=_quotaInfoView;
@property(retain, nonatomic) DTBusinessConfPersonView *personView; // @synthesize personView=_personView;
@property(retain, nonatomic) UIButton *rightBarSettingButton; // @synthesize rightBarSettingButton=_rightBarSettingButton;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) NSArray *result; // @synthesize result=_result;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) DTPickerStatus *pickerStatus; // @synthesize pickerStatus=_pickerStatus;
@property(retain, nonatomic) DTSearchDisplayController *contactSearchDisplayController; // @synthesize contactSearchDisplayController=_contactSearchDisplayController;
@property(retain, nonatomic) DTSearchBar *contactSearchBar; // @synthesize contactSearchBar=_contactSearchBar;
@property(retain, nonatomic) UIButton *startConference; // @synthesize startConference=_startConference;
@property(retain, nonatomic) UIView *historyTableHeaderView; // @synthesize historyTableHeaderView=_historyTableHeaderView;
@property(retain, nonatomic) UITableView *historyTableView; // @synthesize historyTableView=_historyTableView;
@property(retain, nonatomic) UIView *bg; // @synthesize bg=_bg;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(nonatomic) __weak id <conferenceDataRefreshDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)shouldCheckAPNStatus;
- (void)jumpToDetail:(unsigned long long)arg1;
- (void)sendInviteSMS:(long long)arg1;
- (void)shareSMSTo:(id)arg1 uid:(long long)arg2;
- (void)inviteUid:(long long)arg1;
- (void)feedBackPressed:(id)arg1 timeString:(id)arg2;
- (void)jumpQuotaDetail:(id)arg1;
- (void)jumpToDing:(id)arg1;
- (void)didPressAvatar:(id)arg1 delete:(_Bool)arg2;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (id)viewControllerName;
- (void)refreshQuotaInfoView;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)recordPress:(id)arg1;
- (void)expericeConferenceByKey;
- (_Bool)newRightUser;
- (unsigned long long)enterpriseCount;
- (id)memberArray;
- (_Bool)showQuotaAlert:(id)arg1;
- (void)configActionButton;
- (void)refreTopFav;
- (void)resetHeadView;
- (void)createTeam;
- (void)setting;
- (void)cancel;
- (void)popBackConferenceHistory;
- (_Bool)isModal;
- (id)momentString:(id)arg1;
- (id)dayString:(id)arg1;
- (CDUnknownBlockType)searchSingleCallBlock;
- (CDUnknownBlockType)contactPicked;
- (void)startConference:(id)arg1;
- (void)updateUsualContact:(long long)arg1 displayName:(id)arg2 mobile:(id)arg3;
- (_Bool)isSystemNoticeClosed;
- (void)checkAPNStatus;
- (void)showHistoryInfo:(_Bool)arg1;
- (void)loadData;
- (id)genDetail:(id)arg1;
- (void)loadCompoment;
- (void)callQuotaChange:(id)arg1;
- (void)loadQuotaModel;
- (void)loadADModel;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

