//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTCommonIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)sendUrl:(id)arg1 callback:(id)arg2;
- (void)getOverage:(id)arg1;
- (void)checkUrl:(id)arg1 callback:(id)arg2;
- (void)bridge:(id)arg1 callback:(id)arg2;
- (void)getWhiteDomains:(id)arg1;
- (void)getSystemTime:(id)arg1;

@end

