//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTBizConversation, DTContactPickDeptIdentifier, DTContactPickPersonIdentifier, NSArray;

@protocol DTContactPickSelectedDelegate <NSObject>
- (unsigned long long)pickSelectedType;

@optional
- (void)personsHasUnselected:(NSArray *)arg1;
- (void)personsHasSelected:(NSArray *)arg1;
- (void)departmentsHasUnselected:(NSArray *)arg1;
- (void)departmentsHasSelected:(NSArray *)arg1;
- (void)personHasUnselected:(DTContactPickPersonIdentifier *)arg1;
- (void)personHasSelected:(DTContactPickPersonIdentifier *)arg1;
- (void)departmentHasUnselected:(DTContactPickDeptIdentifier *)arg1;
- (void)departmentHasSelected:(DTContactPickDeptIdentifier *)arg1;
- (_Bool)isDepartmentRequired:(DTContactPickDeptIdentifier *)arg1;
- (_Bool)isDepartmentDisable:(DTContactPickDeptIdentifier *)arg1;
- (_Bool)isDepartmentSelected:(DTContactPickDeptIdentifier *)arg1;
- (_Bool)isPersonHidden:(DTContactPickPersonIdentifier *)arg1;
- (_Bool)isPersonRequired:(DTContactPickPersonIdentifier *)arg1;
- (_Bool)isPersonDisable:(DTContactPickPersonIdentifier *)arg1;
- (_Bool)isPersonSelected:(DTContactPickPersonIdentifier *)arg1;
- (void)switchPickSelectedType:(unsigned long long)arg1;
- (void)conversationHasSelected:(DTBizConversation *)arg1;
@end

