//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UILabel, UIView;

@interface DTConferenceQuotaShortInfoView : UIButton
{
    UILabel *_voipLabel;
    UILabel *_bizCallLabel;
    UILabel *_confLabel;
    UIView *_lineView1;
    UIView *_lineView2;
    UIView *_lineUnder;
}

@property(retain, nonatomic) UIView *lineUnder; // @synthesize lineUnder=_lineUnder;
@property(retain, nonatomic) UIView *lineView2; // @synthesize lineView2=_lineView2;
@property(retain, nonatomic) UIView *lineView1; // @synthesize lineView1=_lineView1;
@property(retain, nonatomic) UILabel *confLabel; // @synthesize confLabel=_confLabel;
@property(retain, nonatomic) UILabel *bizCallLabel; // @synthesize bizCallLabel=_bizCallLabel;
@property(retain, nonatomic) UILabel *voipLabel; // @synthesize voipLabel=_voipLabel;
- (void).cxx_destruct;
- (id)getQuotaLabel;
- (id)getLineView;
- (void)layoutSubviews;
- (void)refreshModel:(id)arg1;
- (void)loadCompoment;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

