//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTBizCSpaceDentry;

@interface DTCSpaceOperationProcessor : NSObject
{
    DTBizCSpaceDentry *_currentDentry;
}

@property(retain, nonatomic) DTBizCSpaceDentry *currentDentry; // @synthesize currentDentry=_currentDentry;
- (void).cxx_destruct;
- (void)addNewFolder:(id)arg1;
- (void)moveDentries:(id)arg1 from:(id)arg2 toTarget:(id)arg3;
- (void)deleteDentries:(id)arg1 withSpaceId:(long long)arg2;

@end

