//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "DTDentryPickerDelegate-Protocol.h"

@class BLAccount, BLSpaceEntry, DTBizCSpaceDentry, DTCSpaceFilesCellCallback, DTCSpaceFilterPhotoCollection, DTCSpaceFilterTable, NSArray, NSDictionary, NSString, UICollectionViewFlowLayout, UILabel;
@protocol DTFileBasedInterfaceRouteDelegate;

@interface DTCSpaceFilterViewController : DTViewController <DTDentryPickerDelegate>
{
    _Bool _callPicker;
    long long _filerType;
    BLSpaceEntry *_spaceEntry;
    DTBizCSpaceDentry *_folderDentry;
    NSArray *_orgIds;
    unsigned long long _accessType;
    BLAccount *_currentAccount;
    NSDictionary *_extraInfo;
    DTCSpaceFilterTable *_tableView;
    DTCSpaceFilesCellCallback *_cellCallback;
    DTBizCSpaceDentry *_operatingFile;
    id <DTFileBasedInterfaceRouteDelegate> _routeHandler;
    DTCSpaceFilterPhotoCollection *_collectionView;
    UICollectionViewFlowLayout *_flowLayout;
    UILabel *_headerLabel;
}

@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) DTCSpaceFilterPhotoCollection *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool callPicker; // @synthesize callPicker=_callPicker;
@property(retain, nonatomic) id <DTFileBasedInterfaceRouteDelegate> routeHandler; // @synthesize routeHandler=_routeHandler;
@property(retain, nonatomic) DTBizCSpaceDentry *operatingFile; // @synthesize operatingFile=_operatingFile;
@property(retain, nonatomic) DTCSpaceFilesCellCallback *cellCallback; // @synthesize cellCallback=_cellCallback;
@property(retain, nonatomic) DTCSpaceFilterTable *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(retain, nonatomic) BLAccount *currentAccount; // @synthesize currentAccount=_currentAccount;
@property(nonatomic) unsigned long long accessType; // @synthesize accessType=_accessType;
@property(retain, nonatomic) NSArray *orgIds; // @synthesize orgIds=_orgIds;
@property(retain, nonatomic) DTBizCSpaceDentry *folderDentry; // @synthesize folderDentry=_folderDentry;
@property(retain, nonatomic) BLSpaceEntry *spaceEntry; // @synthesize spaceEntry=_spaceEntry;
@property(nonatomic) long long filerType; // @synthesize filerType=_filerType;
- (void).cxx_destruct;
- (void)dentryPicker:(id)arg1 didChooseDentry:(id)arg2;
- (void)dentryPickerDidCancel:(id)arg1;
- (void)asksForDeleteConfirm:(_Bool)arg1 andIsMulitItems:(_Bool)arg2;
- (void)sendByMail:(id)arg1;
- (void)sendToContact:(id)arg1;
- (void)renameAction:(id)arg1;
- (void)moveAction:(id)arg1;
- (void)deleteAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)openActionSheetForFolder:(id)arg1;
- (void)openActionSheetForFile:(id)arg1;
- (void)openActionSheetForOnlyReadFile:(id)arg1;
- (void)openActionSheetForLocalFile:(id)arg1;
- (void)onTriggerCell:(id)arg1;
- (void)gotoDetailWithDentry:(id)arg1;
- (_Bool)canOperateFile:(id)arg1 withAccessType:(unsigned long long)arg2;
- (unsigned long long)currentListAccessType;
- (void)moveFailedNotification:(id)arg1;
- (void)moveNotification:(id)arg1;
- (void)renameNotification:(id)arg1;
- (void)deleteFailedNotification:(id)arg1;
- (void)deleteNotification:(id)arg1;
- (void)addNotification;
- (id)filterDataSource;
- (void)didReceiveMemoryWarning;
- (void)setupNavigationTitle;
- (id)filterDes;
- (void)setupHeaderText;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

