//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, UIWindow;

@interface DTDatabaseUpdating : NSObject
{
    struct _opaque_pthread_mutex_t _mutex;
    _Bool _updating;
    UIWindow *_window;
    long long _wndShowingCount;
    NSMutableArray *_waitBlocks;
    double _startTime;
}

+ (void)deleteMoreThanMaxCountDINGWithDatabase:(id)arg1;
+ (CDUnknownBlockType)upgradeMainDatabaseAtVersion:(unsigned long long)arg1;
+ (void)setMaxUpgradeVersion;
+ (void)setDatabaseIndexMaxUpgradeVersion;
+ (id)sharedInstance;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSMutableArray *waitBlocks; // @synthesize waitBlocks=_waitBlocks;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(nonatomic) long long wndShowingCount; // @synthesize wndShowingCount=_wndShowingCount;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)databaseAddAndDeleteIndex:(CDUnknownBlockType)arg1;
- (void)checkWhetherDowngraded:(CDUnknownBlockType)arg1;
- (void)checkUnEncryptedDatabase:(CDUnknownBlockType)arg1;
- (void)waitUntilUpdateDone:(CDUnknownBlockType)arg1;
- (void)checkUpdatingIfNeed:(CDUnknownBlockType)arg1;
- (void)updateLastLaunchAppVersion;
- (id)lastLaunchAppVersion;
- (void)closeWindow;
- (void)showWindow;
- (void)dealloc;
- (id)init;

@end

