//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

@class DTBizConversation, DTDefaultIconsHeadView, DTDefaultIconsMenuView, DTEnterpriseCard, NSString;

@interface DTDefaultIconsChooseViewController : DTViewController
{
    DTEnterpriseCard *_enterpriseCard;
    long long _chooseIconNextStyle;
    DTBizConversation *_conversation;
    NSString *_iconMediaId;
    DTDefaultIconsHeadView *_topIconView;
    DTDefaultIconsMenuView *_iconChooseView;
    long long _iconActionType;
}

@property(nonatomic) long long iconActionType; // @synthesize iconActionType=_iconActionType;
@property(retain, nonatomic) DTDefaultIconsMenuView *iconChooseView; // @synthesize iconChooseView=_iconChooseView;
@property(retain, nonatomic) DTDefaultIconsHeadView *topIconView; // @synthesize topIconView=_topIconView;
@property(copy, nonatomic) NSString *iconMediaId; // @synthesize iconMediaId=_iconMediaId;
@property(retain, nonatomic) DTBizConversation *conversation; // @synthesize conversation=_conversation;
@property(nonatomic) long long chooseIconNextStyle; // @synthesize chooseIconNextStyle=_chooseIconNextStyle;
@property(retain, nonatomic) DTEnterpriseCard *enterpriseCard; // @synthesize enterpriseCard=_enterpriseCard;
- (void).cxx_destruct;
- (void)configPhotoImage:(id)arg1;
- (void)onPhotoPick:(long long)arg1;
- (void)chooseFromAlbum;
- (void)openCamera;
- (void)onPhotoClick;
- (id)getIconsActionItems:(id)arg1;
- (void)getDefaultIcons;
- (id)getEnterpriseIconActionItem;
- (void)configHeadView;
- (double)statusBarAndNavigationBarHeight;
- (void)onUpdateDefaultIcon:(id)arg1;
- (void)onSaveDefaultIcon:(id)arg1;
- (void)configNavigationBar;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

