//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTRecentDentryInterfaceModule-Protocol.h"
#import "LWFetchedResultsControllerDelegate-Protocol.h"

@class BLAccount, DTDentryManager, LWFetchRequest, LWFetchedResultsController, NSString, NSTimer, UITableView;
@protocol DTRecentDentryInterface;

@interface DTDentryRecentPresenter : NSObject <LWFetchedResultsControllerDelegate, DTRecentDentryInterfaceModule>
{
    _Bool _hasMore;
    id <DTRecentDentryInterface> _userInterface;
    BLAccount *_account;
    DTDentryManager *_manager;
    LWFetchRequest *_fetchRequest;
    LWFetchedResultsController *_fetchController;
    NSTimer *_timer;
    UITableView *_tableView;
}

@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) LWFetchedResultsController *fetchController; // @synthesize fetchController=_fetchController;
@property(retain, nonatomic) LWFetchRequest *fetchRequest; // @synthesize fetchRequest=_fetchRequest;
@property(retain, nonatomic) DTDentryManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) BLAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <DTRecentDentryInterface> userInterface; // @synthesize userInterface=_userInterface;
- (void).cxx_destruct;
- (id)currentAccount;
- (_Bool)hasMoreCategories;
- (void)controllerDidRollback:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(long long)arg4 newIndex:(unsigned long long)arg5;
- (void)controllerWillChangeContent:(id)arg1;
- (void)datasourceModfiyNotifiatonIfNeed;
- (void)loadLocalData;
- (void)setUITableView:(id)arg1;
- (id)objectAtIndexPath:(id)arg1;
- (void)refreshRecentDentryOperation;
- (void)loadNextPageFromServer;
- (long long)loadNextPageFromLocal;
- (void)loadNextPage;
- (long long)dentryCategoryCount;
- (void)buildFetch;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

