//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MWPhotoBrowserDelegate-Protocol.h"

@class DTBizDingAttachmentExtra, DTBizDingModel, DTWebImageView, MWPhotoBrowser, NSMutableArray, NSString, UIImageView, UINavigationController;

@interface DTDingImageAttachView : UIView <MWPhotoBrowserDelegate>
{
    _Bool _isOriginalImage;
    NSString *_imageMediaId;
    DTWebImageView *_contentView;
    UIImageView *_backgroundView;
    DTBizDingAttachmentExtra *_attachmentFile;
    UINavigationController *_navigationController;
    DTBizDingModel *_dingModel;
    NSMutableArray *_photos;
    MWPhotoBrowser *_browser;
}

@property(retain, nonatomic) MWPhotoBrowser *browser; // @synthesize browser=_browser;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) DTBizDingModel *dingModel; // @synthesize dingModel=_dingModel;
@property(nonatomic) _Bool isOriginalImage; // @synthesize isOriginalImage=_isOriginalImage;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) DTBizDingAttachmentExtra *attachmentFile; // @synthesize attachmentFile=_attachmentFile;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) DTWebImageView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *imageMediaId; // @synthesize imageMediaId=_imageMediaId;
- (void).cxx_destruct;
- (id)photoBrowser:(id)arg1 customMenusAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 animateImageAtIndex:(unsigned long long)arg2;
- (_Bool)photoBrowser:(id)arg1 recogizedQRCode:(id)arg2 atIndex:(unsigned long long)arg3;
- (struct CGRect)photoBrowser:(id)arg1 animateFrameAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (id)currentNavigation;
- (void)singleTap;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

