//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSObject, NSString, UIButton, UILocalizedIndexedCollation, UITableView;
@protocol OS_dispatch_queue;

@interface DTDingReceiverChoserController : DTViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _showAddNewReceiver;
    NSMutableArray *_selectedRecUids;
    NSArray *_receiverUids;
    unsigned long long _maxReceiverCount;
    long long _orgId;
    CDUnknownBlockType _callback;
    NSMutableArray *_receiverCellDatas;
    NSMutableArray *_datasource;
    UITableView *_tableView;
    UILocalizedIndexedCollation *_collation;
    NSMutableArray *_sectionTitles;
    UIButton *_selectAllBtn;
    NSObject<OS_dispatch_queue> *_refreshQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *refreshQueue; // @synthesize refreshQueue=_refreshQueue;
@property(retain, nonatomic) UIButton *selectAllBtn; // @synthesize selectAllBtn=_selectAllBtn;
@property(retain, nonatomic) NSMutableArray *sectionTitles; // @synthesize sectionTitles=_sectionTitles;
@property(retain, nonatomic) UILocalizedIndexedCollation *collation; // @synthesize collation=_collation;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) NSMutableArray *receiverCellDatas; // @synthesize receiverCellDatas=_receiverCellDatas;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(nonatomic) unsigned long long maxReceiverCount; // @synthesize maxReceiverCount=_maxReceiverCount;
@property(nonatomic) _Bool showAddNewReceiver; // @synthesize showAddNewReceiver=_showAddNewReceiver;
@property(copy, nonatomic) NSArray *receiverUids; // @synthesize receiverUids=_receiverUids;
@property(retain, nonatomic) NSMutableArray *selectedRecUids; // @synthesize selectedRecUids=_selectedRecUids;
- (void).cxx_destruct;
- (void)selectAllPressed;
- (void)cellSelectStatus:(_Bool)arg1;
- (void)showSelectAll;
- (void)buildConfirmTitle;
- (void)cancelButtonPressed:(id)arg1;
- (void)confirmButtonPressed:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)choseNewPepolePressed:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)addDataIntoDataSource:(id)arg1;
- (void)loadDataSources;
- (void)reloadData;
- (void)configData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadUIComponent;
- (void)dealloc;
- (id)initWithCallback:(CDUnknownBlockType)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

