//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSNumber;

@interface DTDingFinishStatusModel : Marshal
{
    NSArray *_dingIds;
    NSNumber *_oldStatus;
    NSNumber *_currentStatus;
    NSNumber *_modelTypeInTopic;
    NSNumber *_selfCurrentStatus;
    NSNumber *_finishUid;
    NSNumber *_unFinishCount;
}

@property(retain, nonatomic) NSNumber *unFinishCount; // @synthesize unFinishCount=_unFinishCount;
@property(retain, nonatomic) NSNumber *finishUid; // @synthesize finishUid=_finishUid;
@property(retain, nonatomic) NSNumber *selfCurrentStatus; // @synthesize selfCurrentStatus=_selfCurrentStatus;
@property(retain, nonatomic) NSNumber *modelTypeInTopic; // @synthesize modelTypeInTopic=_modelTypeInTopic;
@property(retain, nonatomic) NSNumber *currentStatus; // @synthesize currentStatus=_currentStatus;
@property(retain, nonatomic) NSNumber *oldStatus; // @synthesize oldStatus=_oldStatus;
@property(copy, nonatomic) NSArray *dingIds; // @synthesize dingIds=_dingIds;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

