//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTDingModelConvert : NSObject
{
}

+ (id)attachmentConvert:(id)arg1;
+ (id)handlerWithAttachment:(id)arg1;
+ (id)convertDingModel:(id)arg1;
+ (id)convertContactArray:(id)arg1;
+ (id)convertToDingCreationResult:(id)arg1;
+ (id)convertToIMError:(id)arg1 cause:(id)arg2;

@end

