//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTBizDingAttachment, DTBizDingModel, DTBizDingReceiverModel, DTBizDingSendModel, NSArray, NSDictionary, NSNumber, NSString;
@protocol DTDingReceiverPersistenceProtocol, DTDingServiceNetworkProtocol, DTDingServicePersistenceProtocol;

@protocol DTDingServiceProtocol <NSObject>
@property(retain, nonatomic) id <DTDingServiceNetworkProtocol> networkIMP;
@property(retain, nonatomic) id <DTDingReceiverPersistenceProtocol> dingReceiverPersistenceIMP;
@property(retain, nonatomic) id <DTDingServicePersistenceProtocol> persistenceIMP;
- (void)getDingGuideInfoSuccessBlock:(void (^)(NSString *))arg1 failureBlock:(void (^)(id <IMError>))arg2;
- (_Bool)hasSendDingInLocal;
- (NSArray *)localDeadlineDings;
- (long long)hasExpireDeadlingCount;
- (long long)willExpireDeadlineDingCount;
- (NSArray *)longestDeadlineDingsWithNum:(long long)arg1;
- (void)deleteOldDingWithStatus:(_Bool)arg1 deleteCount:(long long)arg2;
- (long long)lastDingModifyAtNormalDing:(_Bool)arg1;
- (long long)dingCountInLocalWithStatus:(_Bool)arg1;
- (void)sendDingByTemplateId:(NSString *)arg1 uuid:(NSString *)arg2 receiverUids:(NSArray *)arg3 successBlock:(void (^)(_Bool))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)clearDeletedDingListWithSuccessBlock:(void (^)(void))arg1 failureBlock:(void (^)(id <IMError>))arg2;
- (void)getConfirmStatusInfo:(void (^)(NSString *))arg1 failureBlock:(void (^)(id <IMError>))arg2;
- (void)canSendDingToday:(void (^)(DTDingSendTimesModel *))arg1 failureBlock:(void (^)(id <IMError>))arg2;
- (void)loadDingWithId:(long long)arg1 fromNet:(_Bool)arg2 successBlock:(void (^)(DTBizDingModel *))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)loadDingWithId:(long long)arg1 successBlock:(void (^)(DTBizDingModel *))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)getDingRelatedUids:(long long)arg1 successBlock:(void (^)(NSArray *))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)commentNotify:(long long)arg1 turnOn:(_Bool)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)confirmDingModel:(DTBizDingModel *)arg1 successBlock:(void (^)(void))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)confirmDing:(long long)arg1 successBlock:(void (^)(void))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)pullDingList:(_Bool)arg1 cursor:(long long)arg2 size:(long long)arg3 type:(long long)arg4 successBlock:(void (^)(NSArray *))arg5 failureBlock:(void (^)(id <IMError>))arg6;
- (void)listDingReceiverListV2:(long long)arg1 successBlock:(void (^)(DTBizDingReceiverListModel *))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)listDingReceiverList:(long long)arg1 successBlock:(void (^)(DTBizDingReceiverListModel *))arg2 failureBlock:(void (^)(id <IMError>))arg3;
- (void)dingRemind:(long long)arg1 turnOn:(_Bool)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)changeDingFinishStatus:(DTBizDingModel *)arg1 finishStatus:(_Bool)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)changeDingStatusInBatch:(NSArray *)arg1 status:(NSNumber *)arg2 dingListType:(long long)arg3 successBlock:(void (^)(void))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)changeDingStatus:(DTBizDingModel *)arg1 status:(NSNumber *)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)listDeletedDing:(_Bool)arg1 cursor:(long long)arg2 size:(long long)arg3 successBlock:(void (^)(NSArray *))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)listSentDing:(_Bool)arg1 cursor:(long long)arg2 size:(long long)arg3 successBlock:(void (^)(NSArray *))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)listReceivedDing:(_Bool)arg1 cursor:(long long)arg2 size:(long long)arg3 confirmStatus:(long long)arg4 successBlock:(void (^)(NSArray *))arg5 failureBlock:(void (^)(id <IMError>))arg6;
- (void)listAllDing:(_Bool)arg1 cursor:(long long)arg2 size:(long long)arg3 successBlock:(void (^)(NSArray *))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)sendDingAgain:(NSNumber *)arg1 uids:(NSArray *)arg2 urgentLevel:(NSNumber *)arg3 successBlock:(void (^)(void))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)dingTransform:(NSArray *)arg1 uuid:(NSString *)arg2 urgentLevel:(long long)arg3 remindTime:(long long)arg4 entityType:(long long)arg5 enityId:(long long)arg6 conversationId:(NSString *)arg7 attachment:(DTBizDingAttachment *)arg8 extension:(NSDictionary *)arg9 successBlock:(void (^)(DTBizDingModel *))arg10 failureBlock:(void (^)(id <IMError>))arg11;
- (void)sendDingWithBizSendModel:(DTBizDingSendModel *)arg1 entityType:(long long)arg2 enityId:(long long)arg3 conversationId:(NSString *)arg4 attachment:(DTBizDingAttachment *)arg5 successBlock:(void (^)(DTBizDingModel *))arg6 failureBlock:(void (^)(id <IMError>))arg7;
- (void)sendDingWithBizSendModel:(DTBizDingSendModel *)arg1 attachment:(DTBizDingAttachment *)arg2 conversationId:(NSString *)arg3 successBlock:(void (^)(DTBizDingModel *))arg4 failureBlock:(void (^)(id <IMError>))arg5;
- (void)sendDingWithBizSendModel:(DTBizDingSendModel *)arg1 attachment:(DTBizDingAttachment *)arg2 successBlock:(void (^)(DTBizDingModel *))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)createDingWithUserIds:(NSArray *)arg1 dingModel:(DTBizDingModel *)arg2 successBlock:(void (^)(DTBizDingModel *))arg3 failureBlock:(void (^)(id <IMError>))arg4;
- (void)createDingWithUserIds:(NSArray *)arg1 uuid:(NSString *)arg2 urgentLevel:(long long)arg3 remindTime:(long long)arg4 attachment:(DTBizDingAttachment *)arg5 extension:(NSDictionary *)arg6 successBlock:(void (^)(DTBizDingModel *))arg7 failureBlock:(void (^)(id <IMError>))arg8;
- (void)createDingWithUserIds:(NSArray *)arg1 uuid:(NSString *)arg2 urgentLevel:(long long)arg3 remindTime:(long long)arg4 attachment:(DTBizDingAttachment *)arg5 successBlock:(void (^)(DTBizDingModel *))arg6 failureBlock:(void (^)(id <IMError>))arg7;
- (NSArray *)listLocalDingReceiversWithSenderUid:(long long)arg1 offset:(long long)arg2 limit:(long long)arg3;
- (DTBizDingReceiverModel *)localDingReceiversWithDingId:(long long)arg1;
- (DTBizDingReceiverModel *)localDingReceiversWithMd5String:(long long)arg1 md5String:(NSString *)arg2;
- (_Bool)saveLocalDingReceivers:(DTBizDingReceiverModel *)arg1;
- (void)localBatchUpdateHiddenStatus:(long long)arg1 dingIds:(NSArray *)arg2;
- (void)localBatchRemoveDing:(NSArray *)arg1;
- (unsigned long long)loadLocalNewRepliedDingCountWithFilterType:(long long)arg1;
- (unsigned long long)loadLocalUnconfirmedCountWithFilterType:(long long)arg1;
- (NSDictionary *)loadLocalUnreadCommentDing;
- (NSArray *)loadLocalEarlierReceivedDings:(long long)arg1 withCursor:(long long)arg2 andLimit:(long long)arg3;
- (NSArray *)loadLocalLatesReceivedDings:(long long)arg1 withCursor:(long long)arg2 andLimit:(long long)arg3;
- (NSArray *)loadLocalLatesReceivedDings:(long long)arg1 withLimit:(long long)arg2;
- (NSArray *)loadLocalEarlierSentDings:(long long)arg1 withCursor:(long long)arg2 andLimit:(long long)arg3;
- (NSArray *)loadLocalLatesSentDings:(long long)arg1 withCursor:(long long)arg2 andLimit:(long long)arg3;
- (NSArray *)loadLocalLatesSentDings:(long long)arg1 withLimit:(long long)arg2;
- (NSArray *)loadLocalDingsForDingIds:(NSArray *)arg1;
- (DTBizDingModel *)loadLocalDing:(long long)arg1;
- (_Bool)saveLocalDing:(DTBizDingModel *)arg1;
@end

