//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "DTDatePickerCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSDate, NSDateFormatter, NSString, UITableView;

@interface DTDingSendTimePickerController : DTViewController <UITableViewDataSource, UITableViewDelegate, DTDatePickerCellDelegate>
{
    _Bool _isSendRightNow;
    _Bool _shouldPickerShowen;
    NSDate *_sendTime;
    UITableView *_pickerTable;
    CDUnknownBlockType _sendTimePickedBlock;
    NSDateFormatter *_formatter;
}

@property(retain, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;
@property(nonatomic) _Bool shouldPickerShowen; // @synthesize shouldPickerShowen=_shouldPickerShowen;
@property(copy, nonatomic) CDUnknownBlockType sendTimePickedBlock; // @synthesize sendTimePickedBlock=_sendTimePickedBlock;
@property(retain, nonatomic) UITableView *pickerTable; // @synthesize pickerTable=_pickerTable;
@property(nonatomic) _Bool isSendRightNow; // @synthesize isSendRightNow=_isSendRightNow;
@property(copy, nonatomic) NSDate *sendTime; // @synthesize sendTime=_sendTime;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)datePickerCellWillClose;
- (void)datedidChanged:(id)arg1;
- (void)refreshTableData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)loadUIComponets;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSendTimePickedBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

