//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTAttributedLabel, NSString;
@protocol TTTAttributedLabelDelegate;

@interface DTDingDetailAttatchTextView : UIView
{
    id <TTTAttributedLabelDelegate> _attributedLabelDelegate;
    long long _maxLabelWidth;
    DTAttributedLabel *_textLabel;
    UIView *_labelBgView;
}

+ (double)textHeightWithText:(id)arg1 constraintWidth:(double)arg2;
+ (id)sharedAttributedLabel;
+ (double)heightWithText:(id)arg1 constraintWidth:(double)arg2;
+ (id)textColor;
+ (id)textFont;
@property(retain, nonatomic) UIView *labelBgView; // @synthesize labelBgView=_labelBgView;
@property(retain, nonatomic) DTAttributedLabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) long long maxLabelWidth; // @synthesize maxLabelWidth=_maxLabelWidth;
@property(nonatomic) __weak id <TTTAttributedLabelDelegate> attributedLabelDelegate; // @synthesize attributedLabelDelegate=_attributedLabelDelegate;
- (void).cxx_destruct;
- (void)setTextLabelHighBgColor:(_Bool)arg1;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)initWithFrame:(struct CGRect)arg1;

@end

