//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SWTableViewCell.h"

#import "TTTAttributedLabelDelegate-Protocol.h"

@class DTAvatarImageView, DTBadgeView, DTBizDingModel, DTDingAttachmentLinkView, DTDingImageAttachView, DTDingListActionView, DTDingListAttachAudioView, DTDingListAttachTextView, DTImageLabelView, DTLabel, DTMessageBubbleAttachmentFileView, DTUserNameLabel, NSString, UIButton, UIImageView, UILabel, UIView;
@protocol DTDingListCellDelegate;

@interface DTDingListCell : SWTableViewCell <TTTAttributedLabelDelegate>
{
    _Bool _isSelected;
    id <DTDingListCellDelegate> _dingDelegate;
    DTBizDingModel *_dingModel;
    long long _cellType;
    long long _cellEditType;
    CDUnknownBlockType _cellSelectedBlock;
    UIView *_mainView;
    DTUserNameLabel *_nameLabel;
    DTAvatarImageView *_avatarView;
    DTLabel *_timeLabel;
    UIView *_separatorLine;
    UIView *_topLine;
    UIImageView *_bottomLine;
    UIView *_dingMembersView;
    UILabel *_dingMemberLabel;
    UIButton *_dingMemberButton;
    UIImageView *_accessView;
    UIView *_currentContentView;
    DTDingListAttachTextView *_textView;
    DTDingListAttachAudioView *_audioView;
    DTDingImageAttachView *_attachmentImageView;
    DTMessageBubbleAttachmentFileView *_attachmentFileView;
    DTDingAttachmentLinkView *_attachmentLinkView;
    UIButton *_moreOperationButton;
    DTImageLabelView *_confirmedIconView;
    UIButton *_confirmButton;
    DTDingListActionView *_leftActionView;
    DTDingListActionView *_middleActionView;
    DTBadgeView *_badgeView;
    UIView *_actionLeftLine;
    UILabel *_deadlineTimeLabel;
    UIButton *_finishDingButton;
    UIButton *_hasFinishedDingButton;
    UILabel *_dingSourceLabel;
    UIImageView *_selectIconView;
    UIView *_editMaskView;
}

+ (double)heightOfConent:(id)arg1 textMaxLineCount:(long long)arg2;
+ (double)heightWithDingModel:(id)arg1 textMaxLineCount:(long long)arg2 cellListEditType:(long long)arg3;
+ (double)heightWithDingModel:(id)arg1 textMaxLineCount:(long long)arg2;
+ (_Bool)isImageAttachment:(id)arg1;
@property(retain, nonatomic) UIView *editMaskView; // @synthesize editMaskView=_editMaskView;
@property(retain, nonatomic) UIImageView *selectIconView; // @synthesize selectIconView=_selectIconView;
@property(retain, nonatomic) UILabel *dingSourceLabel; // @synthesize dingSourceLabel=_dingSourceLabel;
@property(retain, nonatomic) UIButton *hasFinishedDingButton; // @synthesize hasFinishedDingButton=_hasFinishedDingButton;
@property(retain, nonatomic) UIButton *finishDingButton; // @synthesize finishDingButton=_finishDingButton;
@property(retain, nonatomic) UILabel *deadlineTimeLabel; // @synthesize deadlineTimeLabel=_deadlineTimeLabel;
@property(retain, nonatomic) UIView *actionLeftLine; // @synthesize actionLeftLine=_actionLeftLine;
@property(retain, nonatomic) DTBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) DTDingListActionView *middleActionView; // @synthesize middleActionView=_middleActionView;
@property(retain, nonatomic) DTDingListActionView *leftActionView; // @synthesize leftActionView=_leftActionView;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) DTImageLabelView *confirmedIconView; // @synthesize confirmedIconView=_confirmedIconView;
@property(retain, nonatomic) UIButton *moreOperationButton; // @synthesize moreOperationButton=_moreOperationButton;
@property(retain, nonatomic) DTDingAttachmentLinkView *attachmentLinkView; // @synthesize attachmentLinkView=_attachmentLinkView;
@property(retain, nonatomic) DTMessageBubbleAttachmentFileView *attachmentFileView; // @synthesize attachmentFileView=_attachmentFileView;
@property(retain, nonatomic) DTDingImageAttachView *attachmentImageView; // @synthesize attachmentImageView=_attachmentImageView;
@property(retain, nonatomic) DTDingListAttachAudioView *audioView; // @synthesize audioView=_audioView;
@property(retain, nonatomic) DTDingListAttachTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UIView *currentContentView; // @synthesize currentContentView=_currentContentView;
@property(retain, nonatomic) UIImageView *accessView; // @synthesize accessView=_accessView;
@property(retain, nonatomic) UIButton *dingMemberButton; // @synthesize dingMemberButton=_dingMemberButton;
@property(retain, nonatomic) UILabel *dingMemberLabel; // @synthesize dingMemberLabel=_dingMemberLabel;
@property(retain, nonatomic) UIView *dingMembersView; // @synthesize dingMembersView=_dingMembersView;
@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) DTLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) DTAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) DTUserNameLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(copy, nonatomic) CDUnknownBlockType cellSelectedBlock; // @synthesize cellSelectedBlock=_cellSelectedBlock;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) long long cellEditType; // @synthesize cellEditType=_cellEditType;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(readonly, nonatomic) DTBizDingModel *dingModel; // @synthesize dingModel=_dingModel;
@property(nonatomic) __weak id <DTDingListCellDelegate> dingDelegate; // @synthesize dingDelegate=_dingDelegate;
- (void).cxx_destruct;
- (id)dingListReplyIconWithReddot:(_Bool)arg1;
- (id)unSupportLinkModel;
- (void)refreshNameAndTime;
- (void)updateCellScrollViewGesture;
- (void)showMoreOperation:(_Bool)arg1;
- (_Bool)isShowingConfirmedView;
- (void)cellScrollViewTapped:(id)arg1;
- (void)attributedLabel:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)displayNameChange:(id)arg1;
- (void)setUpNotification;
- (void)onDingSourceLabelPress:(id)arg1;
- (void)onSelectCell:(id)arg1;
- (void)onAttachmentPressed:(id)arg1;
- (void)onCommentBriefClicked:(id)arg1;
- (void)onConfirmDing:(id)arg1;
- (void)onUserNamePressed:(id)arg1;
- (void)onAvatarPress:(id)arg1;
- (void)openDingReceiverStatusListFromComfirm:(_Bool)arg1;
- (void)openDingReceiverStatusList:(id)arg1;
- (void)refreshLinesFrame;
- (void)refreshMainAndMaskViewFrame;
- (void)refreshAttachmentAndDeadlineFrame;
- (void)refreshTextOrAudioFrame;
- (void)refreshNameAndTimeFrame;
- (void)refreshAvatarFrame;
- (void)calculateFrameWithDing:(id)arg1 textMaxLineCount:(long long)arg2;
- (void)configWithDingModel:(id)arg1 dinglistEditType:(long long)arg2 isSelected:(_Bool)arg3;
- (void)configWithDingModel:(id)arg1;
- (void)showAttachment:(id)arg1;
- (void)showAttachmentWithLinkModel:(id)arg1;
- (void)showBriefViewWithDingModel:(id)arg1;
- (void)showReceiveDingActionsViewWithDingModel:(id)arg1;
- (void)showSendDingActionsViewWithDingModel:(id)arg1;
- (void)resetSendDingActionViewStatus;
- (void)showDetailActionViewWithDingModel:(id)arg1;
- (void)showActionsViewWithDingModel:(id)arg1;
- (void)showConfirmButtonWithDingModel:(id)arg1;
- (void)showSeeDingMembersView;
- (void)refreshBriefViewWithDingModelV2:(id)arg1;
- (void)refreshSeparatorLineWithDingModel:(id)arg1;
- (void)refreshDingFileAttachmentWithDingModel:(id)arg1 attachmentExtra:(id)arg2;
- (void)refreshDingImageAttachmentWithDingModel:(id)arg1 attachmentExtra:(id)arg2;
- (void)refreshAudioAttachmentWithDingModel:(id)arg1;
- (void)refreshTextAttachmentWithDingModel:(id)arg1;
- (void)refreshMainViewWithDingModel:(id)arg1;
- (void)refreshAvatarViewWithDingModel:(id)arg1;
- (void)finishButtonClicked:(id)arg1;
- (void)moreOpenationBtnClicked:(id)arg1;
- (void)attachmentLinkViewPressed:(id)arg1;
- (void)updateSelectIconViewImage;
- (void)layoutCellWithEditType:(long long)arg1 animation:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)layoutAllComponents;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 cellType:(long long)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)loadSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

