//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableSet, OpenMDHandler;

@interface DTEncryptCenter : NSObject
{
    OpenMDHandler *_databaseHandler;
    NSMutableSet *_loadingCorpSet;
    NSDictionary *_allKeys;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *allKeys; // @synthesize allKeys=_allKeys;
@property(retain, nonatomic) NSMutableSet *loadingCorpSet; // @synthesize loadingCorpSet=_loadingCorpSet;
@property(retain, nonatomic) OpenMDHandler *databaseHandler; // @synthesize databaseHandler=_databaseHandler;
- (void).cxx_destruct;
- (void)decryptKeys:(id)arg1;
- (id)convertEncryptModel:(id)arg1;
- (void)getEncryptionModelWithCorpId:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (id)encryptionModelWithCorpId:(id)arg1;
- (void)setEncryptionModel:(id)arg1;
- (id)decryptString:(id)arg1 corpId:(id)arg2 error:(id *)arg3;
- (id)encryptString:(id)arg1 corpId:(id)arg2 error:(id *)arg3;
- (id)decryptSource:(id)arg1 corpId:(id)arg2;
- (id)encryptSource:(id)arg1 corpId:(id)arg2;

@end

