//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "DTConversationSelectViewControllerDelegate-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentDatasource-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentProtocol-Protocol.h"
#import "MWPhotoBrowserDelegate-Protocol.h"
#import "TTTAttributedLabelDelegate-Protocol.h"

@class BLFavorite, DTAttributedLabel, DTAudioLevelMeterView, DTMessageBubbleAlipayRedEnvelopView, DTMessageBubbleAttachmentAudioView, DTMessageBubbleAttachmentCMailView, DTMessageBubbleAttachmentCOAView, DTMessageBubbleAttachmentCRMView, DTMessageBubbleAttachmentCSpaceView, DTMessageBubbleAttachmentCardView, DTMessageBubbleAttachmentFileView, DTMessageBubbleAttachmentImageView, DTMessageBubbleAttachmentLinkView, DTMessageBubbleAttachmentLocationView, DTMessageBubbleAttachmentShareView, DTMessageBubbleAttachmentTextView, DTMessageBubbleAttachmentVideoView, DTMessageBubbleCTitleView, DTMessageBubbleConferenceView, DTMessageBubbleDecryptFailView, DTMessageBubbleEmailView, DTMessageBubbleEnterpriseRedEnvelopView, DTMessageBubbleRedEnvelopView, DTWebImageView, MWPhotoBrowser, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIScrollView, UIView;

@interface DTFavoriteDetailViewController : DTViewController <DTMessageCollectionViewCellAttachmentDatasource, DTMessageCollectionViewCellAttachmentProtocol, MWPhotoBrowserDelegate, TTTAttributedLabelDelegate, DTConversationSelectViewControllerDelegate>
{
    _Bool _willDisappear;
    BLFavorite *_favorite;
    UIScrollView *_scrollView;
    UILabel *_nameLabel;
    UIView *_avaterView;
    UILabel *_timeLabel;
    UIImageView *_avatarImageView;
    UIView *_contentView;
    UIView *_lineView;
    DTAttributedLabel *_contentLabel;
    DTWebImageView *_picImageView;
    UIButton *_playButton;
    DTAudioLevelMeterView *_levelMeterView;
    UILabel *_durationLabel;
    UIView *_bubbleView;
    DTMessageBubbleAttachmentAudioView *_audioBubbleView;
    MWPhotoBrowser *_browser;
    NSMutableArray *_photos;
    struct CGSize _bubbleSize;
}

@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) MWPhotoBrowser *browser; // @synthesize browser=_browser;
@property(nonatomic) _Bool willDisappear; // @synthesize willDisappear=_willDisappear;
@property(retain, nonatomic) DTMessageBubbleAttachmentAudioView *audioBubbleView; // @synthesize audioBubbleView=_audioBubbleView;
@property(nonatomic) struct CGSize bubbleSize; // @synthesize bubbleSize=_bubbleSize;
@property(retain, nonatomic) UIView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) DTAudioLevelMeterView *levelMeterView; // @synthesize levelMeterView=_levelMeterView;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) DTWebImageView *picImageView; // @synthesize picImageView=_picImageView;
@property(retain, nonatomic) DTAttributedLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIView *avaterView; // @synthesize avaterView=_avaterView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) BLFavorite *favorite; // @synthesize favorite=_favorite;
- (void).cxx_destruct;
- (id)transToAttachmentWithFavorite:(id)arg1;
- (id)conversationSelectViewAttachmentDataForSend;
- (int)conversationSelectViewAttachmentType;
- (void)attributedLabel:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (id)getLocalAmrDataWithMessage:(id)arg1;
- (void)playAudioWithMessage:(id)arg1 startPlay:(CDUnknownBlockType)arg2 stopCallback:(CDUnknownBlockType)arg3;
- (void)playAudioWithMessage:(id)arg1;
- (void)messageBubbleAttachmentAudioViewStartPlay;
- (_Bool)messageAttachmentisOutgoing;
- (void)showBubbleWithAudio:(id)arg1;
- (struct CGSize)messageAudioBubbleSizeForAudio:(id)arg1 hasAvatarSpace:(_Bool)arg2;
- (id)getLocalImageUrlWithMessage:(id)arg1 isThumb:(_Bool)arg2;
- (void)setPicImageWithContent:(id)arg1;
- (struct CGSize)thumbnailViewSizeWithImageSize:(struct CGSize)arg1 imageScale:(double)arg2;
- (struct CGSize)getScreenSizeWithMediaIdString:(id)arg1 orientation:(long long)arg2;
- (id)userAvaterView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)photoBrowserDownloadImageError:(id)arg1 errUserInfo:(id)arg2;
- (id)photoBrowser:(id)arg1 animateImageAtIndex:(unsigned long long)arg2;
- (struct CGRect)photoBrowser:(id)arg1 animateFrameAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (id)getLocalImageWithMessage:(id)arg1 isThumb:(_Bool)arg2;
- (id)currentNavigation;
- (void)picImageTap:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)setupView;
- (void)configNameLabel:(id)arg1;
- (void)chooseSaveToSpace:(id)arg1;
- (void)chooseDelete:(id)arg1;
- (void)chooseForward:(id)arg1;
- (void)moreEvent:(id)arg1;
- (_Bool)needSaveCSpace;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) DTMessageBubbleAlipayRedEnvelopView *bubbleAlipayRedEnvelopView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentAudioView *bubbleAttachmentAudioView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCMailView *bubbleAttachmentCMailView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCRMView *bubbleAttachmentCRMView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCSpaceView *bubbleAttachmentCSpaceView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCardView *bubbleAttachmentCardView;
@property(readonly, nonatomic) DTMessageBubbleConferenceView *bubbleAttachmentConferenceView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentFileView *bubbleAttachmentFileView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentImageView *bubbleAttachmentImageView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentLinkView *bubbleAttachmentLinkView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentLocationView *bubbleAttachmentLocationView;
@property(readonly, nonatomic) DTMessageBubbleCTitleView *bubbleAttachmentOATitleView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCOAView *bubbleAttachmentOAView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentShareView *bubbleAttachmentShareView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentTextView *bubbleAttachmentTextView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentVideoView *bubbleAttachmentVideoView;
@property(readonly, nonatomic) DTMessageBubbleDecryptFailView *bubbleDecryptFailView;
@property(readonly, nonatomic) DTMessageBubbleEmailView *bubbleEmailView;
@property(readonly, nonatomic) DTMessageBubbleEnterpriseRedEnvelopView *bubbleEnterpriseRedEnvelopView;
@property(readonly, nonatomic) DTMessageBubbleRedEnvelopView *bubbleRedEnvelopView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

