//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SWTableViewCell.h"

#import "DTAudioLevelMeterViewDelegate-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentDatasource-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentProtocol-Protocol.h"

@class BLFavorite, DTAttributedLabel, DTMessageBubbleAlipayRedEnvelopView, DTMessageBubbleAttachmentAudioView, DTMessageBubbleAttachmentCMailView, DTMessageBubbleAttachmentCOAView, DTMessageBubbleAttachmentCRMView, DTMessageBubbleAttachmentCSpaceView, DTMessageBubbleAttachmentCardView, DTMessageBubbleAttachmentFileView, DTMessageBubbleAttachmentImageView, DTMessageBubbleAttachmentLinkView, DTMessageBubbleAttachmentLocationView, DTMessageBubbleAttachmentShareView, DTMessageBubbleAttachmentTextView, DTMessageBubbleAttachmentVideoView, DTMessageBubbleCTitleView, DTMessageBubbleConferenceView, DTMessageBubbleDecryptFailView, DTMessageBubbleEmailView, DTMessageBubbleEnterpriseRedEnvelopView, DTMessageBubbleRedEnvelopView, DTWebImageView, NSString, UIButton, UIImageView, UILabel, UIView;
@protocol DTFavoriteCellDelegate;

@interface DTFavoriteCommonCell : SWTableViewCell <DTAudioLevelMeterViewDelegate, DTMessageCollectionViewCellAttachmentDatasource, DTMessageCollectionViewCellAttachmentProtocol>
{
    _Bool _notShowForward;
    _Bool _needShowSaveToSpace;
    _Bool _disableLongPress;
    _Bool _hideTopPadding;
    id <DTFavoriteCellDelegate> _customDelegate;
    UILabel *_nameLabel;
    UIView *_avaterView;
    UILabel *_timeLabel;
    UIImageView *_orgImageView;
    UIImageView *_dingIconView;
    DTAttributedLabel *_dingTitleLabel;
    DTMessageBubbleAttachmentAudioView *_dingAudioView;
    DTAttributedLabel *_contentLabel;
    DTMessageBubbleAttachmentAudioView *_audioBubbleView;
    UIImageView *_detailContainer;
    UIImageView *_thumbnailImageView;
    UILabel *_summaryLabel;
    UILabel *_titleLabel;
    DTWebImageView *_picImageView;
    UIButton *_vedioPlayBtn;
    UIImageView *_avatarImageView;
    UIView *_mainView;
    BLFavorite *_favorite;
    UIView *_bottomLine;
}

+ (struct CGSize)stringSizeWithFont:(id)arg1 withString:(id)arg2 withSize:(struct CGSize)arg3;
+ (double)heightForFavoriteCell:(id)arg1;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) __weak BLFavorite *favorite; // @synthesize favorite=_favorite;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) _Bool hideTopPadding; // @synthesize hideTopPadding=_hideTopPadding;
@property(nonatomic) _Bool disableLongPress; // @synthesize disableLongPress=_disableLongPress;
@property(nonatomic) _Bool needShowSaveToSpace; // @synthesize needShowSaveToSpace=_needShowSaveToSpace;
@property(nonatomic) _Bool notShowForward; // @synthesize notShowForward=_notShowForward;
@property(retain, nonatomic) UIButton *vedioPlayBtn; // @synthesize vedioPlayBtn=_vedioPlayBtn;
@property(retain, nonatomic) DTWebImageView *picImageView; // @synthesize picImageView=_picImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UIImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(retain, nonatomic) UIImageView *detailContainer; // @synthesize detailContainer=_detailContainer;
@property(retain, nonatomic) DTMessageBubbleAttachmentAudioView *audioBubbleView; // @synthesize audioBubbleView=_audioBubbleView;
@property(retain, nonatomic) DTAttributedLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) DTMessageBubbleAttachmentAudioView *dingAudioView; // @synthesize dingAudioView=_dingAudioView;
@property(retain, nonatomic) DTAttributedLabel *dingTitleLabel; // @synthesize dingTitleLabel=_dingTitleLabel;
@property(retain, nonatomic) UIImageView *dingIconView; // @synthesize dingIconView=_dingIconView;
@property(retain, nonatomic) UIImageView *orgImageView; // @synthesize orgImageView=_orgImageView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIView *avaterView; // @synthesize avaterView=_avaterView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak id <DTFavoriteCellDelegate> customDelegate; // @synthesize customDelegate=_customDelegate;
- (void).cxx_destruct;
- (void)vedioPlayBtnClick:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)messageBubbleAttachmentAudioViewStartPlay;
- (_Bool)messageAttachmentisOutgoing;
- (void)layoutSubviews;
- (void)configCellWithFavorite:(id)arg1;
- (_Bool)needSaveCSpace;
- (void)setFavoriteAudioViewWithSize:(struct CGSize)arg1;
- (void)setPicImageWithContent:(id)arg1;
- (id)image:(id)arg1 scaleAndCroppForSize:(struct CGSize)arg2;
- (void)showBubbleWithBubbleView:(id)arg1 withMediaId:(id)arg2 withDuration:(long long)arg3 withVolums:(id)arg4;
- (void)removeAudioView;
- (void)setFavoriteDingAudioViewWithSize:(struct CGSize)arg1;
- (struct CGSize)messageAudioBubbleSizeWithMediaId:(id)arg1 withDuration:(long long)arg2 hasAvatarSpace:(_Bool)arg3;
- (void)configNameLabelWithContent:(id)arg1;
- (id)userAvaterView:(id)arg1;
- (void)signTap:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)saveToSpaceCell:(id)arg1;
- (void)deleteFavoriteCell:(id)arg1;
- (void)forwardFavoriteCell:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNameLabelText:(id)arg1;
- (void)addGestureRecognizers;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) DTMessageBubbleAlipayRedEnvelopView *bubbleAlipayRedEnvelopView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentAudioView *bubbleAttachmentAudioView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCMailView *bubbleAttachmentCMailView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCRMView *bubbleAttachmentCRMView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCSpaceView *bubbleAttachmentCSpaceView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCardView *bubbleAttachmentCardView;
@property(readonly, nonatomic) DTMessageBubbleConferenceView *bubbleAttachmentConferenceView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentFileView *bubbleAttachmentFileView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentImageView *bubbleAttachmentImageView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentLinkView *bubbleAttachmentLinkView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentLocationView *bubbleAttachmentLocationView;
@property(readonly, nonatomic) DTMessageBubbleCTitleView *bubbleAttachmentOATitleView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCOAView *bubbleAttachmentOAView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentShareView *bubbleAttachmentShareView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentTextView *bubbleAttachmentTextView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentVideoView *bubbleAttachmentVideoView;
@property(readonly, nonatomic) DTMessageBubbleDecryptFailView *bubbleDecryptFailView;
@property(readonly, nonatomic) DTMessageBubbleEmailView *bubbleEmailView;
@property(readonly, nonatomic) DTMessageBubbleEnterpriseRedEnvelopView *bubbleEnterpriseRedEnvelopView;
@property(readonly, nonatomic) DTMessageBubbleRedEnvelopView *bubbleRedEnvelopView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

