//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTContact, NSString;

@interface DTFriendRequest : NSObject
{
    long long _uid;
    DTContact *_contact;
    unsigned long long _status;
    unsigned long long _source;
    NSString *_remark;
}

@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) DTContact *contact; // @synthesize contact=_contact;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

