//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTIDLDingService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)changeDingFinishStatus:(id)arg1 finishStatus:(_Bool)arg2 callback:(id)arg3;
- (void)changeDingStatusInBatch:(id)arg1 action:(id)arg2 dingListType:(id)arg3 callback:(id)arg4;
- (void)getDingRelatedUids:(id)arg1 callback:(id)arg2;
- (void)commentNotify:(id)arg1 turnOn:(_Bool)arg2 callback:(id)arg3;
- (void)getGuideInfo:(id)arg1;
- (void)getOneKeyDingInfo:(id)arg1;
- (void)getRecommendedDingUsers:(id)arg1;
- (void)getConfirmStatusInfo:(id)arg1;
- (void)sendDingAgain:(id)arg1 uids:(id)arg2 urgentLevel:(id)arg3 callback:(id)arg4;
- (void)listDingReceiverListV2:(id)arg1 callback:(id)arg2;
- (void)sendDing:(id)arg1 callback:(id)arg2;
- (void)handleDing:(id)arg1 handleStatus:(id)arg2 callback:(id)arg3;
- (void)sendDingByTemplateId:(id)arg1 uuid:(id)arg2 recvUids:(id)arg3 callback:(id)arg4;
- (void)pullDingList:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 dingListType:(id)arg4 callback:(id)arg5;
- (void)getDingMemberByDingId:(id)arg1 callback:(id)arg2;
- (void)clearDeletedDingList:(id)arg1;
- (void)canSendDingToday:(id)arg1;
- (void)audioDingWithAttachments:(id)arg1 uuid:(id)arg2 urgentLevel:(id)arg3 remindTime:(id)arg4 audio:(id)arg5 attachments:(id)arg6 extension:(id)arg7 callback:(id)arg8;
- (void)textDingWithAttachments:(id)arg1 uuid:(id)arg2 urgentLevel:(id)arg3 remindTime:(id)arg4 content:(id)arg5 attachments:(id)arg6 extension:(id)arg7 callback:(id)arg8;
- (void)listDeleteDing:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 callback:(id)arg4;
- (void)listAllDing:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 callback:(id)arg4;
- (void)changeDingStatus:(id)arg1 status:(id)arg2 callback:(id)arg3;
- (void)sendDingComment:(id)arg1 callback:(id)arg2;
- (void)removeDingComment:(id)arg1 dingCommentId:(id)arg2 callback:(id)arg3;
- (void)listDingComment:(id)arg1 latest:(_Bool)arg2 cursor:(id)arg3 size:(id)arg4 callback:(id)arg5;
- (void)listDings:(id)arg1 callback:(id)arg2;
- (void)confirmDing:(id)arg1 callback:(id)arg2;
- (void)listDingReceiverList:(id)arg1 callback:(id)arg2;
- (void)dingRemind:(id)arg1 turnOn:(_Bool)arg2 callback:(id)arg3;
- (void)listSentDing:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 callback:(id)arg4;
- (void)listReceivedDing:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 confirmStatus:(id)arg4 callback:(id)arg5;
- (void)dingV2:(id)arg1 urgentLevel:(id)arg2 remindTime:(id)arg3 entityType:(id)arg4 enityId:(id)arg5 uuid:(id)arg6 callback:(id)arg7;
- (void)ding:(id)arg1 urgentLevel:(id)arg2 remindTime:(id)arg3 entityType:(id)arg4 enityId:(id)arg5 callback:(id)arg6;
- (void)dingWithAudio:(id)arg1 uuid:(id)arg2 urgentLevel:(id)arg3 remindTime:(id)arg4 audio:(id)arg5 callback:(id)arg6;
- (void)dingWithImage:(id)arg1 uuid:(id)arg2 urgentLevel:(id)arg3 remindTime:(id)arg4 picUrl:(id)arg5 callback:(id)arg6;
- (void)dingWithText:(id)arg1 uuid:(id)arg2 urgentLevel:(id)arg3 remindTime:(id)arg4 content:(id)arg5 callback:(id)arg6;
- (void)checkCalling:(id)arg1;
- (void)getMessages:(id)arg1 callback:(id)arg2;
- (void)confirmDingMessage:(id)arg1 callback:(id)arg2;
- (void)listDingSum:(id)arg1 endTime:(id)arg2 callback:(id)arg3;
- (void)listDingMessageByTime:(id)arg1 endTime:(id)arg2 callback:(id)arg3;
- (void)listDingMessage:(_Bool)arg1 cursor:(id)arg2 size:(id)arg3 callback:(id)arg4;
- (void)cancelDingMessage:(id)arg1 callback:(id)arg2;
- (void)cancelCallRemind:(id)arg1 callback:(id)arg2;
- (void)dingWithAudioMessage:(id)arg1 uids:(id)arg2 cid:(id)arg3 uuid:(id)arg4 audio:(id)arg5 callback:(id)arg6;
- (void)dingWithImageMessage:(id)arg1 uids:(id)arg2 cid:(id)arg3 uuid:(id)arg4 picUrl:(id)arg5 callback:(id)arg6;
- (void)dingWithTextMessage:(id)arg1 uids:(id)arg2 cid:(id)arg3 uuid:(id)arg4 content:(id)arg5 callback:(id)arg6;
- (void)getDingConfirmUsers:(id)arg1 callback:(id)arg2;
- (void)getDingUnconfirmUsers:(id)arg1 callback:(id)arg2;
- (void)getUnreadUsers:(id)arg1 callback:(id)arg2;
- (void)dingMessage:(id)arg1 callTime:(id)arg2 uids:(id)arg3 callback:(id)arg4;

@end

