//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseAPITask.h"

@class BLMail, DTIMAPAccount;

@interface DTIMAPFetchDetailTask : BLBaseAPITask
{
    BLMail *_mail;
    DTIMAPAccount *_imapAccount;
}

@property(retain, nonatomic) DTIMAPAccount *imapAccount; // @synthesize imapAccount=_imapAccount;
@property(retain, nonatomic) BLMail *mail; // @synthesize mail=_mail;
- (void).cxx_destruct;
- (unsigned long long)canRetryWithError:(id)arg1;
- (id)findPreferDetails:(id)arg1;
- (void)process;

@end

