//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImageView, UILabel;

@interface DTIndustryPickerLabel : UIButton
{
    UIImageView *_leftLine;
    UILabel *_nameLabel;
}

@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *leftLine; // @synthesize leftLine=_leftLine;
- (void).cxx_destruct;
- (void)configWithNeedLeftLine:(_Bool)arg1;

@end

