//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTInvitationRedDot;

@interface DTInvitationManager : NSObject
{
    DTInvitationRedDot *_invitation;
}

+ (id)invitationForRedDotModel:(id)arg1;
+ (id)shareInstance;
@property(retain, nonatomic) DTInvitationRedDot *invitation; // @synthesize invitation=_invitation;
- (void).cxx_destruct;
- (unsigned long long)dotType;
- (void)setIsFirstTimeToShowInvitation:(_Bool)arg1;
- (_Bool)isFirstTimeToShowInvitation;
- (void)setHasNewInvitation:(_Bool)arg1;
- (_Bool)hasNewInvitation;
- (void)setInvitationSettingInfo:(id)arg1;
- (void)dotHasClicked;
- (id)dotInfo;
- (_Bool)needShowRedDot;

@end

