//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLMessageView.h"

#import "DTMailReaderHeaderViewDelegate-Protocol.h"

@class DTMailReaderHeaderView, NSString;
@protocol DTMailReaderContentViewDelegate;

@interface DTMailReaderContentView : BLMessageView <DTMailReaderHeaderViewDelegate>
{
    id <DTMailReaderContentViewDelegate> _delegate;
    DTMailReaderHeaderView *_headerView;
}

@property(retain, nonatomic) DTMailReaderHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <DTMailReaderContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)elementTopPaddingForAttachmentListView:(id)arg1;
- (double)distanceBetweenElementsInAttachmentListView:(id)arg1;
- (double)elementRightPaddingForAttachmentListView:(id)arg1;
- (double)elementLeftPaddingForAttachmentListView:(id)arg1;
- (double)elementHeightForAttachmentListView:(id)arg1;
- (double)elementWidthForAttachmentListView:(id)arg1;
- (id)attachmentListView:(id)arg1 elementViewAtIndex:(unsigned long long)arg2 withFrame:(struct CGRect)arg3;
- (void)toldHeadViewChangedWithHeight:(double)arg1;
- (void)clickCalendarAreaInHeaderView:(id)arg1;
- (void)clickOnRecipientInHeaderView:(id)arg1;
- (id)mailHeaderView;
- (void)initMailDetailHeader;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

