//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BLAccount, BLFolder, DTBadgeView, NSMutableArray, NSString, UITableView;
@protocol BLFolderListViewControllerDelegate;

@interface DTMailFolderListViewController : DTViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isReloading;
    id <BLFolderListViewControllerDelegate> _delegate;
    BLFolder *_selectedFolder;
    BLAccount *_account;
    UITableView *_tableView;
    NSMutableArray *_systemFolders;
    NSMutableArray *_customFolders;
    DTBadgeView *_badgeView;
}

@property(retain, nonatomic) DTBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) _Bool isReloading; // @synthesize isReloading=_isReloading;
@property(retain, nonatomic) NSMutableArray *customFolders; // @synthesize customFolders=_customFolders;
@property(retain, nonatomic) NSMutableArray *systemFolders; // @synthesize systemFolders=_systemFolders;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) BLAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) BLFolder *selectedFolder; // @synthesize selectedFolder=_selectedFolder;
@property(nonatomic) __weak id <BLFolderListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)hideRedBallAtSettingButton;
- (void)showRedBallAtSettingButton;
- (id)folderAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)popBackFolderList;
- (void)onMailSettingButtonClicked:(id)arg1;
- (id)findChildsWithParent:(id)arg1 inFolders:(id)arg2;
- (id)treeSortCustomFolders:(id)arg1;
- (void)reloadDataSource;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

