//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BLMail;
@protocol DTMailTagsShowDelegate;

@interface DTMailTagsManager : NSObject
{
    struct {
        unsigned int isImportant:4;
        unsigned int isNeedAlarm:4;
    } _flags;
    BLMail *_parsedMail;
    id <DTMailTagsShowDelegate> _delegate;
}

@property(nonatomic) __weak id <DTMailTagsShowDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BLMail *parsedMail; // @synthesize parsedMail=_parsedMail;
- (void).cxx_destruct;
- (void)parseMailTags;
- (void)toggleAlarmTag;
- (void)toggleImportantTag;
- (_Bool)mailIsNeedAlarm;
- (_Bool)mailIsImportant;
- (id)initWithParsedMail:(id)arg1;

@end

