//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTMessageBaseViewController.h"

@interface DTMessageBaseViewController (Cmail)
- (void)messageBubbleCViewFooterRightButton:(id)arg1 footerView:(id)arg2;
- (void)messageBubbleCViewFooterMiddleButton:(id)arg1 footerView:(id)arg2;
- (void)messageBubbleCViewFooterLeftButton:(id)arg1 footerView:(id)arg2;
@end

