//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "DTMessageBubbleAttachmentProtocal-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel;

@interface DTMessageBubbleAttachmentFileView : UIView <DTMessageBubbleAttachmentProtocal>
{
    CDUnknownBlockType _cleanSelectedFileBlock;
    UIImageView *_bgImageView;
    UIImageView *_iconImageView;
    UILabel *_contentLabel;
    UILabel *_fileSizeLabel;
    UIButton *_deleteBtn;
}

+ (struct CGSize)calculateSizeWithItem:(id)arg1 showRightBtn:(_Bool)arg2 constraintsSize:(struct CGSize)arg3;
+ (struct CGSize)calculateSizeWithItem:(id)arg1 constraintsSize:(struct CGSize)arg2;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(readonly, nonatomic) UILabel *fileSizeLabel; // @synthesize fileSizeLabel=_fileSizeLabel;
@property(readonly, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(readonly, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(readonly, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(copy, nonatomic) CDUnknownBlockType cleanSelectedFileBlock; // @synthesize cleanSelectedFileBlock=_cleanSelectedFileBlock;
- (void).cxx_destruct;
- (void)onDeleteIconClick:(id)arg1;
- (void)layoutSubviews;
- (void)configWithItem:(id)arg1 showDeleteBtn:(_Bool)arg2 complete:(CDUnknownBlockType)arg3;
- (void)configWithItem:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

