//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "DTMessageAvatarViewDelegate-Protocol.h"
#import "DTMessageBubbleAttachmentCOAViewFooterViewDelegate-Protocol.h"
#import "DTMessageBubbleViewDataSource-Protocol.h"
#import "DTMessageBubbleViewDelegate-Protocol.h"
#import "DTMessageCellMaskViewDelegate-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentDatasource-Protocol.h"
#import "DTMessageCollectionViewCellAttachmentProtocol-Protocol.h"
#import "DTMessageRefreshViewDelegate-Protocol.h"
#import "DTMessageStatusViewDelegate-Protocol.h"
#import "DTMessageTagViewDelegate-Protocol.h"
#import "DTMessagesNameViewDelegate-Protocol.h"

@class DTAvatarImageView, DTBizMessage, DTMessageAvatarView, DTMessageBubbleAlipayRedEnvelopView, DTMessageBubbleAttachmentAudioView, DTMessageBubbleAttachmentCMailView, DTMessageBubbleAttachmentCOAView, DTMessageBubbleAttachmentCRMView, DTMessageBubbleAttachmentCSpaceView, DTMessageBubbleAttachmentCardView, DTMessageBubbleAttachmentFileView, DTMessageBubbleAttachmentImageView, DTMessageBubbleAttachmentLinkView, DTMessageBubbleAttachmentLocationView, DTMessageBubbleAttachmentShareView, DTMessageBubbleAttachmentTextView, DTMessageBubbleAttachmentVideoView, DTMessageBubbleCTitleView, DTMessageBubbleConferenceView, DTMessageBubbleDecryptFailView, DTMessageBubbleEmailView, DTMessageBubbleEnterpriseRedEnvelopView, DTMessageBubbleRedEnvelopView, DTMessageBubbleView, DTMessageCellMaskView, DTMessageCollectionViewLayoutAttributes, DTMessageContactTitleView, DTMessageRefreshView, DTMessageStatusView, DTMessageTagView, DTMessageTimestampMessageView, DTMessagesNameView, DTNewMessagesAnchorView, NSString, UIImageView, UILabel;
@protocol DTMessageCollectionViewCellDataSource, DTMessageCollectionViewCellDelegate;

@interface DTMessageCollectionViewCell : UICollectionViewCell <DTMessageCollectionViewCellAttachmentProtocol, DTMessageCollectionViewCellAttachmentDatasource, DTMessageBubbleViewDelegate, DTMessageBubbleViewDataSource, DTMessageAvatarViewDelegate, DTMessageStatusViewDelegate, DTMessageBubbleAttachmentCOAViewFooterViewDelegate, DTMessageTagViewDelegate, DTMessageRefreshViewDelegate, DTMessagesNameViewDelegate, DTMessageCellMaskViewDelegate>
{
    DTMessageBubbleView *_messageBubbleView;
    DTMessageStatusView *_messageStatusView;
    DTMessageAvatarView *_messageAvatarView;
    DTNewMessagesAnchorView *_theNewMessageAnchorView;
    DTMessageTimestampMessageView *_timesTampMessageView;
    DTMessagesNameView *_cellNameView;
    DTMessageBubbleCTitleView *_bubbleAttachmentOATitleView;
    UILabel *_cellbottomLabel;
    UIImageView *_selectIconView;
    DTMessageTagView *_tagView;
    DTMessageRefreshView *_refreshView;
    DTMessageTagView *_sourceTagView;
    UILabel *_timesTampLabel;
    DTMessageCellMaskView *_maskView;
    UIImageView *_audioUnreadImageView;
    DTMessageBubbleAttachmentImageView *_bubbleAttachmentImageView;
    DTMessageBubbleAttachmentAudioView *_bubbleAttachmentAudioView;
    DTMessageBubbleAttachmentTextView *_bubbleAttachmentTextView;
    DTMessageBubbleAttachmentFileView *_bubbleAttachmentFileView;
    DTMessageBubbleAttachmentLinkView *_bubbleAttachmentLinkView;
    DTMessageBubbleAttachmentShareView *_bubbleAttachmentShareView;
    DTMessageBubbleAttachmentCOAView *_bubbleAttachmentOAView;
    DTMessageBubbleAttachmentCSpaceView *_bubbleAttachmentCSpaceView;
    DTMessageBubbleAttachmentCMailView *_bubbleAttachmentCMailView;
    DTMessageBubbleEmailView *_bubbleEmailView;
    DTMessageBubbleAttachmentCardView *_bubbleAttachmentCardView;
    DTMessageBubbleAttachmentCRMView *_bubbleAttachmentCRMView;
    DTMessageBubbleAttachmentLocationView *_bubbleAttachmentLocationView;
    DTMessageBubbleRedEnvelopView *_bubbleRedEnvelopView;
    DTMessageBubbleEnterpriseRedEnvelopView *_bubbleEnterpriseRedEnvelopView;
    DTMessageBubbleAlipayRedEnvelopView *_bubbleAlipayRedEnvelopView;
    DTMessageBubbleAttachmentVideoView *_bubbleAttachmentVideoView;
    DTMessageBubbleDecryptFailView *_bubbleDecryptFailView;
    DTMessageBubbleConferenceView *_bubbleConferenceView;
    _Bool _userTitleEnabled;
    DTMessageContactTitleView *_contactTitleView;
    DTAvatarImageView *_avatarImageView;
    DTMessageCollectionViewLayoutAttributes *_messageCollectionViewLayoutAttributes;
    id <DTMessageCollectionViewCellDelegate> _delegate;
    id <DTMessageCollectionViewCellDataSource> _dataSource;
    DTBizMessage *_message;
    UILabel *_cellTopLabel;
    struct CGSize _attachmentImageSize;
}

+ (id)cellReuseIdentifierWithMessageType:(long long)arg1;
@property(nonatomic) _Bool userTitleEnabled; // @synthesize userTitleEnabled=_userTitleEnabled;
@property(nonatomic) struct CGSize attachmentImageSize; // @synthesize attachmentImageSize=_attachmentImageSize;
@property(retain, nonatomic) DTMessageBubbleDecryptFailView *bubbleDecryptFailView; // @synthesize bubbleDecryptFailView=_bubbleDecryptFailView;
@property(retain, nonatomic) DTMessageBubbleAttachmentVideoView *bubbleAttachmentVideoView; // @synthesize bubbleAttachmentVideoView=_bubbleAttachmentVideoView;
@property(retain, nonatomic) DTMessageBubbleEnterpriseRedEnvelopView *bubbleEnterpriseRedEnvelopView; // @synthesize bubbleEnterpriseRedEnvelopView=_bubbleEnterpriseRedEnvelopView;
@property(retain, nonatomic) DTMessageBubbleRedEnvelopView *bubbleRedEnvelopView; // @synthesize bubbleRedEnvelopView=_bubbleRedEnvelopView;
@property(retain, nonatomic) DTMessageBubbleAttachmentLocationView *bubbleAttachmentLocationView; // @synthesize bubbleAttachmentLocationView=_bubbleAttachmentLocationView;
@property(retain, nonatomic) DTMessageBubbleAttachmentCRMView *bubbleAttachmentCRMView; // @synthesize bubbleAttachmentCRMView=_bubbleAttachmentCRMView;
@property(retain, nonatomic) DTMessageBubbleAttachmentCardView *bubbleAttachmentCardView; // @synthesize bubbleAttachmentCardView=_bubbleAttachmentCardView;
@property(retain, nonatomic) DTMessageBubbleEmailView *bubbleEmailView; // @synthesize bubbleEmailView=_bubbleEmailView;
@property(retain, nonatomic) DTMessageBubbleCTitleView *bubbleAttachmentOATitleView; // @synthesize bubbleAttachmentOATitleView=_bubbleAttachmentOATitleView;
@property(retain, nonatomic) DTMessageBubbleAttachmentShareView *bubbleAttachmentShareView; // @synthesize bubbleAttachmentShareView=_bubbleAttachmentShareView;
@property(retain, nonatomic) DTMessageBubbleAttachmentLinkView *bubbleAttachmentLinkView; // @synthesize bubbleAttachmentLinkView=_bubbleAttachmentLinkView;
@property(retain, nonatomic) DTMessageBubbleAttachmentFileView *bubbleAttachmentFileView; // @synthesize bubbleAttachmentFileView=_bubbleAttachmentFileView;
@property(retain, nonatomic) DTMessageBubbleAttachmentAudioView *bubbleAttachmentAudioView; // @synthesize bubbleAttachmentAudioView=_bubbleAttachmentAudioView;
@property(retain, nonatomic) DTMessageBubbleAttachmentImageView *bubbleAttachmentImageView; // @synthesize bubbleAttachmentImageView=_bubbleAttachmentImageView;
@property(retain, nonatomic) DTMessageBubbleAttachmentTextView *bubbleAttachmentTextView; // @synthesize bubbleAttachmentTextView=_bubbleAttachmentTextView;
@property(retain, nonatomic) UILabel *cellTopLabel; // @synthesize cellTopLabel=_cellTopLabel;
@property(retain, nonatomic) DTBizMessage *message; // @synthesize message=_message;
@property(nonatomic) __weak id <DTMessageCollectionViewCellDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <DTMessageCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *timesTampLabel; // @synthesize timesTampLabel=_timesTampLabel;
@property(retain, nonatomic) DTMessageCollectionViewLayoutAttributes *messageCollectionViewLayoutAttributes; // @synthesize messageCollectionViewLayoutAttributes=_messageCollectionViewLayoutAttributes;
@property(retain, nonatomic) DTAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIImageView *audioUnreadImageView; // @synthesize audioUnreadImageView=_audioUnreadImageView;
@property(retain, nonatomic) DTMessageCellMaskView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UILabel *cellbottomLabel; // @synthesize cellbottomLabel=_cellbottomLabel;
@property(retain, nonatomic) DTMessageTagView *sourceTagView; // @synthesize sourceTagView=_sourceTagView;
@property(readonly, nonatomic) DTMessageRefreshView *refreshView; // @synthesize refreshView=_refreshView;
@property(retain, nonatomic) DTMessageTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) DTMessagesNameView *cellNameView; // @synthesize cellNameView=_cellNameView;
@property(retain, nonatomic) DTMessageTimestampMessageView *timesTampMessageView; // @synthesize timesTampMessageView=_timesTampMessageView;
@property(retain, nonatomic) DTNewMessagesAnchorView *theNewMessageAnchorView; // @synthesize theNewMessageAnchorView=_theNewMessageAnchorView;
@property(retain, nonatomic) UIImageView *selectIconView; // @synthesize selectIconView=_selectIconView;
@property(retain, nonatomic) DTMessageStatusView *messageStatusView; // @synthesize messageStatusView=_messageStatusView;
@property(retain, nonatomic) DTMessageBubbleView *messageBubbleView; // @synthesize messageBubbleView=_messageBubbleView;
@property(readonly, nonatomic) DTMessageContactTitleView *contactTitleView; // @synthesize contactTitleView=_contactTitleView;
@property(retain, nonatomic) DTMessageAvatarView *messageAvatarView; // @synthesize messageAvatarView=_messageAvatarView;
- (void).cxx_destruct;
- (void)handleEndPanGesture:(id)arg1;
- (void)handleChangePanGesture:(id)arg1;
- (void)panGestureWithOffset:(double)arg1;
- (void)footerViewRightButtonEvent:(id)arg1;
- (void)footerViewmiddleButtonEvent:(id)arg1;
- (void)footerViewLeftButtonEvent:(id)arg1;
- (id)bubbleMessage:(id)arg1;
- (id)bubbleConversation:(id)arg1;
- (void)pauseUploadingButtonPressed;
- (void)failureButtonPressed;
- (void)confirmReceived:(id)arg1;
- (void)messageBubbleViewLongGestureBecomeNextResponder:(id)arg1;
- (void)messageBubbleView:(id)arg1 triggerMenuActionWithType:(long long)arg2;
- (void)messageBubbleView:(id)arg1 didDoubleTappedWithGestureRecognizer:(id)arg2;
- (void)messageBubbleView:(id)arg1 didTappedWithGestureRecognizer:(id)arg2;
- (void)unreadAlertButtonPressed;
- (void)statusAlertBringToFront;
- (void)unreadCountButtonPressed;
- (void)leftButtonClick:(id)arg1;
- (void)messageRefreshViewDidClick:(id)arg1;
- (void)messageTagIconClick:(id)arg1 tagViewModel:(id)arg2;
- (void)messageTagClick:(id)arg1 tagViewModel:(id)arg2;
- (void)avatarViewLongPress;
- (void)avatarViewDidTap;
- (void)messageBubbleAttachmentAudioViewStartPlay;
- (_Bool)messageAttachmentisOutgoing;
- (void)attributedLabel:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
@property(readonly, nonatomic) DTMessageBubbleConferenceView *bubbleAttachmentConferenceView;
@property(readonly, nonatomic) DTMessageBubbleAlipayRedEnvelopView *bubbleAlipayRedEnvelopView;
- (void)setContactTitleViewEnabled:(_Bool)arg1;
- (void)setAvatarIconModel:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)updateSelectIconViewImage;
- (void)messageCellMaskViewTapAction;
- (void)removeAudioUnreadImageView;
- (void)configLayoutAttributes:(id)arg1;
- (void)configLayoutAttributes:(id)arg1 animation:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, nonatomic) DTMessageBubbleAttachmentCMailView *bubbleAttachmentCMailView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCSpaceView *bubbleAttachmentCSpaceView;
@property(readonly, nonatomic) DTMessageBubbleAttachmentCOAView *bubbleAttachmentOAView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

