//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTMessageCollectionViewCell.h"

@interface DTMessageCollectionViewCellIncoming : DTMessageCollectionViewCell
{
}

+ (id)cellReuseIdentifierWithMessageType:(long long)arg1;
- (void)handleEndPanGesture:(id)arg1;
- (void)handleChangePanGesture:(id)arg1;
- (id)bubbleAttachmentConferenceView;
- (id)bubbleDecryptFailView;
- (id)bubbleAttachmentVideoView;
- (id)bubbleAttachmentCSpaceView;
- (id)bubbleAttachmentCMailView;
- (id)bubbleAttachmentOAView;
- (id)bubbleEmailView;
- (id)bubbleAlipayRedEnvelopView;
- (id)bubbleEnterpriseRedEnvelopView;
- (id)bubbleRedEnvelopView;
- (id)bubbleAttachmentLocationView;
- (id)bubbleAttachmentCRMView;
- (id)bubbleAttachmentCardView;
- (id)bubbleAttachmentLinkView;
- (id)bubbleAttachmentFileView;
- (id)bubbleAttachmentAudioView;
- (id)bubbleAttachmentImageView;
- (id)bubbleAttachmentTextView;
- (id)configAudioUnreadImageView;
- (void)removeAudioUnreadImageView;
- (id)configMaskView;
- (id)configTimesTampLabel;
- (id)configBubbleAttachmentOATitleView;
- (id)configSelectIconView;
- (id)configCellbottomLabel;
- (id)configCellNameView;
- (id)configTimesTampMessageView;
- (id)configNewMessageAnchorView;
- (id)configMessageAvatarView;
- (id)configMessageStatusView;
- (id)configMessageBubbleView;
- (id)configSourceTagView;
- (id)configRefreshView;
- (id)configTagView;
- (void)configLayoutAttributes:(id)arg1;
- (void)configLayoutAttributes:(id)arg1 animation:(_Bool)arg2;
- (void)prepareForReuse;

@end

