//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTMessageToolBarContentView, LWEmoticonPreviewView, LWEmotionScrollView;

@interface DTMessageInputContainerView : UIView
{
    struct CGRect _backupFrame;
    struct CGRect _backupToolBarFrame;
    _Bool _translatedToOriginalFrame;
    DTMessageToolBarContentView *_toolBarContentView;
    LWEmoticonPreviewView *_emotionPreView;
    LWEmotionScrollView *_emotionScrollView;
}

+ (double)originHeight;
+ (double)originYWithParentView:(id)arg1;
+ (id)shareInputContainerView:(struct CGRect)arg1;
@property(retain, nonatomic) LWEmotionScrollView *emotionScrollView; // @synthesize emotionScrollView=_emotionScrollView;
@property(readonly, nonatomic) _Bool translatedToOriginalFrame; // @synthesize translatedToOriginalFrame=_translatedToOriginalFrame;
@property(retain, nonatomic) LWEmoticonPreviewView *emotionPreView; // @synthesize emotionPreView=_emotionPreView;
@property(retain, nonatomic) DTMessageToolBarContentView *toolBarContentView; // @synthesize toolBarContentView=_toolBarContentView;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (_Bool)dealWithEmoTextShouldChangeTextInRange:(struct _NSRange)arg1 text:(id)arg2 dtAt:(id)arg3;
- (void)loadFaceView;
- (void)configureInputContainerView;
- (void)resetInputSubViewsFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)dtLanguageDidChanged:(id)arg1;
- (void)translationToBackupFrame;
- (void)translationToOriginalFrame;
- (_Bool)hasChangeFrame;
- (id)initWithFrame:(struct CGRect)arg1;

@end

