//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIImage;

@interface DTMessageBubbleFileItem : NSObject
{
    long long _fileType;
    NSString *_content;
    NSString *_fileSize;
    UIImage *_iconImage;
    UIImage *_backgroundImage;
}

+ (id)buildDingAttachmentFileWithCSpaceDentry:(id)arg1;
+ (id)buildWithDingLinkModel:(id)arg1;
+ (id)buildWithDing:(id)arg1 backgroundImage:(id)arg2;
+ (id)buildWithMessage:(id)arg1;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(copy, nonatomic) NSString *fileSize; // @synthesize fileSize=_fileSize;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long fileType; // @synthesize fileType=_fileType;
- (void).cxx_destruct;

@end

