//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LIMBizUserIconModel, UIImage;

@interface DTMessageAvatarModel : NSObject
{
    LIMBizUserIconModel *_iconModel;
    UIImage *_iconImage;
}

@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) LIMBizUserIconModel *iconModel; // @synthesize iconModel=_iconModel;
- (void).cxx_destruct;

@end

