//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTMessageBaseHandler.h"

#import "LWEmotionViewDelegate-Protocol.h"

@class NSString;

@interface DTMessageEmotionHandler : DTMessageBaseHandler <LWEmotionViewDelegate>
{
    long long _packageId;
}

@property(nonatomic) long long packageId; // @synthesize packageId=_packageId;
- (void)emotionFavoriteAddPressedEmotionView;
- (void)emotionSettingButtonPressedEmotionView;
- (void)emotionAddButtonPressedEmotionView;
- (void)emotionSendButtonPressedEmotionView:(id)arg1;
- (void)emotionDeleteButtonPressedEmotionView:(id)arg1;
- (void)emotionDidPicked:(long long)arg1 emotionView:(id)arg2;
- (void)emotionDidHighlighted:(long long)arg1 emotionView:(id)arg2;
- (void)switchTab;
- (void)setTabWithPackageId:(long long)arg1;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

