//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTMessageBaseHandler.h"

#import "DTMessageMenuViewDelegate-Protocol.h"

@class DTCustomMenuModel, DTMessageMenuView, NSString;

@interface DTMessageInputCustomMenuHandler : DTMessageBaseHandler <DTMessageMenuViewDelegate>
{
    _Bool _isMenuMode;
    DTCustomMenuModel *_customMenuModel;
    DTMessageMenuView *_menuView;
}

@property(nonatomic) _Bool isMenuMode; // @synthesize isMenuMode=_isMenuMode;
@property(retain, nonatomic) DTMessageMenuView *menuView; // @synthesize menuView=_menuView;
@property(retain, nonatomic) DTCustomMenuModel *customMenuModel; // @synthesize customMenuModel=_customMenuModel;
- (void).cxx_destruct;
- (void)didPressedSwitchButtonOnMenuView:(id)arg1;
- (void)menuView:(id)arg1 didSelectSubmenuAtIndexPath:(id)arg2;
- (void)menuView:(id)arg1 didSelectMenuAtIndex:(long long)arg2;
- (id)menuView:(id)arg1 titlesOfSubmenuForMenuItemAtIndex:(long long)arg2;
- (id)menuView:(id)arg1 titleForMenuItemAtIndex:(long long)arg2;
- (long long)numberOfSectionsInMenuView:(id)arg1;
- (double)setEditBottomMenuViewHidden:(_Bool)arg1 editBottomMenuView:(id)arg2;
- (void)requestForCustomMenu;
- (void)didSelectedButtonMode:(id)arg1;
- (void)showMenuViewWithAnimated:(_Bool)arg1;
- (void)showInputViewWithAnimated:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

