//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class DTMessagePopupActionItem;

@interface DTMessagePopupActionButton : UIButton
{
    DTMessagePopupActionItem *_actionItem;
}

@property(retain, nonatomic) DTMessagePopupActionItem *actionItem; // @synthesize actionItem=_actionItem;
- (void).cxx_destruct;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)backgroundRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;

@end

