//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTBadgeView, UIButton;
@protocol DTMessageToolBarFaceViewDelegate;

@interface DTMessageToolBarFaceView : UIView
{
    _Bool _isActive;
    UIButton *_faceBtn;
    id <DTMessageToolBarFaceViewDelegate> _delegate;
    DTBadgeView *_badgeView;
}

@property(retain, nonatomic) DTBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) __weak id <DTMessageToolBarFaceViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property(retain, nonatomic) UIButton *faceBtn; // @synthesize faceBtn=_faceBtn;
- (void).cxx_destruct;
- (void)face:(id)arg1;
- (void)setFaceBtnImage:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

