//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTMessageBubbleImageItem : NSObject
{
    _Bool _incomming;
    _Bool _ignoreSmallImage;
    _Bool _isGif;
    _Bool _isMagicImage;
    NSString *_cId;
    NSString *_localId;
    NSString *_mediaId;
    long long _dataSize;
    long long _orientation;
    unsigned long long _sendStatus;
    unsigned long long _magicShowType;
    long long _magicEmotionId;
    long long _magicPackageId;
}

+ (id)buildWithMessage:(id)arg1;
@property(nonatomic) long long magicPackageId; // @synthesize magicPackageId=_magicPackageId;
@property(nonatomic) long long magicEmotionId; // @synthesize magicEmotionId=_magicEmotionId;
@property(nonatomic) unsigned long long magicShowType; // @synthesize magicShowType=_magicShowType;
@property(nonatomic) _Bool isMagicImage; // @synthesize isMagicImage=_isMagicImage;
@property(nonatomic) _Bool isGif; // @synthesize isGif=_isGif;
@property(nonatomic) _Bool ignoreSmallImage; // @synthesize ignoreSmallImage=_ignoreSmallImage;
@property(nonatomic) unsigned long long sendStatus; // @synthesize sendStatus=_sendStatus;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) long long dataSize; // @synthesize dataSize=_dataSize;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(nonatomic) _Bool incomming; // @synthesize incomming=_incomming;
@property(copy, nonatomic) NSString *localId; // @synthesize localId=_localId;
@property(copy, nonatomic) NSString *cId; // @synthesize cId=_cId;
- (void).cxx_destruct;

@end

