//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, DACircularProgressView, DTMovieDownloader, DTMoviePlayerFooterView, DTMoviePlayerModel, DTWebImageView, NSDictionary, NSString, NSTimer, UIProgressView;
@protocol DTMoviePlayerViewControllerDelegate;

@interface DTMoviePlayerViewController : DTViewController <UIGestureRecognizerDelegate>
{
    NSTimer *_timer;
    _Bool _isSeeking;
    _Bool _isPlaying;
    _Bool _dismissed;
    _Bool _playedOnce;
    _Bool _longTapped;
    DTMoviePlayerModel *_movieModel;
    DTWebImageView *_bgImageView;
    id <DTMoviePlayerViewControllerDelegate> _delegate;
    NSDictionary *_extensionDict;
    AVPlayerItem *_playerItem;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    UIProgressView *_videoProgress;
    DTMoviePlayerFooterView *_footerView;
    DACircularProgressView *_downProgress;
    DTMovieDownloader *_downloader;
    id _playProgressObserver;
}

@property(nonatomic) _Bool longTapped; // @synthesize longTapped=_longTapped;
@property(retain, nonatomic) id playProgressObserver; // @synthesize playProgressObserver=_playProgressObserver;
@property(retain, nonatomic) DTMovieDownloader *downloader; // @synthesize downloader=_downloader;
@property(retain, nonatomic) DACircularProgressView *downProgress; // @synthesize downProgress=_downProgress;
@property(retain, nonatomic) DTMoviePlayerFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIProgressView *videoProgress; // @synthesize videoProgress=_videoProgress;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) NSDictionary *extensionDict; // @synthesize extensionDict=_extensionDict;
@property(nonatomic) __weak id <DTMoviePlayerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DTWebImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) DTMoviePlayerModel *movieModel; // @synthesize movieModel=_movieModel;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)setProgressWithDuration:(double)arg1;
- (void)downloadVideoSuccess;
- (void)applySeekToPosition:(double)arg1;
- (void)pause;
- (void)play;
- (void)setIsSeeking:(_Bool)arg1;
- (void)setIsPlaying:(_Bool)arg1;
- (void)updatePosition:(_Bool)arg1 forceZero:(_Bool)arg2;
- (void)invalidTimer;
- (void)timerDidFire:(id)arg1;
- (void)startTimer;
- (void)dismiss;
- (double)videoHeight;
- (void)longPressed:(id)arg1;
- (void)tapPressed:(id)arg1;
- (void)rightSwipe:(id)arg1;
- (void)preparePlay;
- (void)playToEndTimeNotification:(id)arg1;
- (void)monitoringPlayProgress:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onAppDidEnterBackground:(id)arg1;
- (void)addAppStatusObservers;
- (void)addObservers;
- (void)setVideoPath:(id)arg1;
- (void)startDownLoadVideo;
- (void)startLoadVideo;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)initWithMovieModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

