//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTNavigationController.h"

@interface DTNavigationController (BarButton)
+ (id)customBarButtonItemsWithTitle1:(id)arg1 badgeView1:(id)arg2 normalColor1:(id)arg3 highlightColor1:(id)arg4 target1:(id)arg5 action1:(SEL)arg6 title2:(id)arg7 badgeView2:(id)arg8 normalColor2:(id)arg9 highlightColor2:(id)arg10 target2:(id)arg11 action2:(SEL)arg12;
+ (id)customBarButtonItemsWithTitle:(id)arg1 badgeView:(id)arg2 normalColor:(id)arg3 highlightColor:(id)arg4 target:(id)arg5 action:(SEL)arg6;
+ (id)customBarButtonItemsWithImage1:(id)arg1 image2:(id)arg2 image3:(id)arg3 highImage1:(id)arg4 highImage2:(id)arg5 highImage3:(id)arg6 target1:(id)arg7 target2:(id)arg8 target3:(id)arg9 action1:(SEL)arg10 action2:(SEL)arg11 action3:(SEL)arg12;
+ (id)customBarButtonItemsWithImage1:(id)arg1 highImage1:(id)arg2 badgeView1:(id)arg3 target1:(id)arg4 action1:(SEL)arg5 image2:(id)arg6 highImage2:(id)arg7 badgeView2:(id)arg8 target2:(id)arg9 action2:(SEL)arg10;
+ (id)customBarButtonItemsWithImage1:(id)arg1 highImage1:(id)arg2 highImage2:(id)arg3 image2:(id)arg4 target1:(id)arg5 target2:(id)arg6 action1:(SEL)arg7 action2:(SEL)arg8;
+ (id)barButtonItemWithTitle:(id)arg1 badgeImage:(id)arg2 target:(id)arg3 action:(SEL)arg4;
+ (id)customBarButtonItemWithImage:(id)arg1 highImage:(id)arg2 target:(id)arg3 action:(SEL)arg4;
+ (id)customBarButtonItemWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)customBarButtonItemWithIconFont:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)barButtonItemWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)barButtonItemWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (void)configBackBarButtonItem:(id)arg1 withTitle:(id)arg2 tintColor:(id)arg3;
+ (id)backBarButtonItemWithTitle:(id)arg1 tintColor:(id)arg2 titleColor:(id)arg3 target:(id)arg4 action:(SEL)arg5;
+ (id)backBarButtonItemWithTitle:(id)arg1 tintColor:(id)arg2 target:(id)arg3 action:(SEL)arg4;
+ (id)backBarButtonItemWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)iconfontWithSize:(double)arg1;
+ (id)indicatorFont;
+ (id)barTitleFont;
@end

