//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTNewMessageNotificationViewController;

@interface DTNotificationSoundSettingObserver : NSObject
{
    _Bool _shouldSaveSettings;
    DTNewMessageNotificationViewController *_controller;
}

@property(nonatomic) _Bool shouldSaveSettings; // @synthesize shouldSaveSettings=_shouldSaveSettings;
@property(nonatomic) __weak DTNewMessageNotificationViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)dealloc;
- (void)willResignActive:(id)arg1;
- (void)applyUpdateCloudSettings;
- (id)initWithController:(id)arg1;

@end

