//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTOANotifyPushModel : Marshal
{
    NSString *_notifyId;
    NSString *_icon;
    NSString *_title;
    NSString *_content;
    NSString *_url;
    NSNumber *_audio;
}

@property(retain, nonatomic) NSNumber *audio; // @synthesize audio=_audio;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *notifyId; // @synthesize notifyId=_notifyId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

