//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSNumber, NSString;

@interface DTOACheckInLocModel : Marshal
{
    NSNumber *_lat;
    NSNumber *_lon;
    NSNumber *_accuracy;
    NSArray *_wifiList;
    NSNumber *_planId;
    NSString *_corpId;
    NSString *_deviceId;
}

@property(copy, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
@property(retain, nonatomic) NSNumber *planId; // @synthesize planId=_planId;
@property(copy, nonatomic) NSArray *wifiList; // @synthesize wifiList=_wifiList;
@property(retain, nonatomic) NSNumber *accuracy; // @synthesize accuracy=_accuracy;
@property(retain, nonatomic) NSNumber *lon; // @synthesize lon=_lon;
@property(retain, nonatomic) NSNumber *lat; // @synthesize lat=_lat;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

