//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class DTOrgEmpSettingModel, DTOrgEmployeeModel, DTOrganizationModel, NSArray, NSDate, NSNumber, NSString;

@interface DTOrgEmployeeExtensionModel : Marshal
{
    _Bool _isOrgAuth;
    _Bool _isAdmin;
    DTOrgEmployeeModel *_orgEmployeeModel;
    NSString *_extNumber;
    NSDate *_employDate;
    NSString *_orgWorkAddress;
    NSArray *_orgExtPropertyList;
    NSArray *_orgNodeItemList;
    DTOrganizationModel *_orgDetail;
    NSNumber *_spaceId;
    NSNumber *_orgLevel;
    DTOrgEmpSettingModel *_empSettingModel;
}

@property(retain, nonatomic) DTOrgEmpSettingModel *empSettingModel; // @synthesize empSettingModel=_empSettingModel;
@property(retain, nonatomic) NSNumber *orgLevel; // @synthesize orgLevel=_orgLevel;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
@property(retain, nonatomic) NSNumber *spaceId; // @synthesize spaceId=_spaceId;
@property(retain, nonatomic) DTOrganizationModel *orgDetail; // @synthesize orgDetail=_orgDetail;
@property(copy, nonatomic) NSArray *orgNodeItemList; // @synthesize orgNodeItemList=_orgNodeItemList;
@property(copy, nonatomic) NSArray *orgExtPropertyList; // @synthesize orgExtPropertyList=_orgExtPropertyList;
@property(nonatomic) _Bool isOrgAuth; // @synthesize isOrgAuth=_isOrgAuth;
@property(copy, nonatomic) NSString *orgWorkAddress; // @synthesize orgWorkAddress=_orgWorkAddress;
@property(retain, nonatomic) NSDate *employDate; // @synthesize employDate=_employDate;
@property(copy, nonatomic) NSString *extNumber; // @synthesize extNumber=_extNumber;
@property(retain, nonatomic) DTOrgEmployeeModel *orgEmployeeModel; // @synthesize orgEmployeeModel=_orgEmployeeModel;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

