//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class DTALocationManager, DTAddMemberHandler, DTButtonView, DTRegion, DTTeamCreation, DTTeamDepartment, NSArray, NSString;

@interface DTOrgEasyOperatingViewController : DTTableViewController
{
    _Bool _limited;
    _Bool _isFastCreate;
    _Bool _exitToRootVC;
    _Bool _isCreateExperienceTeamWhenQuit;
    _Bool _support40Service;
    _Bool _needAutoLocate;
    _Bool _needResentRequest;
    _Bool _isRequesting;
    _Bool _isLocating;
    _Bool _hasLocationChecked;
    DTRegion *_selectedRegion;
    long long _orgId;
    NSString *_inviteCode;
    NSString *_redirectUrl;
    unsigned long long _from;
    DTButtonView *_createBtn;
    long long _tableViewHeight;
    DTAddMemberHandler *_addMemberHandler;
    DTTeamCreation *_team;
    DTTeamDepartment *_dept;
    NSArray *_freshMembers;
    double _delaySeconds;
    unsigned long long _delayTimes;
    NSString *_tempIndustryDesc;
    NSString *_support40ServiceProvince;
    NSString *_support40ServiceCity;
    DTALocationManager *_locationManager;
}

@property(retain, nonatomic) DTALocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) _Bool hasLocationChecked; // @synthesize hasLocationChecked=_hasLocationChecked;
@property(nonatomic) _Bool isLocating; // @synthesize isLocating=_isLocating;
@property(nonatomic) _Bool isRequesting; // @synthesize isRequesting=_isRequesting;
@property(nonatomic) _Bool needResentRequest; // @synthesize needResentRequest=_needResentRequest;
@property(nonatomic) _Bool needAutoLocate; // @synthesize needAutoLocate=_needAutoLocate;
@property(copy, nonatomic) NSString *support40ServiceCity; // @synthesize support40ServiceCity=_support40ServiceCity;
@property(copy, nonatomic) NSString *support40ServiceProvince; // @synthesize support40ServiceProvince=_support40ServiceProvince;
@property(nonatomic) _Bool support40Service; // @synthesize support40Service=_support40Service;
@property(nonatomic) _Bool isCreateExperienceTeamWhenQuit; // @synthesize isCreateExperienceTeamWhenQuit=_isCreateExperienceTeamWhenQuit;
@property(copy, nonatomic) NSString *tempIndustryDesc; // @synthesize tempIndustryDesc=_tempIndustryDesc;
@property(nonatomic) unsigned long long delayTimes; // @synthesize delayTimes=_delayTimes;
@property(nonatomic) double delaySeconds; // @synthesize delaySeconds=_delaySeconds;
@property(copy, nonatomic) NSArray *freshMembers; // @synthesize freshMembers=_freshMembers;
@property(retain, nonatomic) DTTeamDepartment *dept; // @synthesize dept=_dept;
@property(retain, nonatomic) DTTeamCreation *team; // @synthesize team=_team;
@property(retain, nonatomic) DTAddMemberHandler *addMemberHandler; // @synthesize addMemberHandler=_addMemberHandler;
@property(nonatomic) long long tableViewHeight; // @synthesize tableViewHeight=_tableViewHeight;
@property(retain, nonatomic) DTButtonView *createBtn; // @synthesize createBtn=_createBtn;
@property(nonatomic) unsigned long long from; // @synthesize from=_from;
@property(nonatomic) _Bool exitToRootVC; // @synthesize exitToRootVC=_exitToRootVC;
@property(nonatomic) _Bool isFastCreate; // @synthesize isFastCreate=_isFastCreate;
@property(copy, nonatomic) NSString *redirectUrl; // @synthesize redirectUrl=_redirectUrl;
@property(copy, nonatomic) NSString *inviteCode; // @synthesize inviteCode=_inviteCode;
@property(nonatomic) _Bool limited; // @synthesize limited=_limited;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
- (void).cxx_destruct;
- (void)autoLocation:(CDUnknownBlockType)arg1;
- (void)popBack;
- (void)quit;
- (_Bool)isNeedToShowRecommendExperienceTeam;
- (void)teamDetail;
- (void)redirectToAuthorizationUrlWithCorpId:(id)arg1;
- (void)gotoSuccess:(long long)arg1 corpId:(id)arg2;
- (void)gotoAuthorization:(id)arg1;
- (void)goto40Service:(long long)arg1;
- (void)createOrganizationDidSuccess:(long long)arg1;
- (_Bool)isISV;
- (void)dealWithManageOrg:(long long)arg1;
- (void)dealWithCreateOrg:(long long)arg1 userRightsLevel:(unsigned long long)arg2;
- (void)manageOrg:(id)arg1;
- (_Bool)isCustomIndustryEmpty;
- (void)pickCityOfTeam:(id)arg1;
- (void)pickIndustry;
- (void)pickEmployee;
- (id)teamMemberLimitedTip;
- (id)teamMemberCountTip;
- (unsigned long long)leastMemberCount;
- (void)handler40ServerRequest;
@property(retain, nonatomic) DTRegion *selectedRegion; // @synthesize selectedRegion=_selectedRegion;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)loadDataSource;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

