//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "DTMobileInputViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class DTAvatarImageView, DTButton, DTContact, DTJob, DTMobileInputView, NSString, UIButton, UIImageView, UILabel, UIScrollView, UITextField, UIView;

@interface DTPasswordInputViewController : DTViewController <UITextFieldDelegate, DTMobileInputViewDelegate, UIAlertViewDelegate, UIActionSheetDelegate>
{
    _Bool _hasPrivacyPolicy;
    _Bool _viewWillDisAppear;
    int _errorCount;
    DTJob *_job;
    NSString *_headerTitle;
    NSString *_countryCode;
    NSString *_countryName;
    UILabel *_countryCodeLabel;
    UIImageView *_countrySelectImageView;
    UILabel *_passwordLabel;
    UIImageView *_labelDivideLine;
    DTButton *_countryCodeButton;
    DTMobileInputView *_mobileInput;
    DTButton *_nextButton;
    UIButton *_reportLossButton;
    UILabel *_protocolLable;
    DTButton *_protocolButton;
    UITextField *_passwordTextField;
    UIScrollView *_sclView;
    UIButton *_loginProblemButton;
    UIButton *_freshUserButton;
    DTButton *_environmentButton;
    DTAvatarImageView *_avatar;
    DTContact *_contact;
    NSString *_lastInputMobile;
    UIView *_temView;
    UIImageView *_backgroundImage;
    UIImageView *_firstDivideLine;
}

@property(retain, nonatomic) UIImageView *firstDivideLine; // @synthesize firstDivideLine=_firstDivideLine;
@property(retain, nonatomic) UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIView *temView; // @synthesize temView=_temView;
@property(copy, nonatomic) NSString *lastInputMobile; // @synthesize lastInputMobile=_lastInputMobile;
@property(nonatomic) _Bool viewWillDisAppear; // @synthesize viewWillDisAppear=_viewWillDisAppear;
@property(nonatomic) int errorCount; // @synthesize errorCount=_errorCount;
@property(retain, nonatomic) DTContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) DTAvatarImageView *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) DTButton *environmentButton; // @synthesize environmentButton=_environmentButton;
@property(retain, nonatomic) UIButton *freshUserButton; // @synthesize freshUserButton=_freshUserButton;
@property(retain, nonatomic) UIButton *loginProblemButton; // @synthesize loginProblemButton=_loginProblemButton;
@property(retain, nonatomic) UIScrollView *sclView; // @synthesize sclView=_sclView;
@property(retain, nonatomic) UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) DTButton *protocolButton; // @synthesize protocolButton=_protocolButton;
@property(retain, nonatomic) UILabel *protocolLable; // @synthesize protocolLable=_protocolLable;
@property(retain, nonatomic) UIButton *reportLossButton; // @synthesize reportLossButton=_reportLossButton;
@property(retain, nonatomic) DTButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) DTMobileInputView *mobileInput; // @synthesize mobileInput=_mobileInput;
@property(retain, nonatomic) DTButton *countryCodeButton; // @synthesize countryCodeButton=_countryCodeButton;
@property(retain, nonatomic) UIImageView *labelDivideLine; // @synthesize labelDivideLine=_labelDivideLine;
@property(retain, nonatomic) UILabel *passwordLabel; // @synthesize passwordLabel=_passwordLabel;
@property(retain, nonatomic) UIImageView *countrySelectImageView; // @synthesize countrySelectImageView=_countrySelectImageView;
@property(retain, nonatomic) UILabel *countryCodeLabel; // @synthesize countryCodeLabel=_countryCodeLabel;
@property(copy, nonatomic) NSString *countryName; // @synthesize countryName=_countryName;
@property(copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic) _Bool hasPrivacyPolicy; // @synthesize hasPrivacyPolicy=_hasPrivacyPolicy;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) DTJob *job; // @synthesize job=_job;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)checkAvatarWithMobile:(id)arg1;
- (_Bool)isShowResetPswtAlertView:(long long)arg1;
- (id)getCountryName;
- (void)checkMobileInputFormatter:(id)arg1;
- (id)getMobileInputViewController;
- (void)showErrorMsg:(id)arg1;
- (void)freshUserButtonClick:(id)arg1;
- (void)loginProblemButtonClick:(id)arg1;
- (void)countryCodeButtonAction:(id)arg1;
- (void)reportLoginFailedError:(id)arg1;
- (void)nextButtonAction:(id)arg1;
- (void)reportLossButtonAction;
- (void)showMoreMenu:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)phoneNumberInputDidChanged:(id)arg1;
- (void)dealloc;
- (struct CGSize)getSizeFromString:(id)arg1;
- (void)handleWillChangeKeyboardFrame:(id)arg1;
- (void)activePassWordInput;
- (void)hideKeyBoard;
- (void)didReceiveMemoryWarning;
- (void)loadComponents;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)defaultCountryCode;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

