//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTPushHandlerProtocol-Protocol.h"

@class NSString;

@interface DTPushDingHandler : NSObject <DTPushHandlerProtocol>
{
}

- (void)handleDeadlineFinishStatusChange:(id)arg1;
- (void)handleGuideLayerModel:(id)arg1;
- (void)configRedDotDing:(id)arg1 andPushComment:(id)arg2;
- (void)handleCommentNofityStatusChanged:(id)arg1;
- (void)handleDingConfirmStatusChange:(id)arg1;
- (void)handelDingNewSent:(id)arg1;
- (void)handleDingSendStatus:(id)arg1;
- (void)handelUserDingStatus:(id)arg1;
- (_Bool)handelDingQuto:(id)arg1;
- (_Bool)handleDingCommentCreated:(id)arg1;
- (_Bool)handleFinishDing:(id)arg1;
- (_Bool)handleSelfConfirmDing:(id)arg1;
- (_Bool)handleReceiverConfirmDing:(id)arg1;
- (_Bool)handleCreateDing:(id)arg1 againDing:(_Bool)arg2;
- (void)pushCaught:(id)arg1 error:(id)arg2;
- (id)convertData:(id)arg1 toObjectWithClazz:(Class)arg2;
- (void)pushReceived:(id)arg1 value:(id)arg2;
- (Class)returnedValueClass;
- (id)topicName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

