//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTQrcodeIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)bindV2:(id)arg1 umidToken:(id)arg2 callback:(id)arg3;
- (void)bind:(id)arg1 callback:(id)arg2;

@end

