//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTRegionFile : NSObject
{
    NSString *_regionKey;
    NSString *_fileName;
}

+ (id)regionCodeFileForSelectLanguage:(unsigned long long)arg1;
+ (id)regionFileForSelectLanguage:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *regionKey; // @synthesize regionKey=_regionKey;
- (void).cxx_destruct;

@end

