//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTRedEnvelopServiceNetworkProtocol-Protocol.h"

@class NSString;

@interface DTRedEnvelopServiceNetworkIMP : NSObject <DTRedEnvelopServiceNetworkProtocol>
{
}

- (void)alipayAuthSign:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)alipaySign:(id)arg1 signType:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)queryAcquireResult:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)getBindAlipaySuccessBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (void)unbindAlipaySuccessBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (void)bindAlipay:(id)arg1 authCode:(id)arg2 signString:(id)arg3 signType:(id)arg4 successBlock:(CDUnknownBlockType)arg5 failureBlock:(CDUnknownBlockType)arg6;
- (void)fetchBalanceSuccessBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (void)queryRedEnvelopCluster:(long long)arg1 clusterId:(id)arg2 startTime:(long long)arg3 size:(int)arg4 flowId:(long long)arg5 successBlock:(CDUnknownBlockType)arg6 failureBlock:(CDUnknownBlockType)arg7;
- (void)queryReceivedRedEnvelops:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)querySentRedEnvelopClusters:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)leaveMessageToRedEnvelopFlow:(long long)arg1 clusterId:(id)arg2 flowId:(int)arg3 leaveMessage:(id)arg4 successBlock:(CDUnknownBlockType)arg5 failureBlock:(CDUnknownBlockType)arg6;
- (void)pickRedEnvelopCluster:(long long)arg1 clusterId:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)checkRedEnvelopClusterPickingStatus:(long long)arg1 clusterId:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)generateRedEnvelopClusterV2:(long long)arg1 clusterId:(id)arg2 amount:(id)arg3 size:(int)arg4 receivers:(id)arg5 type:(long long)arg6 cid:(id)arg7 congratulations:(id)arg8 oid:(long long)arg9 redEnvelopeSubscribeLifecycleModel:(id)arg10 signString:(id)arg11 signType:(id)arg12 successBlock:(CDUnknownBlockType)arg13 failureBlock:(CDUnknownBlockType)arg14;
- (void)generateRedEnvelopCluster:(long long)arg1 clusterId:(id)arg2 amount:(id)arg3 size:(int)arg4 receivers:(id)arg5 type:(long long)arg6 cid:(id)arg7 congratulations:(id)arg8 oid:(long long)arg9 signString:(id)arg10 signType:(id)arg11 successBlock:(CDUnknownBlockType)arg12 failureBlock:(CDUnknownBlockType)arg13;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

