//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTRedEnvelopRecordModel, DTRedEnvelopeSubscribeLifecycleModel, NSArray, NSDictionary, NSString;
@protocol DTRedEnvelopServiceNetworkProtocol, DTRedEnvelopServicePersistenceProtocol;

@protocol DTRedEnvelopServiceProtocol <NSObject>
@property(retain, nonatomic) id <DTRedEnvelopServiceNetworkProtocol> networkIMP;
@property(retain, nonatomic) id <DTRedEnvelopServicePersistenceProtocol> persistenceIMP;
- (NSArray *)unsendRedenvelopRecordInConversationId:(NSString *)arg1;
- (_Bool)clearRedenvelopRecordInConversationId:(NSString *)arg1;
- (DTRedEnvelopRecordModel *)redEnvelopRecordWithBusinessId:(NSString *)arg1;
- (_Bool)saveRedEnvelopRecord:(DTRedEnvelopRecordModel *)arg1;
- (_Bool)verifierAuthResult:(NSDictionary *)arg1 openId:(id *)arg2 authCode:(id *)arg3;
- (_Bool)verifierAliPayResult:(NSDictionary *)arg1 redEnvelopRecord:(id *)arg2;
- (void)alipayAuthSign:(NSString *)arg1 successBlock:(void (^)(NSString *))arg2 failureBlock:(void (^)(DTError *))arg3;
- (void)alipaySign:(NSString *)arg1 signType:(NSString *)arg2 successBlock:(void (^)(NSString *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)queryAcquireResult:(NSString *)arg1 successBlock:(void (^)(DTAcquireResultModel *))arg2 failureBlock:(void (^)(DTError *))arg3;
- (void)getBindAlipaySuccessBlock:(void (^)(NSString *))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)unbindAlipaySuccessBlock:(void (^)(void))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)bindAlipay:(NSString *)arg1 authCode:(NSString *)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)fetchBalanceSuccessBlock:(void (^)(NSString *))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)queryRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 startTime:(long long)arg3 size:(int)arg4 flowId:(long long)arg5 successBlock:(void (^)(DTBizRedEnvelopClusterDetail *))arg6 failureBlock:(void (^)(DTError *))arg7;
- (void)queryReceivedRedEnvelops:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(void (^)(DTBizRedEnvelopReceivedList *))arg4 failureBlock:(void (^)(DTError *))arg5;
- (void)querySentRedEnvelopClusters:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(void (^)(DTBizRedEnvelopClusterSentList *))arg4 failureBlock:(void (^)(DTError *))arg5;
- (void)leaveMessageToRedEnvelopFlow:(long long)arg1 clusterId:(NSString *)arg2 flowId:(int)arg3 leaveMessage:(NSString *)arg4 successBlock:(void (^)(void))arg5 failureBlock:(void (^)(DTError *))arg6;
- (void)pickRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 successBlock:(void (^)(DTBizRedEnvelopClusterPickingStatus *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)checkRedEnvelopClusterPickingStatus:(long long)arg1 clusterId:(NSString *)arg2 successBlock:(void (^)(DTBizRedEnvelopClusterPickingStatus *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)generateRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 amount:(NSString *)arg3 size:(int)arg4 receivers:(NSArray *)arg5 type:(long long)arg6 cid:(NSString *)arg7 congratulations:(NSString *)arg8 oid:(long long)arg9 redEnvelopeSubscribeLifecycleModel:(DTRedEnvelopeSubscribeLifecycleModel *)arg10 successBlock:(void (^)(DTBizRedEnvelopCluster *))arg11 failureBlock:(void (^)(DTError *))arg12;
- (void)sendInitAlipay;
- (NSString *)getBindAlipayAccount;
- (NSString *)generateClusterId;
@end

