//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIColor, UIImage;

@interface DTScrollMenuViewItem : NSObject
{
    _Bool _hiddenTitle;
    _Bool _enable;
    _Bool _enableReddot;
    UIImage *_icon;
    NSString *_title;
    NSString *_url;
    double _fontSize;
    double _iconTopMargin;
    double _labelToIconMargin;
    UIColor *_backgroundColor;
    CDUnknownBlockType _action;
    struct CGSize _iconSize;
}

+ (id)buildWithIconImage:(id)arg1 url:(id)arg2 title:(id)arg3 hiddenTitle:(_Bool)arg4 iconSize:(struct CGSize)arg5 fontSize:(double)arg6 iconTopMargin:(double)arg7 labelToIconMargin:(double)arg8 backgroundColor:(id)arg9 enableReddot:(_Bool)arg10 action:(CDUnknownBlockType)arg11;
+ (id)buildWithIconImage:(id)arg1 url:(id)arg2 title:(id)arg3 hiddenTitle:(_Bool)arg4 iconSize:(struct CGSize)arg5 fontSize:(double)arg6 iconTopMargin:(double)arg7 labelToIconMargin:(double)arg8 backgroundColor:(id)arg9 action:(CDUnknownBlockType)arg10;
+ (id)buildWithIconImage:(id)arg1 url:(id)arg2 title:(id)arg3 hiddenTitle:(_Bool)arg4 iconSize:(struct CGSize)arg5 fontSize:(double)arg6 iconTopMargin:(double)arg7 labelToIconMargin:(double)arg8 action:(CDUnknownBlockType)arg9;
+ (id)buildWithIconImage:(id)arg1 url:(id)arg2 title:(id)arg3 hiddenTitle:(_Bool)arg4 iconSize:(struct CGSize)arg5 fontSize:(double)arg6 action:(CDUnknownBlockType)arg7;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(nonatomic) _Bool enableReddot; // @synthesize enableReddot=_enableReddot;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double labelToIconMargin; // @synthesize labelToIconMargin=_labelToIconMargin;
@property(nonatomic) double iconTopMargin; // @synthesize iconTopMargin=_iconTopMargin;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize=_iconSize;
@property(nonatomic) _Bool hiddenTitle; // @synthesize hiddenTitle=_hiddenTitle;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;

@end

