//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactBaseViewController.h"

#import "DTLoadMoreDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTEmptyResultView, DTLoadMoreController, DTTableLoadingView, NSArray, NSOrderedSet, NSString, UITableView;

@interface DTSearchUserViewController : DTContactBaseViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UISearchDisplayDelegate, DTLoadMoreDelegate>
{
    _Bool _noMoreAlias;
    _Bool _noMoreUsualContact;
    _Bool _noMoreFriend;
    _Bool _noMoreLocalColleague;
    _Bool _noMoreMobileContact;
    _Bool _noMoreColleague;
    NSString *_searchText;
    NSArray *_preResults;
    unsigned long long _searchModel;
    CDUnknownBlockType _userDidPickedBlock;
    UITableView *_tableView;
    NSArray *_datasource;
    NSOrderedSet *_validUidSet;
    DTLoadMoreController *_loadMoreController;
    DTEmptyResultView *_searchEmptyView;
    DTTableLoadingView *_loadingView;
    long long _startForMoreAlias;
    long long _startForMoreUsualContact;
    long long _startForMoreFriend;
    long long _startForMoreLocalColleague;
    long long _startForMoreMobileContact;
    long long _startForMoreColleague;
}

@property(nonatomic) long long startForMoreColleague; // @synthesize startForMoreColleague=_startForMoreColleague;
@property(nonatomic) long long startForMoreMobileContact; // @synthesize startForMoreMobileContact=_startForMoreMobileContact;
@property(nonatomic) long long startForMoreLocalColleague; // @synthesize startForMoreLocalColleague=_startForMoreLocalColleague;
@property(nonatomic) long long startForMoreFriend; // @synthesize startForMoreFriend=_startForMoreFriend;
@property(nonatomic) long long startForMoreUsualContact; // @synthesize startForMoreUsualContact=_startForMoreUsualContact;
@property(nonatomic) long long startForMoreAlias; // @synthesize startForMoreAlias=_startForMoreAlias;
@property(nonatomic) _Bool noMoreColleague; // @synthesize noMoreColleague=_noMoreColleague;
@property(nonatomic) _Bool noMoreMobileContact; // @synthesize noMoreMobileContact=_noMoreMobileContact;
@property(nonatomic) _Bool noMoreLocalColleague; // @synthesize noMoreLocalColleague=_noMoreLocalColleague;
@property(nonatomic) _Bool noMoreFriend; // @synthesize noMoreFriend=_noMoreFriend;
@property(nonatomic) _Bool noMoreUsualContact; // @synthesize noMoreUsualContact=_noMoreUsualContact;
@property(nonatomic) _Bool noMoreAlias; // @synthesize noMoreAlias=_noMoreAlias;
@property(retain, nonatomic) DTTableLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) DTEmptyResultView *searchEmptyView; // @synthesize searchEmptyView=_searchEmptyView;
@property(retain, nonatomic) DTLoadMoreController *loadMoreController; // @synthesize loadMoreController=_loadMoreController;
@property(copy, nonatomic) NSOrderedSet *validUidSet; // @synthesize validUidSet=_validUidSet;
@property(copy, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType userDidPickedBlock; // @synthesize userDidPickedBlock=_userDidPickedBlock;
@property(nonatomic) unsigned long long searchModel; // @synthesize searchModel=_searchModel;
@property(copy, nonatomic) NSArray *preResults; // @synthesize preResults=_preResults;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void).cxx_destruct;
- (void)createUidWithPhone:(id)arg1 successBlock:(CDUnknownBlockType)arg2;
- (void)dt_openConferenceWithUid:(long long)arg1 phone:(id)arg2 name:(id)arg3;
- (void)openConferenceWithUid:(long long)arg1 phone:(id)arg2 name:(id)arg3;
- (void)openOTOConversationWithUid:(long long)arg1 name:(id)arg2;
- (void)openMessageWithUid:(long long)arg1 phone:(id)arg2 name:(id)arg3;
- (void)showsMoreSearchResultOfDingWithSearchText:(id)arg1;
- (void)showsMoreSearchResultOfChatWithSearchText:(id)arg1 uid:(long long)arg2;
- (void)showsContactInfoWithMobileContact:(id)arg1 uid:(long long)arg2;
- (void)showsContactInfoWithRelation:(id)arg1;
- (void)showsContactInfoWithMobileContact:(id)arg1 searchText:(id)arg2;
- (void)showsContactInfoWithUID:(long long)arg1 item:(id)arg2 searchText:(id)arg3;
- (id)showsEnterpriseCardResults:(id)arg1 searchText:(id)arg2;
- (id)showsMobileContacts:(id)arg1 searchText:(id)arg2;
- (id)showsFriends:(id)arg1 searchText:(id)arg2;
- (id)showUsualContacts:(id)arg1 searchText:(id)arg2;
- (id)showsAliasContacts:(id)arg1 searchText:(id)arg2;
- (void)colleagueListWithSearchText:(id)arg1 datasource:(id)arg2 validUidSet:(id)arg3 originalCount:(unsigned long long)arg4 complete:(CDUnknownBlockType)arg5;
- (void)userListWithSearchText:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (id)uidsOfEnterpriseCards:(id)arg1;
- (id)uidsOfUsualContacts:(id)arg1;
- (id)uidsOfContacts:(id)arg1;
- (void)searchUserWithSearchText:(id)arg1;
- (void)loadMoreControllerWillBeginLoading:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)loadDataSource;
- (void)loadComponent;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

