//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactBaseViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UILabel, UITextField;

@interface DTSendFriendRequestViewController : DTContactBaseViewController <UITextFieldDelegate>
{
    _Bool _isSendingFriendRequest;
    long long _uid;
    unsigned long long _source;
    NSString *_conversationTitle;
    CDUnknownBlockType _sendDidFinish;
    UITextField *_mobileInputField;
    UILabel *_label;
}

@property(nonatomic) _Bool isSendingFriendRequest; // @synthesize isSendingFriendRequest=_isSendingFriendRequest;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UITextField *mobileInputField; // @synthesize mobileInputField=_mobileInputField;
@property(copy, nonatomic) CDUnknownBlockType sendDidFinish; // @synthesize sendDidFinish=_sendDidFinish;
@property(copy, nonatomic) NSString *conversationTitle; // @synthesize conversationTitle=_conversationTitle;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)confirmButtonPressed:(id)arg1;
- (_Bool)messageIsValid:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)textFieldDidValueChanged:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

