//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTShareShortenAdpater, NSMutableArray, NSString, UIButton, UIColor, UILabel, UIViewController, UTShareContent;

@interface DTSharePopupMenuView : UIView
{
    _Bool _isShowing;
    NSString *_topTitle;
    UIColor *_mainBackgroundColor;
    UIColor *_defaultMenuItemColor;
    long long _channelStyle;
    long long _operateStyle;
    UIViewController *_viewController;
    CDUnknownBlockType _clickSuccessBlock;
    CDUnknownBlockType _clickFailureBlock;
    CDUnknownBlockType _cancelBlock;
    UTShareContent *_shareContent;
    NSString *_pageOriginalURL;
    UIButton *_backgroundButton;
    UILabel *_topTitleLabel;
    UIView *_containerView;
    UIView *_dividingLine;
    UIButton *_cancelButton;
    NSMutableArray *_channelArray;
    NSMutableArray *_operateArray;
    DTShareShortenAdpater *_shortURLAdpater;
}

@property(retain, nonatomic) DTShareShortenAdpater *shortURLAdpater; // @synthesize shortURLAdpater=_shortURLAdpater;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(copy, nonatomic) NSMutableArray *operateArray; // @synthesize operateArray=_operateArray;
@property(copy, nonatomic) NSMutableArray *channelArray; // @synthesize channelArray=_channelArray;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *dividingLine; // @synthesize dividingLine=_dividingLine;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UILabel *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
@property(retain, nonatomic) UIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(copy, nonatomic) NSString *pageOriginalURL; // @synthesize pageOriginalURL=_pageOriginalURL;
@property(retain, nonatomic) UTShareContent *shareContent; // @synthesize shareContent=_shareContent;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType clickFailureBlock; // @synthesize clickFailureBlock=_clickFailureBlock;
@property(copy, nonatomic) CDUnknownBlockType clickSuccessBlock; // @synthesize clickSuccessBlock=_clickSuccessBlock;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) long long operateStyle; // @synthesize operateStyle=_operateStyle;
@property(nonatomic) long long channelStyle; // @synthesize channelStyle=_channelStyle;
@property(retain, nonatomic) UIColor *defaultMenuItemColor; // @synthesize defaultMenuItemColor=_defaultMenuItemColor;
@property(retain, nonatomic) UIColor *mainBackgroundColor; // @synthesize mainBackgroundColor=_mainBackgroundColor;
@property(copy, nonatomic) NSString *topTitle; // @synthesize topTitle=_topTitle;
- (void).cxx_destruct;
- (void)showTipWithMessage:(id)arg1;
- (void)swipeHandler:(id)arg1;
- (void)dismissWithAnimation:(_Bool)arg1;
- (void)showInView:(id)arg1 animation:(_Bool)arg2;
- (long long)convertShareType:(int)arg1;
- (void)shareToThirdPartyPlatform:(int)arg1;
- (void)saveImage:(id)arg1;
- (void)addToConfInvite:(id)arg1;
- (void)addToFavorite:(id)arg1;
- (void)refreshLink:(id)arg1;
- (void)copyLink:(id)arg1;
- (void)shareToSafari:(id)arg1;
- (void)shareToSMS:(id)arg1;
- (void)shareToSina:(id)arg1;
- (void)shareToAlipayTimeline:(id)arg1;
- (void)shareToAlipaySession:(id)arg1;
- (void)shareToWeixinFeed:(id)arg1;
- (void)shareToWeixinFriend:(id)arg1;
- (void)shareToDingFriend:(id)arg1;
- (void)cancelButtonClicked:(id)arg1;
- (void)backgroundButtonPressed:(id)arg1;
- (void)configureOperateArray;
- (void)configureChannelArray;
- (void)onActionButtonClick:(id)arg1;
- (void)configureScrollView;
- (void)addGesture;
- (void)configurePopupMenuView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

