//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTSingleCallVoIPServiceProtocol-Protocol.h"

@class NSString, NSTimer;

@interface DTSingleCallVoIPServiceIMP : NSObject <DTSingleCallVoIPServiceProtocol>
{
    _Bool _isSpeakStatus;
    _Bool _isPlaying;
    _Bool _voipCalling;
    CDUnknownBlockType _singleCallVoIPEventHandle;
    CDUnknownBlockType _singleCallVoIPDurationHandle;
    CDUnknownBlockType _singleCallVoIPStatusHandle;
    CDUnknownBlockType _singleCallVoIPLowVolumeHandle;
    unsigned long long _state;
    NSString *_callId;
    NSString *_rejectCallId;
    NSTimer *_vibrateTimer;
}

@property(retain, nonatomic) NSTimer *vibrateTimer; // @synthesize vibrateTimer=_vibrateTimer;
@property(copy, nonatomic) NSString *rejectCallId; // @synthesize rejectCallId=_rejectCallId;
@property(copy, nonatomic) NSString *callId; // @synthesize callId=_callId;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic, getter=isVoIPCalling) _Bool voipCalling; // @synthesize voipCalling=_voipCalling;
@property(copy, nonatomic) CDUnknownBlockType singleCallVoIPLowVolumeHandle; // @synthesize singleCallVoIPLowVolumeHandle=_singleCallVoIPLowVolumeHandle;
@property(copy, nonatomic) CDUnknownBlockType singleCallVoIPStatusHandle; // @synthesize singleCallVoIPStatusHandle=_singleCallVoIPStatusHandle;
@property(copy, nonatomic) CDUnknownBlockType singleCallVoIPDurationHandle; // @synthesize singleCallVoIPDurationHandle=_singleCallVoIPDurationHandle;
@property(copy, nonatomic) CDUnknownBlockType singleCallVoIPEventHandle; // @synthesize singleCallVoIPEventHandle=_singleCallVoIPEventHandle;
- (void).cxx_destruct;
- (void)checkDevicePermissionWithBlock:(CDUnknownBlockType)arg1;
- (id)stringFromTimeInterval:(double)arg1;
- (id)localVideoRenderView;
- (id)remoteVideoRenderView;
- (void)onStartMedia:(id)arg1;
- (void)onLWPStatus:(id)arg1;
- (void)onVoIPSessionState:(id)arg1 timeCost:(int)arg2 kbpsCost:(int)arg3;
- (void)onTransportIntensitLocalLevel:(int)arg1 remoteLevel:(int)arg2;
- (void)onVoIPDebug:(id)arg1 type:(unsigned long long)arg2;
- (void)onSwitchToAudio:(id)arg1;
- (void)onHungup:(id)arg1 error:(unsigned long long)arg2 info:(id)arg3 remoteOpenId:(id)arg4;
- (void)onAcceptWithCallId:(id)arg1 type:(unsigned long long)arg2 remoteOpenId:(id)arg3 remoteVideoEnabled:(_Bool)arg4;
- (void)onReceiveRingWithCallId:(id)arg1 extraMsg:(id)arg2 remoteOpenId:(id)arg3;
- (void)onAlertingWitCallId:(id)arg1 openId:(id)arg2 type:(unsigned long long)arg3 extraMsg:(id)arg4;
- (void)onMakeCallReadyWichCallID:(id)arg1 remoteOpenId:(id)arg2;
- (void)onErrorOccur:(unsigned long long)arg1 errorInfo:(id)arg2;
- (void)receiveVoIPMessage:(id)arg1 callId:(id)arg2;
- (void)handFree:(_Bool)arg1;
- (void)micMute:(_Bool)arg1;
- (void)receiveVoIPSignalMsgFromAPN:(id)arg1;
- (void)acceptVoIPCall:(id)arg1;
- (void)stopVoIPCall:(id)arg1 type:(long long)arg2 errorCode:(unsigned long long)arg3;
- (void)startVoIPCall:(id)arg1 voipUUid:(id)arg2 toPSTN:(_Bool)arg3 fromPhone:(id)arg4 toPhone:(id)arg5;
- (void)startPlayOnPhoneAlert;
- (void)startPlayNotconnectedAlert;
- (void)startPlayBusyAlert;
- (void)startPlayHangupAlert;
- (void)stopPlayVibrate;
- (void)startPlayVibrate;
- (void)startPlayVibrateOnce:(_Bool)arg1;
- (void)stopPlayIncommingAlert;
- (void)checkVolume;
- (void)startPlayIncommingAlert;
- (void)destoryVoIP;
- (void)setupVoIP;
- (void)switchStateMachine:(unsigned long long)arg1 callId:(id)arg2 statusString:(id)arg3 timeDuration:(id)arg4 errorCode:(unsigned long long)arg5;
- (void)audioInterrupt:(id)arg1;
- (void)routeChange:(id)arg1;
- (void)didBecomeActive;
- (void)listenEnterForground;
- (void)listenAudioEvent;
- (id)init;
- (void)dealloc;

@end

