//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface DTSplashScreenModel : NSObject
{
    _Bool _hasDefaultSave;
    NSString *_defaultEndTime;
    NSString *_defaultPhoto;
    long long _channelType;
    NSString *_operationDetailURL;
    NSArray *_orgScreenSub;
    unsigned long long _showTime;
}

+ (id)toJsonStringWithModel:(id)arg1;
+ (id)modelWithJson:(id)arg1;
@property(nonatomic) unsigned long long showTime; // @synthesize showTime=_showTime;
@property(retain, nonatomic) NSArray *orgScreenSub; // @synthesize orgScreenSub=_orgScreenSub;
@property(copy, nonatomic) NSString *operationDetailURL; // @synthesize operationDetailURL=_operationDetailURL;
@property(nonatomic) _Bool hasDefaultSave; // @synthesize hasDefaultSave=_hasDefaultSave;
@property(nonatomic) long long channelType; // @synthesize channelType=_channelType;
@property(copy, nonatomic) NSString *defaultPhoto; // @synthesize defaultPhoto=_defaultPhoto;
@property(copy, nonatomic) NSString *defaultEndTime; // @synthesize defaultEndTime=_defaultEndTime;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

