//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class UITextField;

@interface DTTipEggListController : DTTableViewController
{
    _Bool _isPFEasyShowing;
    _Bool _isATShowing;
    UITextField *_textField;
}

@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) _Bool isATShowing; // @synthesize isATShowing=_isATShowing;
@property(nonatomic) _Bool isPFEasyShowing; // @synthesize isPFEasyShowing=_isPFEasyShowing;
- (void).cxx_destruct;
- (void)mockMails:(long long)arg1 toFolder:(id)arg2;
- (void)resetSyncPts;
- (void)swithcJavaScriptRunMode;
- (void)switchHpmEnvironment;
- (void)modifyUpFrag;
- (void)tap:(id)arg1;
- (void)dealloc;
- (void)loadDatasource;
- (void)viewDidLoad;

@end

