//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

@class DTButton, DTTipsViewModel, UIImageView, UILabel, UIView;

@interface DTTipsViewController : DTViewController
{
    DTTipsViewModel *_viewModel;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_contentLabel;
    UIView *_actionBackgroundView;
    DTButton *_actionButton;
    CDUnknownBlockType _callback;
}

@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) DTButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UIView *actionBackgroundView; // @synthesize actionBackgroundView=_actionBackgroundView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) DTTipsViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)nextButtonAction:(id)arg1;
- (void)leftBarButtonAction;
- (struct CGSize)sizeWithString:(id)arg1 font:(id)arg2 size:(struct CGSize)arg3;
- (void)loadComponents;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 callback:(CDUnknownBlockType)arg2;

@end

