//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTUmidManager : NSObject
{
}

+ (_Bool)isSimulator;
+ (id)encrypIsSimulatorString;
+ (id)encryptWithAES128:(id)arg1;
+ (id)decryptWithAES128:(id)arg1;
+ (id)sharedManager;
- (id)getUmidSecurityToken;
- (id)init;

@end

