//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTAsset, DTCSpaceMode, NSDictionary, WKBizMessage;
@protocol NSCopying><NSCoding;

@interface DTVendorsSendModel : NSObject
{
    long long _attachmentType;
    WKBizMessage *_wkBizMessage;
    DTCSpaceMode *_cSpaceMode;
    DTAsset *_videoAsset;
    NSDictionary<NSCopying><NSCoding> *_userInfo;
}

+ (id)buildWithSendInfo:(id)arg1 attachmentType:(long long)arg2;
@property(retain, nonatomic) NSDictionary<NSCopying><NSCoding> *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) DTAsset *videoAsset; // @synthesize videoAsset=_videoAsset;
@property(retain, nonatomic) DTCSpaceMode *cSpaceMode; // @synthesize cSpaceMode=_cSpaceMode;
@property(retain, nonatomic) WKBizMessage *wkBizMessage; // @synthesize wkBizMessage=_wkBizMessage;
@property(nonatomic) long long attachmentType; // @synthesize attachmentType=_attachmentType;
- (void).cxx_destruct;

@end

