//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTVideoConferenceMemberModel, DTVideoConferenceModel, NSArray, NSNumber, NSString, UIWindow;
@protocol DTVideoManageNetworkProtocol;

@protocol DTVideoManageServiceProtocol <NSObject>
@property(readonly, nonatomic) UIWindow *currentVideoConfWindow;
@property(readonly, nonatomic) _Bool frontCamera;
@property(readonly, nonatomic) _Bool amCaller;
@property(readonly, nonatomic) unsigned long long videoConf_Type;
@property(copy, nonatomic) DTVideoConferenceModel *videoModel;
@property(copy, nonatomic) CDUnknownBlockType videoConfEventCallBack;
@property(nonatomic) unsigned long long currentState;
@property(retain, nonatomic) id <DTVideoManageNetworkProtocol> networkIMP;
@property(nonatomic) _Bool isInVideoConference;
@property(nonatomic, getter=isStoping) _Bool stopHasPress;
- (void)onReceiveVideoConfPush:(id)arg1 type:(unsigned long long)arg2;
- (void)uploadLogByContent:(NSString *)arg1 successBlock:(void (^)(void))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)queryConferenceListByTime:(long long)arg1 maxCount:(unsigned long long)arg2 successBlock:(void (^)(NSArray *))arg3 failureBlock:(void (^)(NSError *))arg4;
- (void)indicationVideoConferenceMemberStatus:(unsigned long long)arg1 conferenceId:(NSString *)arg2 cameraStatus:(NSNumber *)arg3 micStatus:(NSNumber *)arg4 successBlock:(void (^)(void))arg5 failureBlock:(void (^)(NSError *))arg6;
- (void)controVideoConfByCalledIds:(NSArray *)arg1 controType:(unsigned long long)arg2 successBlock:(void (^)(void))arg3 failureBlock:(void (^)(NSError *))arg4;
- (void)pullVideoConfMembersByConferenceId:(NSString *)arg1 successBlock:(void (^)(NSArray *))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)pullVideoConfSuccessBlock:(void (^)(NSArray *))arg1 failureBlock:(void (^)(NSError *))arg2;
- (void)createVideoConfByCalledIds:(NSArray *)arg1 callType:(unsigned long long)arg2 successBlock:(void (^)(DTVideoConferenceModel *))arg3 failureBlock:(void (^)(NSError *))arg4;
- (_Bool)switchStateMachine:(unsigned long long)arg1;
- (void)pullVideoConfWhenReg;
- (void)windowShareRemoved:(NSString *)arg1;
- (void)windowShareAdded:(NSString *)arg1;
- (void)errorHasOccuredTitle:(NSString *)arg1 errorInfo:(NSString *)arg2 errorCode:(long long)arg3;
- (void)participantsChanged:(void *)arg1;
- (void)remoteSourceJoinRoom:(void *)arg1;
- (void)remoteSourceLeaveRoom:(void *)arg1;
- (void)receiveOhterFrame:(void *)arg1;
- (void)receiveSelfFrame:(void *)arg1;
- (void)receiveAudioFrame:(void *)arg1;
- (void)recordCPUInfo:(void *)arg1;
- (void)getBandWidthInfo:(void (^)(void *))arg1;
- (void)getMediaInfo:(void (^)(void *))arg1;
- (void)getParticipantInfo:(void (^)(void *))arg1;
- (void)getVideoInfo:(void (^)(void *))arg1;
- (void)refreshConfMember;
- (void)switchCameraCompletion:(void (^)(_Bool))arg1;
- (void)enableCamera:(_Bool)arg1 completion:(void (^)(_Bool))arg2;
- (void)enableSpeaker:(_Bool)arg1 completion:(void (^)(_Bool))arg2;
- (void)muteAudio:(_Bool)arg1 completion:(void (^)(_Bool))arg2;
- (void)unWatchMember:(NSString *)arg1;
- (void)memberWatch:(NSString *)arg1;
- (void)exitVideoConfCallWithMemeber:(DTVideoConferenceMemberModel *)arg1;
- (void)stopVideoConfCall:(_Bool)arg1;
- (void)receiveVideoConfByModel:(DTVideoConferenceModel *)arg1 directIntoConf:(_Bool)arg2;
- (void)createVideoConfFromRecordDirect:(NSArray *)arg1 callType:(unsigned long long)arg2 completion:(void (^)(_Bool))arg3;
- (void)createVideoConfFromRecord:(NSArray *)arg1 callType:(unsigned long long)arg2;
- (void)createVideoConfCallType:(unsigned long long)arg1;
@end

