//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTVIPUserAlarmManager.h"

@interface DTVIPUserAlarmManager (Mail)
+ (void)triggerMailAlarmWithModule:(id)arg1 subtype:(int)arg2 subtypeDesc:(id)arg3 error:(id)arg4 reason:(id)arg5;
@end

