//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

#import "DTVideoConferenceCollectionMemberCellDataSource-Protocol.h"
#import "DTVideoConferenceCollectionMemberCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UICollectionView, UICollectionViewFlowLayout, YYThreadSafeArray;
@protocol DTVideoConferenceMembersFooterDataSource, DTVideoConferenceMembersFooterDelegate;

@interface DTVideoConferenceMembersFooter : UICollectionReusableView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, DTVideoConferenceCollectionMemberCellDataSource, DTVideoConferenceCollectionMemberCellDelegate>
{
    _Bool _muteAll;
    id <DTVideoConferenceMembersFooterDelegate> _delegate;
    id <DTVideoConferenceMembersFooterDataSource> _dataSource;
    UICollectionView *_membersCollectionView;
    UICollectionViewFlowLayout *_membersCollectionLayout;
    YYThreadSafeArray *_memberArray;
    YYThreadSafeArray *_itemArray;
}

@property(retain, nonatomic) YYThreadSafeArray *itemArray; // @synthesize itemArray=_itemArray;
@property(retain, nonatomic) YYThreadSafeArray *memberArray; // @synthesize memberArray=_memberArray;
@property(retain, nonatomic) UICollectionViewFlowLayout *membersCollectionLayout; // @synthesize membersCollectionLayout=_membersCollectionLayout;
@property(retain, nonatomic) UICollectionView *membersCollectionView; // @synthesize membersCollectionView=_membersCollectionView;
@property(nonatomic) id <DTVideoConferenceMembersFooterDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) id <DTVideoConferenceMembersFooterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_isMemberConnectVideoConference:(id)arg1;
- (long long)_memberIndexInMemberArray:(id)arg1;
- (_Bool)_isMemberInVideoScreen:(id)arg1;
- (id)_memberAtIndex:(id)arg1;
- (void)_refreshItemsArray;
- (void)_loadComponent;
- (long long)memberCount;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)prepareForReuse;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)muteAll:(_Bool)arg1;
- (void)updateDataSource;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

