//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSNumber, NSString;

@protocol DTVideoManageNetworkProtocol <NSObject>
- (void)uploadLogByContent:(NSString *)arg1 successBlock:(void (^)(DTVidyoConfOperationResultModel *))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)queryConferenceListByTime:(long long)arg1 maxCount:(unsigned long long)arg2 successBlock:(void (^)(DTVidyoHistoryConfListResultModel *))arg3 failureBlock:(void (^)(NSError *))arg4;
- (void)indicationVideoConferenceByConferenceId:(NSString *)arg1 uid:(NSNumber *)arg2 memberStatus:(unsigned long long)arg3 cameraStatus:(NSNumber *)arg4 micStatus:(NSNumber *)arg5 successBlock:(void (^)(DTVidyoConfOperationResultModel *))arg6 failureBlock:(void (^)(NSError *))arg7;
- (void)controVideoConfByConferenceId:(NSString *)arg1 calledIds:(NSArray *)arg2 controType:(unsigned long long)arg3 successBlock:(void (^)(DTVidyoConfOperationResultModel *))arg4 failureBlock:(void (^)(NSError *))arg5;
- (void)pullVideoConfMembersByConferenceId:(NSString *)arg1 successBlock:(void (^)(DTVidyoConfMemberListResultModel *))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)pullVideoConfByCallerId:(NSNumber *)arg1 successBlock:(void (^)(DTVidyoConfListResultModel *))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)createVideoConfByCallerId:(NSNumber *)arg1 calledIds:(NSArray *)arg2 callType:(NSNumber *)arg3 successBlock:(void (^)(DTVidyoConfCreateResultModel *))arg4 failureBlock:(void (^)(NSError *))arg5;
@end

