//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "DTVoIPAudioProtocol-Protocol.h"

@class AVAudioPlayer, NSString;

@interface DTVoIPAudioManageIMP : NSObject <AVAudioPlayerDelegate, DTVoIPAudioProtocol>
{
    _Bool _isSpeakStatus;
    _Bool _isResetWhenEnd;
    AVAudioPlayer *_audioPlayer;
    NSString *_audioSessionCategoryBeforeVoIP;
}

@property(copy, nonatomic) NSString *audioSessionCategoryBeforeVoIP; // @synthesize audioSessionCategoryBeforeVoIP=_audioSessionCategoryBeforeVoIP;
@property(retain, nonatomic) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
- (void).cxx_destruct;
- (void)proximityChanged:(id)arg1;
- (void)enableProximity:(_Bool)arg1;
- (id)currentAudioOutputDevice:(id)arg1;
- (id)currentAudioInputDevice:(id)arg1;
- (id)returnAudioSessionCode:(long long)arg1;
- (void)resetAudioSessionCategory;
- (void)activeAudioSession:(_Bool)arg1 notifyOtherApp:(_Bool)arg2 speak:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (_Bool)setSpeaker:(_Bool)arg1;
- (void)forceStopPlayAudio;
- (void)startPlayAudio:(_Bool)arg1;
- (float)getVolume;
- (void)stopPlayVibrate;
- (void)startPlayVibrateCompletion:(CDUnknownBlockType)arg1;
- (void)startPlayAudioByURL:(id)arg1 enableSpeak:(_Bool)arg2 resetWhenEnd:(_Bool)arg3 numberOfLoops:(long long)arg4 error:(id *)arg5;
- (void)startPlayAudioByURL:(id)arg1 enableSpeak:(_Bool)arg2 error:(id *)arg3;
- (void)startPlayAudioByURL:(id)arg1 error:(id *)arg2;
- (void)startPlayAudioByName:(id)arg1 enableSpeak:(_Bool)arg2 resetWhenEnd:(_Bool)arg3 numberOfLoops:(long long)arg4 error:(id *)arg5;
- (void)startPlayAudioByName:(id)arg1 enableSpeak:(_Bool)arg2 error:(id *)arg3;
- (void)startPlayAudioByName:(id)arg1 error:(id *)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

