//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTWebViewController.h"

@interface DTWebViewController (Parse)
- (_Bool)willLoadNewPageWithRequest:(id)arg1 navigationType:(long long)arg2 webViewRequest:(id)arg3;
- (id)generateQueryParamsWithQuery:(id)arg1;
- (_Bool)checkForceRotateParams:(id)arg1;
- (_Bool)checkOrientationAndRotate:(id)arg1;
- (void)parseParamsFromURL:(id)arg1;
- (void)parseNavigationColorWithInitialURL:(id)arg1;
@end

