//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTWebViewController.h"

@interface DTWebViewController (JsBridge)
+ (void)swithcJavaScriptRunMode;
+ (void)setJavaScriptRunMode:(long long)arg1;
+ (long long)javaScriptRunMode;
+ (id)javaScriptRunModeString;
- (void)jsBridge_pagePostWebViewDidLoadAllBridge;
- (void)jsBridge_viewWillDisappear:(_Bool)arg1;
- (void)jsBridge_viewDidAppear:(_Bool)arg1;
@end

