//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTWorkCalendarCellModel : NSObject
{
    _Bool _hideTopLine;
    _Bool _hideBottomLine;
    long long _cellType;
    long long _orgId;
    long long _deptId;
    NSString *_appId;
    NSString *_subAppId;
    NSString *_actionURL;
    CDUnknownBlockType _cellDidSelectedBlock;
    CDUnknownBlockType _cellAccessoryDidSelectedBlock;
}

+ (long long)calenderCellTypeWithIdlStyleType:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType cellAccessoryDidSelectedBlock; // @synthesize cellAccessoryDidSelectedBlock=_cellAccessoryDidSelectedBlock;
@property(copy, nonatomic) CDUnknownBlockType cellDidSelectedBlock; // @synthesize cellDidSelectedBlock=_cellDidSelectedBlock;
@property(nonatomic) _Bool hideBottomLine; // @synthesize hideBottomLine=_hideBottomLine;
@property(nonatomic) _Bool hideTopLine; // @synthesize hideTopLine=_hideTopLine;
@property(copy, nonatomic) NSString *actionURL; // @synthesize actionURL=_actionURL;
@property(copy, nonatomic) NSString *subAppId; // @synthesize subAppId=_subAppId;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(nonatomic) long long deptId; // @synthesize deptId=_deptId;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
- (void).cxx_destruct;
- (void)paddingDataWithIDLModel:(id)arg1;

@end

