//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTWebImageView, UIImageView, UILabel;
@protocol DTWorkHeaderViewDelete;

@interface DTWorkHeaderView : UIView
{
    id <DTWorkHeaderViewDelete> _delegate;
    long long _workHeaderHeight;
    DTWebImageView *_workHeaderImageView;
    UILabel *_workHeaderLabel;
    UIImageView *_workLabelMaskView;
}

@property(retain, nonatomic) UIImageView *workLabelMaskView; // @synthesize workLabelMaskView=_workLabelMaskView;
@property(retain, nonatomic) UILabel *workHeaderLabel; // @synthesize workHeaderLabel=_workHeaderLabel;
@property(retain, nonatomic) DTWebImageView *workHeaderImageView; // @synthesize workHeaderImageView=_workHeaderImageView;
@property(nonatomic) long long workHeaderHeight; // @synthesize workHeaderHeight=_workHeaderHeight;
@property(nonatomic) __weak id <DTWorkHeaderViewDelete> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onImageViewTapped:(id)arg1;
- (void)stretchHeaderViewHeightWithOffset:(double)arg1;
- (void)configHeaderWithImageUrl:(id)arg1 headerText:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

