//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ELCAssetOriginalSendViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTAssetCollection, DTAssetHandler, DTPHPickerBottomView, ELCAssetOriginalSendView, MWPhotoBrowser, NSArray, NSMutableArray, NSString, UITableView;
@protocol ELCAssetPickerFilterDelegate, ELCAssetSelectionDelegate;

@interface ELCAssetTablePicker : UIViewController <UITableViewDataSource, UITableViewDelegate, ELCAssetOriginalSendViewDelegate>
{
    _Bool _singleSelection;
    _Bool _immediateReturn;
    _Bool _supportOriginalSelected;
    _Bool _supportPreview;
    _Bool _selectOriginal;
    _Bool _fullImage;
    _Bool _isPreview;
    int _columns;
    id <ELCAssetSelectionDelegate> _parent;
    DTAssetCollection *_assetGroup;
    NSMutableArray *_elcAssets;
    long long _style;
    long long _filterType;
    NSString *_confirmText;
    id <ELCAssetPickerFilterDelegate> _assetPickerFilterDelegate;
    UITableView *_pickerTableView;
    ELCAssetOriginalSendView *_sendView;
    NSMutableArray *_selectedAssets;
    unsigned long long _totalSize;
    NSMutableArray *_photos;
    DTAssetHandler *_assetHandler;
    NSMutableArray *_selections;
    DTPHPickerBottomView *_bottomView;
    ELCAssetOriginalSendView *_sendView1;
    NSArray *_previewingAssets;
    unsigned long long _currentIdx;
    MWPhotoBrowser *_photoBrowser;
}

@property(nonatomic) __weak MWPhotoBrowser *photoBrowser; // @synthesize photoBrowser=_photoBrowser;
@property(nonatomic) unsigned long long currentIdx; // @synthesize currentIdx=_currentIdx;
@property(retain, nonatomic) NSArray *previewingAssets; // @synthesize previewingAssets=_previewingAssets;
@property(nonatomic) _Bool isPreview; // @synthesize isPreview=_isPreview;
@property(retain, nonatomic) ELCAssetOriginalSendView *sendView1; // @synthesize sendView1=_sendView1;
@property(retain, nonatomic) DTPHPickerBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) NSMutableArray *selections; // @synthesize selections=_selections;
@property(retain, nonatomic) DTAssetHandler *assetHandler; // @synthesize assetHandler=_assetHandler;
@property(nonatomic) _Bool fullImage; // @synthesize fullImage=_fullImage;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(nonatomic) _Bool selectOriginal; // @synthesize selectOriginal=_selectOriginal;
@property(nonatomic) unsigned long long totalSize; // @synthesize totalSize=_totalSize;
@property(retain, nonatomic) NSMutableArray *selectedAssets; // @synthesize selectedAssets=_selectedAssets;
@property(retain, nonatomic) ELCAssetOriginalSendView *sendView; // @synthesize sendView=_sendView;
@property(retain, nonatomic) UITableView *pickerTableView; // @synthesize pickerTableView=_pickerTableView;
@property(nonatomic) int columns; // @synthesize columns=_columns;
@property(nonatomic) __weak id <ELCAssetPickerFilterDelegate> assetPickerFilterDelegate; // @synthesize assetPickerFilterDelegate=_assetPickerFilterDelegate;
@property(copy, nonatomic) NSString *confirmText; // @synthesize confirmText=_confirmText;
@property(nonatomic) _Bool supportPreview; // @synthesize supportPreview=_supportPreview;
@property(nonatomic) long long filterType; // @synthesize filterType=_filterType;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic) _Bool supportOriginalSelected; // @synthesize supportOriginalSelected=_supportOriginalSelected;
@property(nonatomic) _Bool immediateReturn; // @synthesize immediateReturn=_immediateReturn;
@property(nonatomic) _Bool singleSelection; // @synthesize singleSelection=_singleSelection;
@property(retain, nonatomic) NSMutableArray *elcAssets; // @synthesize elcAssets=_elcAssets;
@property(retain, nonatomic) DTAssetCollection *assetGroup; // @synthesize assetGroup=_assetGroup;
@property(nonatomic) __weak id <ELCAssetSelectionDelegate> parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (void)photoBrowserCurrentIndex:(unsigned long long)arg1;
- (void)photoBrowserDidDisappear:(id)arg1;
- (void)photoBrowserCustomBottomToolBarOriginComplete:(id)arg1;
- (id)photoBrowserCustomBottomToolBar:(id)arg1 customAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2 selectedChanged:(_Bool)arg3;
- (_Bool)photoBrowser:(id)arg1 isPhotoSelectedAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (id)currentPhotoBrowserAssets;
- (void)initPhotosData;
- (void)showMWPhotoBrowser:(id)arg1 withELCAsset:(id)arg2;
- (int)totalSelectedAssets;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)assetsForIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initPreivewData;
- (void)preview;
- (void)send;
- (void)didSelectOriginal:(_Bool)arg1;
- (void)assetSelected:(id)arg1;
- (_Bool)shouldSelectAsset:(id)arg1;
- (void)doneAction;
- (void)cancelAction;
- (void)preparePhotos;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

