//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UINavigationControllerDelegate-Protocol.h"

@class ELCImagePickerController, NSArray;

@protocol ELCImagePickerControllerDelegate <UINavigationControllerDelegate>
- (void)elcImagePickerControllerDidCancel:(ELCImagePickerController *)arg1;
- (void)elcImagePickerController:(ELCImagePickerController *)arg1 didFinishPickingMediaWithInfo:(NSArray *)arg2;

@optional
- (void)elcImagePickerController:(ELCImagePickerController *)arg1 didFinishPickingAssets:(NSArray *)arg2;
@end

