//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class H5AMAppDownloadManager, H5AMAppStorage, NSString;

@interface H5AMAppManager : NSObject
{
    NSString *_unzipRootDictionaryPath;
    NSString *_downloadRootDictionaryPath;
    H5AMAppStorage *_appStorage;
    H5AMAppDownloadManager *_appDownloadMngr;
}

+ (id)version;
+ (id)allocPrivate;
+ (id)shareInstance;
@property(retain, nonatomic) H5AMAppDownloadManager *appDownloadMngr; // @synthesize appDownloadMngr=_appDownloadMngr;
@property(retain, nonatomic) H5AMAppStorage *appStorage; // @synthesize appStorage=_appStorage;
@property(retain, nonatomic) NSString *downloadRootDictionaryPath; // @synthesize downloadRootDictionaryPath=_downloadRootDictionaryPath;
@property(retain, nonatomic) NSString *unzipRootDictionaryPath; // @synthesize unzipRootDictionaryPath=_unzipRootDictionaryPath;
- (void).cxx_destruct;
- (void)requestUpdateAllApp;
- (void)sync:(id)arg1;
- (void)requsetInstallApps:(id)arg1;
- (void)removeAppById:(id)arg1;
- (id)findAppById:(id)arg1;
- (id)apps;
- (long long)updateAppList:(id)arg1;
- (void)unzipApp:(id)arg1;
- (void)downloadAppFinish:(id)arg1 error:(id)arg2 mode:(long long)arg3;
- (void)reDownloadApp:(id)arg1;
- (void)downloadApp:(id)arg1;
- (void)postAppListUpdateNotif:(unsigned long long)arg1 progress:(double)arg2;
- (void)postAppUnZipNotif:(id)arg1 status:(unsigned long long)arg2 progress:(double)arg3;
- (void)postAppDownloadNotif:(id)arg1 status:(unsigned long long)arg2 progress:(double)arg3;
- (void)checkAndDownloadApp;
- (void)copyOfflinePackage2AppCenter;
- (id)getAppTarPath:(id)arg1;
- (id)getAppPath:(id)arg1;
- (id)getAppAmrPath:(id)arg1;
- (id)initPrivate;

@end

