//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "H5AMAppManager.h"

@interface H5AMAppManager (Dingtalk)
- (void)dt_removeAppByAppId:(id)arg1;
- (void)dt_removeAppAmrData:(id)arg1 error:(id *)arg2;
- (void)dt_Sync:(id)arg1;
- (long long)extendStatusCode:(id)arg1;
- (void)modifyStatusForDingtalk:(id)arg1;
@end

