//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol IStaticDataStoreComponent <NSObject>
- (NSString *)getExtraData:(NSString *)arg1;
- (NSString *)getAppKey:(NSNumber *)arg1;
- (long long)getKeyType:(NSString *)arg1;
@end

