//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LAPluginDelegate-Protocol.h"

@class NSMutableDictionary, NSString, UIViewController, UIWebView, WebViewJavascriptBridge;
@protocol LAPluginInstanceCollectorDelegate;

@interface LAPluginInstanceCollector : NSObject <LAPluginDelegate>
{
    id <LAPluginInstanceCollectorDelegate> _delegate;
    UIWebView *_webView;
    UIViewController *_viewController;
    WebViewJavascriptBridge *_jsBridge;
    NSMutableDictionary *_plugInstanceMap;
}

@property(retain, nonatomic) NSMutableDictionary *plugInstanceMap; // @synthesize plugInstanceMap=_plugInstanceMap;
@property(nonatomic) __weak WebViewJavascriptBridge *jsBridge; // @synthesize jsBridge=_jsBridge;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak id <LAPluginInstanceCollectorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dispatchEvent:(id)arg1 data:(id)arg2;
- (void)plugin:(id)arg1 callAction:(id)arg2 data:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)initPresetClasses;
- (id)buildActionAsyncResponse:(CDUnknownBlockType)arg1;
- (id)buildActionResponse:(CDUnknownBlockType)arg1;
- (id)buildActionRequest:(id)arg1;
- (void)registerExcuteBlockToBridge;
- (void)unregisterCollector;
- (void)dealloc;
- (id)initCollectorWithWebView:(id)arg1 viewController:(id)arg2 webViewJavascriptBridge:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

