//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LAPluginBase.h"

@interface LAPluginBase (DTUtils)
+ (_Bool)verifyCredibleDomian:(id)arg1 pluginName:(id)arg2 methodName:(id)arg3;
@end

