//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "LANJKWebViewProgressDelegate-Protocol.h"
#import "LAPageSliderViewDelegate-Protocol.h"
#import "LAPluginInstanceCollectorDelegate-Protocol.h"
#import "LAWebViewControllerProtocol-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class LAActionQueue, LADurableLocationManager, LANJKWebViewProgress, LANJKWebViewProgressView, LANaviBarModel, LAPageSliderView, LAPluginInstanceCollector, LAWebViewNavigationManager, LAWebViewSetting, NSString, NSURL, NSURLRequest, UILabel, UIRefreshControl, UIWebView, WebViewJavascriptBridge;
@protocol LAWebViewControllerDelegate;

@interface LAWebViewController : UIViewController <LANJKWebViewProgressDelegate, UIWebViewDelegate, LAPageSliderViewDelegate, LAPluginInstanceCollectorDelegate, LAWebViewControllerProtocol>
{
    long long _numRequestsLoading;
    _Bool _isJsBridgeLoaded;
    id <LAWebViewControllerDelegate> _delegate;
    NSURL *_initialURL;
    WebViewJavascriptBridge *_jsBridge;
    UIWebView *_webView;
    LANaviBarModel *_naviBarModel;
    LAWebViewSetting *_webSetting;
    LAWebViewNavigationManager *_navigationManager;
    LAPageSliderView *_webWrapView;
    LADurableLocationManager *_durableLocationManager;
    CDUnknownBlockType _webViewClosedBlock;
    CDUnknownBlockType _webViewRefreshBlock;
    LAActionQueue *_viewLoadedActQueue;
    LAActionQueue *_viewAppearActQueue;
    LANJKWebViewProgressView *_progressView;
    NSURL *_curRequestURL;
    NSURLRequest *_curRequest;
    NSURL *_curRequestMainDocURL;
    NSURLRequest *_curMainDocRequest;
    LAPluginInstanceCollector *_pluginCollector;
    LANJKWebViewProgress *_progressProxy;
    UIRefreshControl *_refreshControl;
    UILabel *_sourceLabel;
}

@property(retain, nonatomic) UILabel *sourceLabel; // @synthesize sourceLabel=_sourceLabel;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) LANJKWebViewProgress *progressProxy; // @synthesize progressProxy=_progressProxy;
@property(retain, nonatomic) LAPluginInstanceCollector *pluginCollector; // @synthesize pluginCollector=_pluginCollector;
@property(retain, nonatomic) NSURLRequest *curMainDocRequest; // @synthesize curMainDocRequest=_curMainDocRequest;
@property(retain, nonatomic) NSURL *curRequestMainDocURL; // @synthesize curRequestMainDocURL=_curRequestMainDocURL;
@property(retain, nonatomic) NSURLRequest *curRequest; // @synthesize curRequest=_curRequest;
@property(retain, nonatomic) NSURL *curRequestURL; // @synthesize curRequestURL=_curRequestURL;
@property(retain, nonatomic) LANJKWebViewProgressView *progressView; // @synthesize progressView=_progressView;
@property(readonly, nonatomic) LAActionQueue *viewAppearActQueue; // @synthesize viewAppearActQueue=_viewAppearActQueue;
@property(readonly, nonatomic) LAActionQueue *viewLoadedActQueue; // @synthesize viewLoadedActQueue=_viewLoadedActQueue;
@property(copy, nonatomic) CDUnknownBlockType webViewRefreshBlock; // @synthesize webViewRefreshBlock=_webViewRefreshBlock;
@property(copy, nonatomic) CDUnknownBlockType webViewClosedBlock; // @synthesize webViewClosedBlock=_webViewClosedBlock;
@property(retain, nonatomic) LADurableLocationManager *durableLocationManager; // @synthesize durableLocationManager=_durableLocationManager;
@property(retain, nonatomic) LAPageSliderView *webWrapView; // @synthesize webWrapView=_webWrapView;
@property(retain, nonatomic) LAWebViewNavigationManager *navigationManager; // @synthesize navigationManager=_navigationManager;
@property(retain, nonatomic) LAWebViewSetting *webSetting; // @synthesize webSetting=_webSetting;
@property(retain, nonatomic) LANaviBarModel *naviBarModel; // @synthesize naviBarModel=_naviBarModel;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool isJsBridgeLoaded; // @synthesize isJsBridgeLoaded=_isJsBridgeLoaded;
@property(retain, nonatomic) WebViewJavascriptBridge *jsBridge; // @synthesize jsBridge=_jsBridge;
@property(retain, nonatomic) NSURL *initialURL; // @synthesize initialURL=_initialURL;
@property(nonatomic) __weak id <LAWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)imgElementSRCsInDocument;
- (id)linkElementHREFAtPointInViewport:(struct CGPoint)arg1;
- (id)imgElementSRCAtPointInViewPort:(struct CGPoint)arg1;
- (id)htmlElementTagsAtPointInViewport:(struct CGPoint)arg1;
- (struct CGRect)imgElementFrameInWebViewAtPointInViewport:(struct CGPoint)arg1;
- (struct CGPoint)pointInWebViewFromPointInViewport:(struct CGPoint)arg1;
- (struct CGPoint)pointInViewportFromPointInWebView:(struct CGPoint)arg1;
- (struct CGPoint)pointInWebViewFromPointInHTML:(struct CGPoint)arg1;
- (struct CGPoint)pointInHTMLFromPointInWebView:(struct CGPoint)arg1;
- (id)returnAudioSessionCode:(long long)arg1;
- (id)setAudioSessionPlayAndRecordWithSpeaker:(_Bool)arg1;
- (void)activeAudioSession:(_Bool)arg1 notifyOtherApp:(_Bool)arg2 speak:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)outVedioFullScreenView;
- (void)enterVedioFullScreenView;
- (_Bool)pluginInstance:(id)arg1 jsapiShouldCall:(id)arg2;
- (_Bool)addWebPageViewWihtNextPageURL:(id)arg1;
- (void)pageSliderViewDidGoback:(id)arg1;
- (void)pageSliderViewWillGoBack:(id)arg1;
- (_Bool)pageSliderViewShouldGoback:(id)arg1;
- (id)pageSliderBackMirrorView;
- (id)pageSliderContentView;
- (void)configWebJsBridge;
- (void)webViewProgress:(id)arg1 updateProgress:(float)arg2;
- (void)loadDingTalkWebviewJSToolIfNeed;
- (void)loadVedioHookerIfNeed;
- (void)loadNuvaJsIfNeed;
- (_Bool)isNonscenFragment:(id)arg1;
- (_Bool)shouldCheckWebViewPageSlide:(id)arg1;
- (_Bool)shouldIgnoreWebViewError:(id)arg1;
- (_Bool)isLoadingMainDocumentURL;
- (_Bool)isLoadingInitialURL;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)setupSourceLabelWithTextColor:(id)arg1 font:(id)arg2;
- (void)configSourceLabelText:(id)arg1;
- (void)setWebViewBounces:(_Bool)arg1;
- (void)endRefreshingActivityIndicator;
- (void)beginRefreshingActivityIndicator;
- (void)setRefreshControlEnabled:(_Bool)arg1;
- (void)handleRefresh:(id)arg1;
- (void)setupWebViewTitle;
- (void)setWebViewWrapEnable:(_Bool)arg1;
- (void)initWebWrapView;
- (void)initWebViewComponets;
- (void)reloadCurrentRequest;
- (void)loadInitialRequest;
- (void)otherPageRequestError:(id)arg1 error:(id)arg2;
- (void)otherPageRequestFinished:(id)arg1;
- (void)otherPageRequestStarted:(id)arg1;
- (void)mainDocumentRequestError:(id)arg1 error:(id)arg2;
- (void)mainDocumentRequestFinished:(id)arg1;
- (void)mainDocumentRequestStarted:(id)arg1;
- (void)initialURLRequestError:(id)arg1 error:(id)arg2;
- (void)initialURLRequestFinished:(id)arg1;
- (void)initialURLRequestWillStart:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)initPrivate;
- (id)initWithInitialURL:(id)arg1 webSetting:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

