//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ALAudioRecorder;

@interface LWAudioRecorderListener : NSObject
{
    ALAudioRecorder *_recorder;
}

@property __weak ALAudioRecorder *recorder; // @synthesize recorder=_recorder;
- (void).cxx_destruct;

@end

