//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "AVAudioRecorderDelegate-Protocol.h"
#import "LWAudioRecorderProtocol-Protocol.h"

@class ALAudioRecorder, AVAudioPlayer, LWAMRPlayer, NSString, NSURL;
@protocol LWAudioRecorderProtocol;

@interface LWAudioRecorder : NSObject <LWAudioRecorderProtocol, AVAudioRecorderDelegate, AVAudioPlayerDelegate>
{
    NSURL *_recordedTmpFile;
    NSURL *_recordedTmpAmrFile;
    ALAudioRecorder *recorder;
    LWAMRPlayer *amrplayer;
    AVAudioPlayer *avAudioPlayer;
    NSString *lastPlayIdentifier;
    _Bool earphoneModeEnabled;
    _Bool isPause;
    _Bool isForceEarphoneMode;
    _Bool _isShoudProximityState;
    CDUnknownBlockType onSwitchToSpeaker;
    CDUnknownBlockType onSwitchToEarphone;
    CDUnknownBlockType onPlayDidStopped;
    id <LWAudioRecorderProtocol> _recordDelegate;
    NSString *_audioSessionCategoryBeforeAudio;
}

+ (id)sharedAudioRecorder;
@property(copy, nonatomic) NSString *audioSessionCategoryBeforeAudio; // @synthesize audioSessionCategoryBeforeAudio=_audioSessionCategoryBeforeAudio;
@property(nonatomic) _Bool isShoudProximityState; // @synthesize isShoudProximityState=_isShoudProximityState;
@property(nonatomic) __weak id <LWAudioRecorderProtocol> recordDelegate; // @synthesize recordDelegate=_recordDelegate;
@property(readonly, nonatomic) NSURL *recordedTmpAmrFile; // @synthesize recordedTmpAmrFile=_recordedTmpAmrFile;
@property(readonly, nonatomic) NSURL *recordedTmpFile; // @synthesize recordedTmpFile=_recordedTmpFile;
@property(nonatomic) _Bool isForceEarphoneMode; // @synthesize isForceEarphoneMode;
@property(copy, nonatomic) CDUnknownBlockType onPlayDidStopped; // @synthesize onPlayDidStopped;
@property(copy, nonatomic) CDUnknownBlockType onSwitchToEarphone; // @synthesize onSwitchToEarphone;
@property(copy, nonatomic) CDUnknownBlockType onSwitchToSpeaker; // @synthesize onSwitchToSpeaker;
@property(nonatomic) _Bool earphoneModeEnabled; // @synthesize earphoneModeEnabled;
@property(readonly, copy, nonatomic) NSString *lastPlayIdentifier; // @synthesize lastPlayIdentifier;
- (void).cxx_destruct;
- (void)audioRecorderTrackTime:(double)arg1;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)audioRecorderDidRecord:(id)arg1 recordBuffer:(const char *)arg2 recordLength:(int)arg3 encodeAmrAudioLen:(int)arg4 totalAmrEncodeLen:(int)arg5;
- (void)audioRecorderDidStartRecording:(id)arg1;
- (void)audioRecorderAudioSessionInterruption:(_Bool)arg1;
- (void)audioRecorderThrowError:(id)arg1;
- (double)currentTime:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)didFinishPlayingWithSuc:(_Bool)arg1;
- (void)stopPlay;
- (void)continuePlay;
- (void)pause;
- (_Bool)isPause;
- (_Bool)isPlaying;
- (_Bool)isPlaying:(id)arg1;
- (void)sendStatus:(int)arg1;
- (void)playWave:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3 withProximityMonitoring:(_Bool)arg4;
- (void)playWave:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3;
- (void)playWave:(id)arg1 playIdentifier:(id)arg2;
- (void)play:(id)arg1 playIdentifier:(id)arg2;
- (void)play:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3 withProximityMonitoring:(_Bool)arg4;
- (void)play:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3;
- (void)playAmr:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3 withProximityMonitoring:(_Bool)arg4;
- (void)playAmr:(id)arg1 playIdentifier:(id)arg2 withCategory:(id)arg3;
- (void)playAmr:(id)arg1 playIdentifier:(id)arg2;
- (void)keepLastPlayMode;
- (id)decodeAmr:(id)arg1;
- (float)averagePowerForChannelV2;
- (float)averagePowerForChannel;
- (float)peakPowerForChannel;
- (_Bool)isRecording;
- (id)stopRecord;
- (void)startRecord:(id)arg1 amrFilePath:(id)arg2;
- (void)startRecord;
- (void)resetAudioRecorder;
- (double)getAudioTime:(id)arg1;
- (void)delayAudioUnActive;
- (void)audioUnActive;
- (id)returnAudioSessionCode:(long long)arg1;
- (void)activeAudioSession:(_Bool)arg1 notifyOtherApp:(_Bool)arg2 speak:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)audioActive;
- (void)replay;
- (_Bool)setSpeaker:(_Bool)arg1;
- (void)sensorStateChange:(id)arg1;
- (id)setAudioSessionPlayAndRecordWithSpeaker:(_Bool)arg1;
- (void)initAudioSession;
- (void)setIdleTimerDisabled:(_Bool)arg1;
- (void)setProximityMonitoringEnabled:(_Bool)arg1;
- (void)tryDisableProximityMonitoring;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

