//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LWURLInterceptorProtocol-Protocol.h"

@class NSPredicate, NSString;

@interface LWHTTPTrafficInterceptor : NSObject <LWURLInterceptorProtocol>
{
    NSPredicate *_predicate;
}

- (void).cxx_destruct;
- (void)interceptor:(id)arg1 handleRequest:(id)arg2 response:(id)arg3 stopHandle:(_Bool *)arg4;
- (_Bool)interceptor:(id)arg1 canHandleRequest:(id)arg2;
- (void)interceptorUnRegister:(id)arg1;
- (void)interceptorRegister:(id)arg1;
- (id)interceptorIdentifier;
- (long long)interceptorPriority;
- (id)initWithSchemes:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

