//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LWPDownloadTask.h"

@interface LWPDownloadTask (Private)
- (void)appendDataToFileHandle:(id)arg1 data:(id)arg2 offset:(unsigned long long)arg3 noSaveDataLength:(unsigned long long *)arg4 error:(id *)arg5;
- (void)appendDataTo:(id)arg1 from:(id)arg2 offset:(unsigned long long)arg3 error:(id *)arg4;
@end

