//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LWPConnection, LWPMessage, LWPResponse, NSDictionary, NSError, NSString;

@protocol LWPMessengerDelegate <NSObject>
- (void)connection:(LWPConnection *)arg1 didAuthFinish:(LWPResponse *)arg2 error:(NSError *)arg3;
- (NSDictionary *)lwpMessengerRequireAuthHeader:(LWPConnection *)arg1;
- (_Bool)lwpMessengerConnectionCanSendMessage:(LWPConnection *)arg1;
- (_Bool)isMessageInQueue:(NSString *)arg1;
- (void)lwpMessengerConnection:(LWPConnection *)arg1 recvMessage:(LWPMessage *)arg2;
- (void)lwpMessengerConnectionBroken:(LWPConnection *)arg1 error:(NSError *)arg2 isConnectFailed:(_Bool)arg3;
- (void)lwpMessengerConnectionAuthed:(LWPConnection *)arg1;
- (void)lwpMessengerConnectionConnected:(LWPConnection *)arg1;
- (void)lwpMessengerConnectionStartConnect:(LWPConnection *)arg1;
@end

