//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LWPNetworkDiagnoser.h"

@interface LWPNetworkDiagnoser (RawSocket)
- (void)detectRawSocketsConnectable:(id)arg1 timeout:(double)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)detectRawSocketConnectable:(id)arg1 timeout:(double)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)detectRawSocketConnectable:(id)arg1 finishBlock:(CDUnknownBlockType)arg2;
@end

