//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LWURLProxyDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString;
@protocol LWURLResponseProcessProtocol;

@interface LWURLInterceptorManager : NSObject <LWURLProxyDelegate>
{
    NSMutableDictionary *_interceptorRetainMap;
    NSMutableArray *_interceptorList;
    NSRecursiveLock *_interceptorListLock;
    NSMutableDictionary *_interceptorMap;
    NSRecursiveLock *_interceptorMapLock;
    NSMutableArray *_ignoredHostList;
    NSRecursiveLock *_ignoredHostListLock;
    id <LWURLResponseProcessProtocol> _responseProcesser;
}

+ (id)sharedManager;
@property(retain, nonatomic) id <LWURLResponseProcessProtocol> responseProcesser; // @synthesize responseProcesser=_responseProcesser;
@property(retain, nonatomic) NSRecursiveLock *ignoredHostListLock; // @synthesize ignoredHostListLock=_ignoredHostListLock;
@property(retain, nonatomic) NSMutableArray *ignoredHostList; // @synthesize ignoredHostList=_ignoredHostList;
@property(retain, nonatomic) NSRecursiveLock *interceptorMapLock; // @synthesize interceptorMapLock=_interceptorMapLock;
@property(retain, nonatomic) NSMutableDictionary *interceptorMap; // @synthesize interceptorMap=_interceptorMap;
@property(retain, nonatomic) NSRecursiveLock *interceptorListLock; // @synthesize interceptorListLock=_interceptorListLock;
@property(retain, nonatomic) NSMutableArray *interceptorList; // @synthesize interceptorList=_interceptorList;
@property(readonly, copy, nonatomic) NSMutableDictionary *interceptorRetainMap; // @synthesize interceptorRetainMap=_interceptorRetainMap;
- (void).cxx_destruct;
- (id)sharedNormalOperationQueue;
- (_Bool)shouldIgnoreHost:(id)arg1;
- (void)removeAllFilteredHosts;
- (_Bool)addIgnoredHostList:(id)arg1;
- (void)removeAllInterceptors;
- (_Bool)removeInterceptor:(id)arg1;
- (_Bool)addInterceptor:(id)arg1 forceFront:(_Bool)arg2;
- (id)findInterceptorForRequest:(id)arg1;
- (void)checkHitWithStartIndex:(long long)arg1 request:(id)arg2 response:(id)arg3;
- (void)urlProxy:(id)arg1 stopLoading:(id)arg2 response:(id)arg3 withIdentifier:(id)arg4;
- (void)urlProxy:(id)arg1 startLoading:(id)arg2 response:(id)arg3 withIdentifier:(id)arg4;
- (void)urlProxy:(id)arg1 initRequest:(id)arg2 withIdentifier:(id)arg3;
- (_Bool)urlProxy:(id)arg1 canInitWithRequest:(id)arg2;
- (void)addObservers;
- (id)initPrivate;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

