//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAPolyline.h"

@class NSArray;

@interface MAMultiPolyline : MAPolyline
{
    NSArray *_drawStyleIndexes;
}

+ (id)polylineWithCoordinates:(CDStruct_c3b9c2ee *)arg1 count:(unsigned long long)arg2 drawStyleIndexes:(id)arg3;
+ (id)polylineWithPoints:(CDStruct_c3b9c2ee *)arg1 count:(unsigned long long)arg2 drawStyleIndexes:(id)arg3;
@property(retain, nonatomic) NSArray *drawStyleIndexes; // @synthesize drawStyleIndexes=_drawStyleIndexes;
- (void).cxx_destruct;
- (id)initWithCoordinates:(CDStruct_c3b9c2ee *)arg1 count:(unsigned long long)arg2 drawStyleIndexes:(id)arg3;
- (id)initWithPoints:(CDStruct_c3b9c2ee *)arg1 count:(unsigned long long)arg2 drawStyleIndexes:(id)arg3;
- (_Bool)checkDrawIndexes:(id)arg1;

@end

