//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (AES256)
+ (id)AES256DecryptWithData:(id)arg1 key:(id)arg2;
+ (id)AES256EncryptWithWithData:(id)arg1 key:(id)arg2;
@end

