//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTAuthDelegate-Protocol.h"

@class DTConversationService, DTMessageService, NSString;
@protocol DTAuthServiceProtocol, DTContactManager;

@interface OpenIM : NSObject <DTAuthDelegate>
{
    id <DTContactManager> _contactManager;
    id <DTAuthServiceProtocol> _authService;
    DTConversationService *_chatService;
    DTMessageService *_messageService;
}

+ (id)sharedInstance;
@property(retain, nonatomic) DTMessageService *messageService; // @synthesize messageService=_messageService;
@property(retain, nonatomic) DTConversationService *chatService; // @synthesize chatService=_chatService;
@property(retain, nonatomic) id <DTAuthServiceProtocol> authService; // @synthesize authService=_authService;
@property(retain, nonatomic) id <DTContactManager> contactManager; // @synthesize contactManager=_contactManager;
- (void).cxx_destruct;
- (void)authLogoutCompletion;
- (void)authLoginSuccess;
- (void)clear;
- (void)setup;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

