//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OpenDatabase.h"

#import "DTSearchEngineIndexDatabase-Protocol.h"

@class NSString;

@interface OpenDatabase (DTSearchEngine) <DTSearchEngineIndexDatabase>
- (struct sqlite3 *)sqliteForScanReadForSearch;
- (struct sqlite3 *)sqliteForReadForSearch;
- (struct sqlite3 *)sqliteForHookForSearch;
- (void)removeSearchUpdateHookDatabase:(CDUnknownFunctionPointerType)arg1;
- (void)updateSearchHookDatabase:(CDUnknownFunctionPointerType)arg1 userInfo:(void *)arg2;
- (id)allTableNamesForSearch;
- (id)databaseNameForSearch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

