//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QPBaseViewController.h"

#import "QURecordDelegate-Protocol.h"

@class CMMotionManager, NSLayoutConstraint, NSString, QPCountDownView, QPFocusView, QPGPUImageView, QPPointProgress, QPRecordGuideView, QPRecordTipGuideView, UIActionSheet, UIActivityIndicatorView, UIButton, UILabel, UIPanGestureRecognizer, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView;

@interface QPRecordViewController : QPBaseViewController <QURecordDelegate>
{
    QPFocusView *_focusView;
    UIActionSheet *_actionSheet;
    long long _deviceAngle;
    double _lastPinchDistance;
    double _lastPanY;
    struct {
        long long position;
        _Bool skin;
        _Bool manualSkin;
        _Bool isCountDown;
    } _recordFlag;
    QPCountDownView *_countDownView;
    QPRecordGuideView *_guideView;
    QPRecordTipGuideView *_tipGuideView;
    long long _backTorchMode;
    _Bool _torchAutoEnabled;
    _Bool _recordFinished;
    CMMotionManager *_motionManager;
    _Bool _videoIsDraft;
    _Bool _videoNeedToEffectView;
    _Bool _countDown;
    UIView *_viewCenter;
    QPPointProgress *_pointProgress;
    UILabel *_durationLabel;
    QPGPUImageView *_gpuImageView;
    UIView *_viewMask;
    UIButton *_buttonPosition;
    UIButton *_buttonSkin;
    UIView *_viewFocusContent;
    UIButton *_buttonFlash;
    UIView *_viewTop;
    UIButton *_buttonClose;
    UIButton *_buttonFinish;
    UIActivityIndicatorView *_activityIndicator;
    UIView *_viewScale;
    UILabel *_labelScale;
    UIView *_viewBottom;
    UIButton *_buttonRecord;
    UILabel *_recordLabel;
    UIButton *_buttonLibrary;
    UITapGestureRecognizer *_tapGesture;
    UIPanGestureRecognizer *_panGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    UILabel *_qupaiLogo;
    NSLayoutConstraint *_viewScaleTopConstraint;
    NSLayoutConstraint *_viewCenterTopConstraint;
    NSLayoutConstraint *_viewCenterHeightConstraint;
    NSLayoutConstraint *_flashButtonTrailConstraint;
    NSLayoutConstraint *_bottomPanelHeightConstraint;
    long long _recordStatus;
}

@property(nonatomic) _Bool countDown; // @synthesize countDown=_countDown;
@property(nonatomic) long long recordStatus; // @synthesize recordStatus=_recordStatus;
@property(nonatomic) _Bool videoNeedToEffectView; // @synthesize videoNeedToEffectView=_videoNeedToEffectView;
@property(nonatomic) _Bool videoIsDraft; // @synthesize videoIsDraft=_videoIsDraft;
@property(nonatomic) __weak NSLayoutConstraint *bottomPanelHeightConstraint; // @synthesize bottomPanelHeightConstraint=_bottomPanelHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *flashButtonTrailConstraint; // @synthesize flashButtonTrailConstraint=_flashButtonTrailConstraint;
@property(nonatomic) __weak NSLayoutConstraint *viewCenterHeightConstraint; // @synthesize viewCenterHeightConstraint=_viewCenterHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *viewCenterTopConstraint; // @synthesize viewCenterTopConstraint=_viewCenterTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *viewScaleTopConstraint; // @synthesize viewScaleTopConstraint=_viewScaleTopConstraint;
@property(nonatomic) __weak UILabel *qupaiLogo; // @synthesize qupaiLogo=_qupaiLogo;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchGesture; // @synthesize pinchGesture=_pinchGesture;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(nonatomic) __weak UIButton *buttonLibrary; // @synthesize buttonLibrary=_buttonLibrary;
@property(nonatomic) __weak UILabel *recordLabel; // @synthesize recordLabel=_recordLabel;
@property(nonatomic) __weak UIButton *buttonRecord; // @synthesize buttonRecord=_buttonRecord;
@property(nonatomic) __weak UIView *viewBottom; // @synthesize viewBottom=_viewBottom;
@property(nonatomic) __weak UILabel *labelScale; // @synthesize labelScale=_labelScale;
@property(nonatomic) __weak UIView *viewScale; // @synthesize viewScale=_viewScale;
@property(nonatomic) __weak UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) __weak UIButton *buttonFinish; // @synthesize buttonFinish=_buttonFinish;
@property(nonatomic) __weak UIButton *buttonClose; // @synthesize buttonClose=_buttonClose;
@property(nonatomic) __weak UIView *viewTop; // @synthesize viewTop=_viewTop;
@property(nonatomic) __weak UIButton *buttonFlash; // @synthesize buttonFlash=_buttonFlash;
@property(nonatomic) __weak UIView *viewFocusContent; // @synthesize viewFocusContent=_viewFocusContent;
@property(nonatomic) __weak UIButton *buttonSkin; // @synthesize buttonSkin=_buttonSkin;
@property(nonatomic) __weak UIButton *buttonPosition; // @synthesize buttonPosition=_buttonPosition;
@property(nonatomic) __weak UIView *viewMask; // @synthesize viewMask=_viewMask;
@property(nonatomic) __weak QPGPUImageView *gpuImageView; // @synthesize gpuImageView=_gpuImageView;
@property(nonatomic) __weak UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(nonatomic) __weak QPPointProgress *pointProgress; // @synthesize pointProgress=_pointProgress;
@property(nonatomic) __weak UIView *viewCenter; // @synthesize viewCenter=_viewCenter;
- (void).cxx_destruct;
- (void)record:(id)arg1 exp:(CDStruct_1b6d18a9)arg2 iso:(double)arg3;
- (void)record:(id)arg1 ev:(double)arg2 percent:(double)arg3;
- (void)record:(id)arg1 exp:(CDStruct_1b6d18a9)arg2 iso:(double)arg3 string:(id)arg4;
- (void)finishRecordFocus:(id)arg1;
- (void)finishRecordScale:(id)arg1;
- (void)record:(id)arg1 endFocus:(struct CGPoint)arg2 autoFocus:(_Bool)arg3;
- (void)record:(id)arg1 beginFocus:(struct CGPoint)arg2 autoFocus:(_Bool)arg3;
- (void)record:(id)arg1 scale:(double)arg2;
- (void)recordWillStop:(id)arg1;
- (void)recordStopCameraCapture:(id)arg1;
- (void)recordSaveFinish:(id)arg1;
- (void)recordOneSectionFinish:(id)arg1;
- (void)record:(id)arg1 time:(float)arg2;
- (id)recordNewVideoURL:(id)arg1;
- (void)recordPreviewFinish:(id)arg1;
- (void)finishRecordHandleWithError:(id)arg1;
- (void)finishRecord;
- (void)viewCenterPinchGesture:(id)arg1;
- (void)viewCenterPanGesture:(id)arg1;
- (void)viewCenterTapGesture:(id)arg1;
- (void)buttonSkinClick:(id)arg1;
- (void)buttonPositionClick:(id)arg1;
- (void)buttonFlashClick:(id)arg1;
- (void)buttonLibraryClick:(id)arg1;
- (void)buttonRecordUp:(id)arg1;
- (void)buttonRecordDown:(id)arg1;
- (void)viewBottomDown:(id)arg1;
- (void)buttonFinishClick:(id)arg1;
- (void)buttonCloseClick:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)removeCountView;
- (void)countDownViewAnimationFailed:(id)arg1;
- (_Bool)countDownView:(id)arg1 showCount:(long long)arg2;
- (void)removeTipGuide;
- (void)chheckAddTipGuide;
- (void)endMotion;
- (void)startMotion;
- (void)changeTorchMode:(long long)arg1;
- (void)updateUIRecordDurationChange;
- (void)updateRecordStatus;
- (void)changeButton:(id)arg1 image:(id)arg2 size:(struct CGSize)arg3 x:(double)arg4;
- (void)setupSubViews;
- (void)removeObserver;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addObserver;
- (id)allObserverKey;
- (void)cameraCanRecord:(CDUnknownBlockType)arg1;
- (void)audioCanRecord:(CDUnknownBlockType)arg1;
- (void)startToPreview;
- (void)checkFreeDiskspace;
- (void)checkDraft;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

