//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL, QPRecord;

@protocol QURecordDelegate <NSObject>
- (void)record:(QPRecord *)arg1 exp:(CDStruct_1b6d18a9)arg2 iso:(double)arg3;
- (void)record:(QPRecord *)arg1 ev:(double)arg2 percent:(double)arg3;
- (void)record:(QPRecord *)arg1 endFocus:(struct CGPoint)arg2 autoFocus:(_Bool)arg3;
- (void)record:(QPRecord *)arg1 beginFocus:(struct CGPoint)arg2 autoFocus:(_Bool)arg3;
- (void)record:(QPRecord *)arg1 scale:(double)arg2;
- (void)recordStopCameraCapture:(QPRecord *)arg1;
- (void)recordWillStop:(QPRecord *)arg1;
- (void)recordSaveFinish:(QPRecord *)arg1;
- (void)recordOneSectionFinish:(QPRecord *)arg1;
- (void)record:(QPRecord *)arg1 time:(float)arg2;
- (NSURL *)recordNewVideoURL:(QPRecord *)arg1;
- (void)recordPreviewFinish:(QPRecord *)arg1;
@end

