//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TBMainRunloopMonitorProtocol-Protocol.h"

@class NSString, NSThread;
@protocol OS_dispatch_source;

@interface TBMainRunloopObserver : NSObject <TBMainRunloopMonitorProtocol>
{
    _Bool _running;
    _Bool _isStop;
    _Bool _isBetaVersion;
    float _blockInterval;
    float _baseInterval;
    CDUnknownBlockType _handlerBlock;
    NSObject<OS_dispatch_source> *_timerSource;
    CDUnknownBlockType _runLoopObserverInnerBlock;
    NSThread *_monitorThread;
}

@property(nonatomic) _Bool isBetaVersion; // @synthesize isBetaVersion=_isBetaVersion;
@property(nonatomic) _Bool isStop; // @synthesize isStop=_isStop;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(retain, nonatomic) NSThread *monitorThread; // @synthesize monitorThread=_monitorThread;
@property(copy, nonatomic) CDUnknownBlockType runLoopObserverInnerBlock; // @synthesize runLoopObserverInnerBlock=_runLoopObserverInnerBlock;
@property(nonatomic) NSObject<OS_dispatch_source> *timerSource; // @synthesize timerSource=_timerSource;
@property(copy, nonatomic) CDUnknownBlockType handlerBlock; // @synthesize handlerBlock=_handlerBlock;
@property(nonatomic) float baseInterval; // @synthesize baseInterval=_baseInterval;
@property(nonatomic) float blockInterval; // @synthesize blockInterval=_blockInterval;
- (void).cxx_destruct;
- (int)getRandomNumber:(int)arg1 to:(int)arg2;
- (void)samplingCal;
- (void)blockTimerFired;
- (void)runMonitor;
- (void)cancelRunLoopMonitor;
- (void)resumeRunLoopMonitor;
- (void)stopRunLoopMonitor;
- (void)startRunLoopMonitor;
- (void)onAppTerminate;
- (void)onEnterBackground;
- (void)onEnterForground;
- (void)onApplicationBecomeActive;
- (void)onApplicationLaunched;
- (void)addActivityObserver;
- (struct __CFRunLoopObserver *)addRunloopObserver:(unsigned long long)arg1 order:(long long)arg2 mode:(struct __CFString *)arg3 handlerBlock:(CDUnknownBlockType)arg4;
- (_Bool)removeObserver:(struct __CFRunLoopObserver *)arg1 runloopMode:(struct __CFString *)arg2;
- (struct __CFRunLoopObserver *)addMainThreadRunloopBlockObserver:(CDUnknownBlockType)arg1;
- (void)setBetaVersionFlag:(_Bool)arg1;
- (void)setBaseBolckInterval:(float)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

