//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (DTMessageBubble)
+ (id)attachmentMaskImageWithType:(unsigned long long)arg1;
+ (id)attachmentMaskImageWithType:(unsigned long long)arg1 sharp:(_Bool)arg2 incomming:(_Bool)arg3;
+ (id)horizontallyFlippedImageFromImage:(id)arg1;
+ (id)bubbleImageViewWithIncoming:(_Bool)arg1 horizontalFlip:(_Bool)arg2 sharp:(_Bool)arg3 type:(unsigned long long)arg4;
@end

