//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol VOIPConferenceDelegate
- (void)onStartMedia:(NSString *)arg1;
- (void)onLWPStatus:(NSString *)arg1;
- (void)onVoIPSessionState:(NSString *)arg1 timeCost:(int)arg2 kbpsCost:(int)arg3;
- (void)onTransportIntensitLocalLevel:(int)arg1 remoteLevel:(int)arg2;
- (void)onVoIPDebug:(NSString *)arg1 type:(unsigned long long)arg2;
- (void)onSwitchToAudio:(NSString *)arg1;
- (void)onHungup:(NSString *)arg1 error:(unsigned long long)arg2 info:(NSString *)arg3 remoteOpenId:(NSString *)arg4;
- (void)onAcceptWithCallId:(NSString *)arg1 type:(unsigned long long)arg2 remoteOpenId:(NSString *)arg3 remoteVideoEnabled:(_Bool)arg4;
- (void)onReceiveRingWithCallId:(NSString *)arg1 extraMsg:(NSString *)arg2 remoteOpenId:(NSString *)arg3;
- (void)onAlertingWitCallId:(NSString *)arg1 openId:(NSString *)arg2 type:(unsigned long long)arg3 extraMsg:(NSString *)arg4;
- (void)onMakeCallReadyWichCallID:(NSString *)arg1 remoteOpenId:(NSString *)arg2;
- (void)onErrorOccur:(unsigned long long)arg1 errorInfo:(NSString *)arg2;
@end

