//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WKAliasModel : NSObject
{
    long long _openId;
    NSString *_alias;
    NSString *_pinyin;
}

@property(copy, nonatomic) NSString *pinyin; // @synthesize pinyin=_pinyin;
@property(copy, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(nonatomic) long long openId; // @synthesize openId=_openId;
- (void).cxx_destruct;

@end

