//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YapDatabaseViewTransaction.h"

@interface YapDatabaseFilteredViewTransaction : YapDatabaseViewTransaction
{
}

- (void)view:(id)arg1 didRepopulateWithFlags:(int)arg2;
- (void)handleReplaceMetadata:(id)arg1 forCollectionKey:(id)arg2 withRowid:(long long)arg3;
- (void)handleReplaceObject:(id)arg1 forCollectionKey:(id)arg2 withRowid:(long long)arg3;
- (void)handleUpdateObject:(id)arg1 forCollectionKey:(id)arg2 withMetadata:(id)arg3 rowid:(long long)arg4;
- (void)handleInsertObject:(id)arg1 forCollectionKey:(id)arg2 withMetadata:(id)arg3 rowid:(long long)arg4;
- (void)repopulateViewDueToFilteringBlockChange;
- (void)repopulateViewDueToParentFilteringBlockChange;
- (void)repopulateViewDueToParentGroupingBlockChange;
- (_Bool)populateView;
- (_Bool)createIfNeeded;

@end

