//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YapDatabaseViewTransaction.h"

@interface YapDatabaseViewTransaction (Mappings)
- (id)metadataAtRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 withMappings:(id)arg3;
- (id)metadataAtIndexPath:(id)arg1 withMappings:(id)arg2;
- (id)objectAtRow:(unsigned long long)arg1 inSection:(unsigned long long)arg2 withMappings:(id)arg3;
- (id)objectAtIndexPath:(id)arg1 withMappings:(id)arg2;
- (_Bool)getRow:(unsigned long long *)arg1 section:(unsigned long long *)arg2 forKey:(id)arg3 inCollection:(id)arg4 withMappings:(id)arg5;
- (id)indexPathForKey:(id)arg1 inCollection:(id)arg2 withMappings:(id)arg3;
- (_Bool)getKey:(id *)arg1 collection:(id *)arg2 forRow:(unsigned long long)arg3 inSection:(unsigned long long)arg4 withMappings:(id)arg5;
- (_Bool)getKey:(id *)arg1 collection:(id *)arg2 atIndexPath:(id)arg3 withMappings:(id)arg4;
- (_Bool)getRowid:(long long *)arg1 collectionKey:(id *)arg2 forRow:(unsigned long long)arg3 inSection:(unsigned long long)arg4 withMappings:(id)arg5;
@end

